
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_ja(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "Edit Modules" => "Edit Modules",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "プレイリスト",
                "UCL_ModulePlayListPage" => "プレイリストを編集する",
                "Create new module" => "Create new module",
                "Module ID" => "Module ID",
                "EditModulewarning" => "内蔵モジュール（Core）の編集は、更新後に無効になります。\n新しいモジュールを作成して、既存のコンテンツを追加または上書きしてください。 \n異なるモジュールに同じIDのコンテンツがある場合、 \n後から読み込まれたモジュールのコンテンツが前のものを上書きします。",
                "EditType" => "Edit type",
                "UCL_ModuleEditType_Builtin" => "Builtin",
                "UCL_ModuleEditType_Runtime" => "Runtime",
                "Save Config" => "Save Config",
                "Load Config" => "Load Config",
                "Open Module Folder" => "Open Module Folder",
                "ModuleService Config" => "ModuleService Config",
                "Loaded modules" => "Loaded modules",
                "Config" => "設定",
                "Current playlist" => "Current playlist",
                "Create new playlist" => "Create new playlist",
                "Load current playlist" => "現在のプレイリストを読み込む",
                "ModulePlayListTip" => "モジュールを有効にするには、 \n「プレイリストを編集する」を押して、 \n有効にしたいモジュールをプレイリストに追加してください。",
                "UCL_ModulePlayListPageTip" => "編集したいプレイリストを選択するか、\n新しいモジュールプレイリストを作成してください。",
                "UCL_ModulePlayListPageSaveTip" => "プレイリストを編集した後、「保存」を押してください。\n 現在のプレイリストを適用するには、\n「現在のプレイリストを読み込む」を押してください。",
                "UCL_CreateNewModulePageTip" => "モジュールIDには「純粋な数字」（例：3387893998）\nを使用しないでください。\nSteamでサブスクライブされたモジュールは数字をIDとして使用します。\nIDがSteamでサブスクライブされたモジュールと同じ場合、上書きされます。",
                "DeleteTargetDes" => "\"{0}\"を削除します",
                "UCL_LocalizeAsset" => "ローカライズ資産",
                "UCL_ModResourceAsset" => "ModResource",
                "UCL_LanguageCodeAsset" => "編輯支援の言語コード",
                "UCL_SteamWorkshopAsset" => "Steamワークショップ",
                "Module Content" => "モジュール内容",
                "Asset Type" => "アセットタイプ",
                "Open Folder" => "フォルダーを開く",
                "SteamAPILangCode" => "SteamAPI言語コード",
                "EWorkshopFileType" => "ワークショップファイルタイプ",
                "Visibility" => "視認性",
                "Dependencies" => "依存関係",
                "PublishedFileId" => "ワークショップアイテムID",
                "ChangeLog" => "変更履歴",
                "Create workshop item" => "ワークショップアイテムを生成する",
                "Update item to workshop" => "アイテムをワークショップに同期する",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公開",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "コミュニティ",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "モジュールを現在のプレイリストに追加する",
                "AddNewModulesToCurrentPlaylistContent" => "新しく購読したモジュールを{0}\n現在のプレイリストに追加しますか({1})？",
                "HideThisOption" => "このオプションを隠す",
                "Asset Group" => "Asset Group",
                "Confirm" => "確認",
                "Cancel" => "キャンセル",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "再インストール",
                "ReInstallAlert" => "再インストールすると、すべてのモジュールが削除されます。\n再インストールを実行しますか？\n（ゲームが正常に動作しない場合や起動しない場合は、再インストールを試みることができます。）",
                "Edit" => "編集",
                "Preview" => "プレビュー",
                "OpenFile" => "ファイルを開く",
                "UCL_LocalizeEditPage" => "ローカライズの編集",
                "UCL_LocalizeEditPage_Language" => "言語",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（UCL_LanguageCodeAsset が未登録）",
                "UCL_LocalizeEditPage_Current" => "現在：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "適用（永続化）",
                "UCL_LocalizeEditPage_Reset" => "リセット",
                "UCL_LocalizeEditPage_ClearOverride" => "永続化された上書きをクリア",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset に上書きあり）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （現在デフォルト値を使用中）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  デフォルト値：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 適用すると UCL_ConfigAsset/{0}.json に永続化され、次回起動時に自動読み込みされます。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ コード制御（セッション内のみ）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "ダウンロード",
                "Key" => "辞書キー",
                "MoveElement" => "移動エレメント",
                "SelectAssetTemplateDes" => "Select {0} asset template",
                "OpenModuleRootFolder" => "Open Module Folder",
                "OpenModuleInstallFolder" => "Open Install Folder",
                "CopyToClipboard" => "クリップボードにコピー",
                "PasteFromClipboard" => "クリップボードから貼り付ける",
                "CopyDescriptionToClipboard" => "複製説明文をクリップボードにコピーする。",
                "Rename" => "リネーム",
                "EditGroup" => "Edit Group",
                "ShowDeleteButton" => "Show Delete Button",
                "CreateFolder" => "フォルダーを作成する",
                "Delete" => "削除",
                "CreateNew" => "Create New",
                "RefreshData" => "Refresh Data",
                "Save" => "Save",
                "Copy" => "コピー",
                "Paste" => "ペースト",
                "Back" => "戻る",
                "Close" => "閉じる",
                "Select" => "選択",
                "Search" => "検索",
                "Add" => "追加",
                "SetCount" => "カウント設定",
                "SaveBeforeExit?" => "Save before exit?",
                "ExitWitoutSave" => "Exit without save",
                "UCL_SelectAsset" => "アセットを選択",
                "UCL_CreateAsset" => "アセットを作成",
                "UCL_SaveSuccess" => "保存に成功しました！",
                _ => null
            };
        }
    }
}
