
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_zhHans(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "ReadOnly" => "只读",
                "Module_ReadOnly_Banner" => "只读（内建参考）— 如需修改请按『复制成可编辑模组』",
                "Fork_To_Editable" => "复制成可编辑模组（Fork）",
                "Fork_NewID_Prompt" => "新模组 ID",
                "Edit Modules" => "编辑模组",
                "ToolBox.Title" => "工具集",
                "ToolBox.MenuButton" => "🧰 打开工具集",
                "ToolBox.Group.Git" => "🔀 Git / 提交",
                "ToolBox.Group.Runtime" => "🖥 模型与运行期",
                "ToolBox.Group.Docs" => "📖 文档与多语系",
                "ToolBox.Group.Setup" => "🧰 环境安装",
                "ToolBox.GitFlattenSync" => "Git 展平同步",
                "ToolBox.GitFlattenSync.Desc" => "把含 submodule 的 repo 展平成纯文件、同步到另一个 repo 的工作目录（来源只读、目标只写文件，两边 git 都不碰）。",
                "ToolBox.GitSubmoduleSync" => "Git Submodule 同步",
                "ToolBox.GitSubmoduleSync.Desc" => "批量对所有 submodule 切默认 branch / pull / push —— 一张状态表看谁 detached、谁 ahead，防止 submodule update 后分支跑掉。",
                "ToolBox.Group.Diagnostics" => "🩺 诊断与修复",
                "ToolBox.MissingReference" => "Missing Reference 排查",
                "ToolBox.MissingReference.Desc" => "扫出「字段指着一个已被删除的对象」与「缺脚本的 Component」，逐条列出位置并可就地清空字段／移除 Component。⚠ 干净的 null 与断掉的引用在 Inspector 上都画成 None，只有后者会崩。",
                "MissingRef.Title" => "Missing Reference 排查",
                "MissingRef.Intro" => "扫描两类断点：<b>⚠ 断掉的对象引用</b>（字段的 instanceID 还在、对象已被删除 —— 清空即可，可逆）与 <b>🔴 缺脚本的 Component</b>（m_Script 为 null —— 只能整个移除，<b>不可逆</b>）。",
                "MissingRef.NotThis" => "⛔ <b>本页不宣称能修 Odin/PropertyEditor 那条 NRE</b>（<i>InspectorConfig.UpdateOdinEditors → ClearEditorsAndRebuild</i>）—— 那条崩在 Unity 内部，最常见成因是「Inspector 正在追踪的对象上有缺脚本的 Component」。⇒ 先用本页清掉 🔴 那几条再看它有没有消失；没消失就不是这个原因。",
                "MissingRef.Scope" => "扫描范围",
                "MissingRef.Scope.Scenes" => "打开中的场景（含未保存的改动）",
                "MissingRef.Scope.Prefabs" => "全部 Prefab（t:Prefab —— 大项目要等数十秒）",
                "MissingRef.Scope.ScriptableObjects" => "全部 ScriptableObject（t:ScriptableObject）",
                "MissingRef.Scan" => "🔍 扫描",
                "MissingRef.NoTarget" => "⚠ <b>一个目标都没扫到</b> —— 这不是「很干净」，是范围没勾对（或场景没开）。",
                "MissingRef.CleanFmt" => "✅ 干净：扫了 {0} 个目标／{1} 个序列化对象，零问题。",
                "MissingRef.FoundFmt" => "找到 <b>⚠ {0}</b> 条断掉的引用、<b>🔴 {1}</b> 个缺脚本 Component（扫了 {2} 个目标／{3} 个序列化对象）。",
                "MissingRef.ListFmt" => "结果（{0} 条）",
                "MissingRef.TruncatedFmt" => "…只画前 {0} 条，全部共 {1} 条（其余见 Console）。",
                "MissingRef.Kind.MissingScript" => "缺脚本 Component",
                "MissingRef.Select" => "选取",
                "MissingRef.Clear" => "清空字段",
                "MissingRef.RemoveComponent" => "移除 Component",
                "MissingRef.FixAllRefsFmt" => "🧹 清空全部断掉的引用（{0}）",
                "MissingRef.ConfirmClearFmt" => "要处理 {0} 个断掉的引用吗？\n\n· 一般字段 ⇒ 清成空（可逆，重新指定即可）\n· <b>数组／List 的元素 ⇒ 整格移除</b>（不是清成 null —— null 洞照样会被 foreach 走到，那只是把崩点换个位置）\n\n会标记场景／资产为已修改。⛔ 不会自动保存 —— 请自己按 Ctrl+S。",
                "MissingRef.ConfirmRemoveFmt" => "要移除这个 GameObject 上全部「缺脚本」的 Component 吗？\n\n{0}\n\n⛔ 不可逆：那些 Component 上序列化的数据会一起消失。\n⚠ 如果脚本只是暂时编不过（改名／assembly 没编好），移除等于把数据丢了。",
                "MissingRef.FixedFmt" => "✅ 已清空 {0} 条。⛔ 尚未保存（Ctrl+S）。",
                "MissingRef.FixFailFmt" => "　⚠ 另有 {0} 条未修复，逐条理由见 Console。",
                "MissingRef.RemovedFmt" => "✅ 已移除 {0} 个缺脚本 Component。⛔ 尚未保存（Ctrl+S）。",
                "ToolBox.LLMModelAdmin" => "本地 LLM 模型",
                "ToolBox.LLMModelAdmin.Desc" => "管理本机大语言模型（ollama）：查环境状态、从策展目录挑模型安装／卸载、跑一句验收。默认收录 Qwen 系列（6GB 显存以下跑得动的那几颗）。",
                "ToolBox.DocSearch" => "文件搜索",
                "ToolBox.DocSearch.Desc" => "跨项目 200+ 篇 markdown 的即时模糊搜索（含同义词展开、当前语系优先）。",
                "ToolBox.LocalizeEdit" => "多语言编辑",
                "ToolBox.LocalizeEdit.Desc" => "编辑 UCL_LocalizeAsset 的多语言字符串表。",
                "ToolBox.ProcessAdmin" => "Process 管理",
                "ToolBox.ProcessAdmin.Desc" => "查看与处置 C# 开出去的外部 process（PID + 名称 + 启动时间三重身份验证，防误杀、防僵尸潮）。",
                "ToolBox.PackageInstall" => "套件安装",
                "ToolBox.PackageInstall.Desc" => "外部工具的检测与安装（目前：Unity 官方 CLI、Unity Pipeline 套件）—— 看装了没、哪一版，一键打开官方安装命令",
                "ToolBox.FreeTimeAdmin" => "🎲 自由时间管理",
                "ToolBox.FreeTimeAdmin.Desc" => "骰面上的活动设置（启用／分组／建议时间／特殊逻辑／执行提示）—— 就地改写活动 md 的 frontmatter，不另存 override。",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "播放集",
                "UCL_ModulePlayListPage" => "编辑播放集",
                "Create new module" => "创建新模组",
                "Module ID" => "模组ID",
                "EditModulewarning" => "内建模组（如 Core）在免安装模式下为只读，仅供参考浏览、无法直接编辑。\n如需修改：开启该模组后按『复制成可编辑模组（Fork）』，会复制出一份可编辑模组。\n不同模组中若有相同 ID 的内容，将由后载入的模组覆盖。",
                "EditType" => "编辑模式",
                "UCL_ModuleEditType_Builtin" => "内建模组",
                "UCL_ModuleEditType_Runtime" => "游戏模组",
                "UCL_ModuleEditType_Template" => "预设范本",
                "Save Config" => "保存设定",
                "Load Config" => "载入设定",
                "Open Module Folder" => "开启模组资料夹",
                "ModuleService Config" => "模组相关设定",
                "Loaded modules" => "目前载入的模组",
                "Config" => "设定",
                "Current playlist" => "目前的模组播放集",
                "Create new playlist" => "创建新模组播放集",
                "Load current playlist" => "载入目前播放集",
                "ModulePlayListTip" => "若要启用模组\n请按下「编辑播放集按钮」\n并将要启用的模组加入播放集中",
                "UCL_ModulePlayListPageTip" => "请选取想要编辑的播放集\n或是创建新模组播放集",
                "UCL_ModulePlayListPageSaveTip" => "编辑播放集后请按下「存档」\n若要套用当前播放集请按下「载入目前播放集」",
                "UCL_CreateNewModulePageTip" => "模组ID请避免使用「纯数字」(例如3387893998)\nSteam订阅的模组以数字为ID\n若ID与Steam订阅的模組相同，将会被复盖",
                "DeleteTargetDes" => "删除「{0}」",
                "UCL_LocalizeAsset" => "本地化设定",
                "UCL_ModResourceAsset" => "模组资源",
                "UCL_LanguageCodeAsset" => "编辑支持的语言码",
                "UCL_SteamWorkshopAsset" => "Steam工作坊",
                "Module Content" => "模组内容",
                "Asset Type" => "资产类型",
                "Open Folder" => "开启资料夹",
                "SteamAPILangCode" => "SteamAPI语言码",
                "EWorkshopFileType" => "工作坊档案类型",
                "Visibility" => "可见度",
                "Dependencies" => "相依性",
                "PublishedFileId" => "工作坊物品ID",
                "ChangeLog" => "变更日誌",
                "Create workshop item" => "生成工作坊物品",
                "Update item to workshop" => "同步物品到工作坊",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公开",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "社区",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "将模组加入当前的播放清单",
                "AddNewModulesToCurrentPlaylistContent" => "是否要将新订阅的模组{0}\n加入到目前的播放清单({1})?",
                "HideThisOption" => "隐藏此选项",
                "Asset Group" => "Asset分组",
                "Confirm" => "确认",
                "Cancel" => "取消",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "重新安装",
                "ReInstallAlert" => "重新安装将会删除所有模组，请问是否要进行重新安装？\n(若游戏无法正常执行或启动，可以尝试重新安装)",
                "Edit" => "编辑",
                "Preview" => "预览",
                "OpenFile" => "开启档案",
                "UCL_LocalizeEditPage" => "本地化语言设置",
                "UCL_LocalizeEditPage_Language" => "语言",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（尚未注册任何 UCL_LanguageCodeAsset）",
                "UCL_LocalizeEditPage_Current" => "当前：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "应用（持久化）",
                "UCL_LocalizeEditPage_Reset" => "重设",
                "UCL_LocalizeEditPage_ClearOverride" => "清除已持久化的覆写",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset 内存有覆写）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （目前使用默认值）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  默认值：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 应用会持久化到 UCL_ConfigAsset/{0}.json，下次启动自动载入。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ 程序控制（纯 session）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "下载",
                "Key" => "索引键",
                "MoveElement" => "改变顺序",
                "SelectAssetTemplateDes" => "请选取新建{0}的范本",
                "OpenModuleRootFolder" => "开启模组资料夹",
                "OpenModuleInstallFolder" => "开启安装资料夹",
                "CopyToClipboard" => "复制到剪贴板",
                "PasteFromClipboard" => "从剪贴板粘贴",
                "CopyDescriptionToClipboard" => "複製描述到剪贴簿",
                "Rename" => "重新命名",
                "EditGroup" => "编辑分组",
                "ShowDeleteButton" => "显示删除按钮",
                "CreateFolder" => "创建资料夹",
                "Delete" => "删除",
                "CreateNew" => "新增",
                "RefreshData" => "刷新资料",
                "Save" => "存档",
                "Copy" => "复制",
                "Paste" => "贴上",
                "Back" => "返回",
                "Close" => "关闭",
                "Select" => "选择",
                "Search" => "搜索",
                "Add" => "新增",
                "SetCount" => "设置数量",
                "SaveBeforeExit?" => "是否先存档后在离开?",
                "ExitWitoutSave" => "不存档 直接离开",
                "UCL_SelectAsset" => "选取资产",
                "UCL_CreateAsset" => "建立资产",
                "UCL_SaveSuccess" => "保存成功！",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / 总览",
                "Welcome.Title" => "👋  欢迎使用 UCL_Core",
                "Welcome.Subtitle" => "跨项目共用的 Unity 基础框架  ·  Welcome 内容版本 v{0}",
                "Welcome.IntroTitle" => "UCL_Core 是什么？",
                "Welcome.IntroBody" => "UCL_Core 是一套跨项目共用的 Unity 基础框架，提供「数据资产 (UCL_Asset) / 模块系统 / 本地化 / Editor Page / Agent Command 跨进程指令系统」等核心组件。\n想快速上手？从下方功能卡片挑一个你最常用的开始。",
                "Welcome.FeaturesTitle" => "核心功能 (点按钮直达)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset 系统",
                "Welcome.Asset.Desc" => "JSON 序列化的设计资产 (卡牌 / 道具 / 怪物等)，编辑器可视化编辑、跨平台读写、SerializeReference 多态支持。",
                "Welcome.Asset.Btn" => "打开 Modules 编辑器",
                "Welcome.Localize.Title" => "🌐  Localize 翻译字串编辑",
                "Welcome.Localize.Desc" => "编辑各语系翻译字串、CurLangKey、PlayerPrefs key。日常切换语言用上方语言栏即可，不必进这页。",
                "Welcome.Localize.Btn" => "打开 Localize 编辑器",
                "Welcome.Lang.Label" => "🌐 语言：",


                "Welcome.Lang.NoneAvailable" => "(尚未发现 UCL_LanguageCodeAsset — 请先建立语言 Asset)",
                "Welcome.Lang.OpenEditor" => "高级编辑…",
                "Welcome.Agent.Title" => "🤖  Agent Commands (agent ↔ Editor 跨进程)",
                "Welcome.Agent.Desc" => "AI agent 写 queue.json、Editor Watcher 自动执行 — 含 FindAssetUsages / ValidateAssetFormat 等内建 Cmd。",
                "Welcome.Agent.Btn" => "打开 Agent Commands 页",
                "Welcome.Editor.Title" => "🪟  Editor Pages 框架",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — 一致风格的 IMGUI 页面堆栈，支持搜索下拉、HelpURL 跳转、TopBar 客制。",
                "Welcome.Editor.Btn" => "PlayerPrefs 编辑范例",
                "Welcome.DocBtn" => "📖 文档",

                "Welcome.DocsTitle" => "📚 文档总入口",
                "Welcome.Docs.Index" => "UCL_Core 文档 index",
                "Welcome.Docs.Architecture" => "Agent Command 整体架构",
                "Welcome.Docs.CreateCmd" => "新增 Cmd SOP",
                "Welcome.Docs.Validate" => "验证 UCL_Asset 格式",
                "Welcome.Docs.CompileError" => "🔧 Compile Error 排查工作流",
                // Welcome 页的 Skill 入口卡片（小，导向独立的 AgentSkillManager 页）
                "Welcome.SkillEntry.Title" => "🧩  Agent Skill 管理",
                "Welcome.SkillEntry.Desc" => "把 UCL_Core 的 commit / 进酒馆 / 排查编译错等工作流抽成 AI agent Skill — 不同 agent (Claude Code / Cursor / Antigravity / Gemini) 各自的安装路径由管理页统一处理。第一次开 Welcome 会自动弹出。",
                "Welcome.SkillEntry.OpenBtn" => "🛠 打开 Skill 管理页",

                // 独立的 UCL_AgentSkillManagerPage
                "AgentSkill.Title" => "🛠 Agent Skill Manager",
                "AgentSkill.Subtitle" => "把 UCL_Core 的工作流安装给各家 AI agent 用",
                "AgentSkill.ConceptTitle" => "为什么有这页？",
                "AgentSkill.ConceptBody" => "UCL_Core/Skills~/ 内每个 skill 是一份「lazy-load 工作流」— agent 看到触发词才载入完整 SOP，平时不吃 context。每个 agent 家有自家路径惯例：Claude Code → .claude/skills/、Antigravity → .agents/rules/（规划中：Cursor → .cursor/rules/、Gemini）。本页负责对所有支援的 target 统一安装。",
                "AgentSkill.OneClick.Title" => "一键安装（支援 Claude Code / Antigravity）",
                "AgentSkill.OneClick.Desc" => "跑 Tools~/install_skills.py --target <X> 把所有 skill 拷到对应 dst（Claude → .claude/skills/、Antigravity → .agents/rules/）。幂等可重複跑；侦测本地修改不会复写。",
                "AgentSkill.Status.NotInstalled" => "⚠ 尚未安装 — 点下方按钮一键装起来",
                "AgentSkill.Status.Synced" => "✓ 已安装且与来源内文一致",
                "AgentSkill.Status.Stale" => "⚠ 已安装内文与来源不一致（来源已更新或本地被改动）— 建议重装／强制同步",
                "AgentSkill.Status.LegacyNoHash" => "⚠ 旧版 marker 无 source_hash 栏位 — 重装一次即可刷新比对基准",
                "AgentSkill.Status.UnknownHead" => "已安装但无法判定 UCL_Core HEAD（git 不在 PATH？）",
                "AgentSkill.Status.NoProjectRoot" => "找不到 host project root（没有 .claude/ 或 .git/）— 请手动执行 Tools~/install_skills.py --project-root <path>",
                "AgentSkill.Status.NoUCLCore" => "找不到 UCL_Core 路径（UCL_EditorPath.CorePath 为空）",
                "AgentSkill.HostRoot" => "Project root: {0}",
                "AgentSkill.Btn.Install" => "🚀 安装",
                "AgentSkill.Btn.InstallAll" => "🚀 一键安装全部 target",
                "AgentSkill.Btn.ForceSyncAll" => "⚡ 强制同步全部 (复盖本地改动)",
                "AgentSkill.Btn.ForceSyncAll.Synced" => "✅ 已全部同步 (仍可按下强制重写)",
                "AgentSkill.SkippedWarn" => "⚠ 上次安装有 {0} 档因本地改动被跳过，内容未更新 — 用「重装」或「强制同步」复盖 (详见 Console)",
                "AgentSkill.Btn.Sync" => "🔄 同步到当前版本",
                "AgentSkill.Btn.Reinstall" => "🔁 重新安装",
                "AgentSkill.Btn.Refresh" => "重新整理",
                "AgentSkill.Btn.Doc" => "📖 Skills~/README",
                "AgentSkill.Btn.ResetAck" => "重设首次弹出",
                "AgentSkill.Matrix.Title" => "🎛 Per-Agent × Per-Skill 切换",
                "AgentSkill.Matrix.Body" => "用下拉选单选择 agent，查看/管理该 agent 的逐 skill 安装状态。installed/drift 为各 agent 独立；disabled（UCL_SkillConfigAsset）跨 agent 共用：",
                "AgentSkill.Matrix.NoSource" => "(找不到 UCL_Core/Skills~/ 来源目录)",
                "AgentSkill.Matrix.Status.DisabledPendingRemove" => "🚫停用·待移除",
                "AgentSkill.Matrix.Status.Disabled" => "🚫停用",
                "AgentSkill.Matrix.Status.NotInstalled" => "未装",
                "AgentSkill.Matrix.Status.Drift" => "⚠改动",
                "AgentSkill.Matrix.Status.Synced" => "✓同步",
                "AgentSkill.Matrix.Btn.Enable" => "启用",
                "AgentSkill.AckToggle" => " 永不自动弹出本页(即使 skill 有更新；仍可从菜单手动开启)",
                "AgentSkill.LastChangesLabel" => "上次自动弹出原因 — skill 变动: {0}",
                "AgentSkill.AckVersionLabel" => "AcknowledgedVersion: {0}",
                "AgentSkill.NotSet" => "(未设)",

                "Welcome.AutoOpenToggle" => " 不再自动弹出此页 (仍可从菜单 UCL → Welcome 手动开启)",
                "Welcome.ResetButton" => "重置首次弹出 (下次重启 Editor 会再显示一次)",
                "Welcome.ResetLog" => "[UCL_Welcome] 已重置首次弹出状态。下次 domain reload 会再次显示。",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(未设)",
                "Welcome.Search.Title" => "🔍 文档搜索",
                "Welcome.Search.Button" => "搜索",
                "Welcome.Search.Hint" => "支持同义词展开 (读 Docs/_synonyms.txt) — 例：搜「物品」也能命中标题写「道具」的文档。多词以空格分隔 (AND 模式)。",
                "Welcome.Search.NoResults" => "(无命中)",
                "Welcome.Search.ResultsCount" => "命中 {0} 篇 (共扫 {1} 篇)",
                "Welcome.Search.OpenButton" => "📖 打开文件",
                "Welcome.Search.OpenPageButton" => "🔍 打开文件搜索页",
                "DocSearch.Advanced" => "高级选项",
                "DocSearch.Mode" => "搜索模式",
                "DocSearch.Limit" => "结果上限",
                "DocSearch.SynonymsPath" => "同义词文件路径",
                "DocSearch.IncludeArchived" => "包含 archived 文档",
                "DocSearch.Reveal" => "📂 定位",
                "DocSearch.Preview" => "📄 预览",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "刷新",
                "AgentCmd.RunPending" => "执行待办指令",
                "AgentCmd.ClearFailed" => "清除失败",
                "AgentCmd.OpenFolder" => "打开文件夹",
                "AgentCmd.QueuePath" => "Queue: {0}",
                "AgentCmd.QueueSelector" => "Queue 切换",
                "AgentCmd.QueueDefault" => "共用 default ({0})",
                "AgentCmd.PageInfo" => "第 {0}/{1} 页（共 {2} 笔）",
                "AgentCmd.CmdInfoToggle" => "指令说明",
                "AgentCmd.Stats" => "总计: {0} | OneShot: {1} | Repeatable: {2}",
                "AgentCmd.Commands" => "指令清单",
                "AgentCmd.QueueEmpty" => "(queue 是空的 — 从下方挑一个 Command 加入，或直接编辑 queue.json)",
                "AgentCmd.Remove" => "移除",
                "AgentCmd.AddCommand" => "新增指令",
                "AgentCmd.NoHandlers" => "(尚未注册任何 Handler — 请写一个 class 继承 UCL_AgentCommandHandlerBase)",
                "AgentCmd.Command" => "指令:",
                "AgentCmd.Mode" => "模式:",
                "AgentCmd.Description" => "描述:",
                "AgentCmd.Args" => "参数:",
                "AgentCmd.ArgsFormat" => "(格式: k=v;k=v)",
                "AgentCmd.ArgsSchema" => "  Args Schema: {0}",
                "AgentCmd.Example" => "  示例: {0}",
                "AgentCmd.FillExample" => "填入示例",
                "AgentCmd.ViewHelp" => "查看说明",
                "AgentCmd.AddButton" => "加入「{0}」({1})",
                "AgentCmd.SaveTemplateName" => "存为模板 — 名称:",
                "AgentCmd.SaveTemplate" => "保存模板",
                "AgentCmd.TemplateNotes" => "模板备注:",
                "AgentCmd.Templates" => "模板",
                "AgentCmd.TemplatesCount" => " {0} 条",
                "AgentCmd.Search" => "搜索:",
                "AgentCmd.Clear" => "清空",
                "AgentCmd.NoTemplates" => "(没有模板 — 在上方「新增指令」区块填好后按「保存模板」)",
                "AgentCmd.ApplyToForm" => "应用到表单",
                "AgentCmd.AddToQueue" => "加入 Queue",
                "AgentCmd.Delete" => "删除",
                "AgentCmd.History" => "历史记录",
                "AgentCmd.QueueUnrecorded" => "(未记录)",
                "AgentCmd.FoldQueue" => "📋 队列现况",
                "AgentCmd.FoldAdd" => "➕ 新增指令",
                "AgentCmd.FoldTips" => "💡 提示",
                "AgentCmd.Cancel" => "取消",
                "AgentCmd.FailedTitle" => "❌ 失败记录（可补跑）",
                "AgentCmd.FailedCount" => "{0} 笔",
                "AgentCmd.FailedLegacy" => "另有 {0} 笔旧失败没有参数记录，无法补跑（详情见 _cmd_errors/）",
                "AgentCmd.FailedEmpty" => "没有失败记录。失败的 OneShot 会即时出队，记录落在 _cmd_failed/。",
                "AgentCmd.FailedRetry" => "补跑",
                "AgentCmd.FailedToForm" => "填回表单",
                "AgentCmd.FailedClearAll" => "清除全部记录",
                "AgentCmd.FailedClearAllConfirm" => "要删掉 {0} 笔失败记录吗？只删记录、不影响任何 queue —— 但删掉之后就查不到失败过什么了。",
                "AgentCmd.FailedRetryWarning" => "⚠ 补跑＝重新执行一次，副作用会重放（酒馆公告会重发、同 SHA 领两次薪、转账会重转）。先确认这笔真的没生效再按。",
                "AgentCmd.FailedRetried" => "已补跑 ×{0}",
                "AgentCmd.FailedRetryCmdId" => "补跑产生的 cmd：{0}（{1}）—— 结果查 _cmd_results/",
                "AgentCmd.FailedOpenReport" => "打开报告",
                "AgentCmd.QueueFilter" => "Queue 筛选",
                "AgentCmd.QueueFilterAll" => "(全部)",
                "AgentCmd.HistoryCount" => " {0} 条",
                "AgentCmd.NoHistory" => "(没有符合的历史 — 按下「新增指令」后会自动记录到这里)",
                "AgentCmd.Cleanup" => "清理 —",
                "AgentCmd.OlderThanDays" => "早于(天):",
                "AgentCmd.DeleteOlder" => "删除过旧",
                "AgentCmd.Dedupe" => "去除重复",
                "AgentCmd.ClearAll" => "全部清空",
                "AgentCmd.ClearAllConfirmTitle" => "全部清空历史？",
                "AgentCmd.ClearAllConfirmBody" => "确定要删除 {0} 条历史记录吗？此动作不可逆。",
                "AgentCmd.ConfirmDelete" => "删除",
                "AgentCmd.ConfirmCancel" => "取消",
                "AgentCmd.ReAdd" => "重新加入",
                "AgentCmd.ToTemplate" => "→ 模板",
                "AgentCmd.AutoWatcher" => "自动触发器",
                "AgentCmd.LastTrigger" => "上次触发: {0}",
                "AgentCmd.Never" => "(从未)",
                "AgentCmd.SimulateTrigger" => "模拟触发",
                "AgentCmd.Tips" => "小提示",
                "AgentCmd.Tip_OneShot" => "- OneShot: 成功执行后会直接从 queue 中移除",
                "AgentCmd.Tip_Repeatable" => "- Repeatable: 每次 Run 都会再执行一次，并把 RunCount +1",
                "AgentCmd.Tip_WaitInit" => "- Run 之前自动 await UCL_ModuleService.WaitUntilInitialized — 确保模组系统已就绪",
                "AgentCmd.Tip_FailedKept" => "- 失败的指令会把错误讯息写进 LastRunError 并留在 queue (不会被移除)",
                "AgentCmd.Tip_Watcher" => "- Auto-Watcher 启用时: 外部写入 AgentCommands/pending.trigger 即会自动触发 Run Pending (无需手动点按钮)",
                "AgentCmd.Tip_ExportCatalog" => "- 想导出 Cmd 目录？加一笔 'ExportCommandCatalog' Cmd 即可 (不再有独立按钮)",

                // ==== UCL_LoginStatusPage ====
                "LoginStatus.Title" => "登入状态",
                "LoginStatus.Btn.Refresh" => "🔄 刷新",
                "LoginStatus.Btn.Logout" => "🌙 登出",
                "LoginStatus.Btn.ForceRm" => "✂ 强制移除",
                "LoginStatus.Btn.Morning" => "🌅 Morning (登入)",
                "LoginStatus.Btn.ConfirmRemove" => "确定 ✂",
                "LoginStatus.Collision.Title" => "<color=#ff9966><b>⚠ Session-key COLLISION 侦测</b></color>",
                "LoginStatus.Collision.Desc" => "cwd-hash session_key 在多 Claude IDE 同 cwd 下会撞。下列 session_key 对到 ≥ 2 lock:",
                "LoginStatus.Collision.Hint" => "→ 用 pid 跟 locked_at 区分自己 process。Morning ritual 该带 --strict-persona。",
                "LoginStatus.Locks.HeaderFmt" => "<b>当前活跃 Persona Lock ({0})</b>",
                "LoginStatus.Locks.Empty" => "(无 active lock — 所有 persona offline)",
                "LoginStatus.Col.Persona" => "Persona",
                "LoginStatus.Col.Agent" => "Agent",
                "LoginStatus.Col.Bank" => "账户",
                "LoginStatus.NowStatus.None" => "（没设定当前状态）",
                "LoginStatus.Col.Pid" => "pid",
                "LoginStatus.Col.LockedAt" => "锁定时间 (UTC)",
                "LoginStatus.Col.SessionKey" => "session_key",
                "LoginStatus.Col.Token" => "Session Token",
                "LoginStatus.Token.None" => "<color=#888888>(无 token)</color>",
                "LoginStatus.Col.Status" => "状态",
                "LoginStatus.Col.Wake" => "Wake#",
                "LoginStatus.Col.LayerRole" => "Layer 角色",
                "LoginStatus.Col.LastActive" => "最后活跃 (UTC)",
                "LoginStatus.ManualLogin.Title" => "<b>手动 Morning (登入)</b>",
                "LoginStatus.Field.Agent" => "Agent:",
                "LoginStatus.Field.Persona" => "Persona:",
                "LoginStatus.Field.Model" => "Model:",
                "LoginStatus.Field.ForkName" => "Fork 名称:",
                "LoginStatus.Login.RejectHint" => "(agent / persona 任一为空都会被拒绝)",
                "LoginStatus.Pool.HeaderFmt" => "<b>Persona 池 ({0})</b>",
                "LoginStatus.Pool.EmptyFmt" => "(无 registry — `{0}` 不存在或空)",
                "LoginStatus.Dialog.ForceRm.Title" => "强制移除 Lock",
                "LoginStatus.Dialog.ForceRm.BodyFmt" => "确定强制删除 lock?\n\n{0}\n\n注意: persona registry status 不会自动改成 offline, 需后续手动修正。建议优先用 Logout (走 goodnight ritual)。",
                // Logout 确认 popup（取消／登出；防误按）
                "LoginStatus.Dialog.Logout.TitleFmt" => "确认登出 — {0}",
                "LoginStatus.Dialog.Logout.BodyFmt" =>
                    "即将登出下列 persona（**不写信**：删 lock＝下线，酒馆广播会标明未留信）：\n\n" +
                    "  Persona       : {0}\n" +
                    "  Agent         : {1}\n" +
                    "  Bank          : {2}\n" +
                    "  Locked at     : {3}\n" +
                    "  Session token : {4}\n\n" +
                    "要写收尾信请改走晚安流程（senate cmd goodnight-check）。",


                // ==== UCL_AssetReferencePage ====
                "AssetRef.Btn.Entry" => "🔗 引用查询",
                "AssetRef.TitleFmt" => "引用查询: {0}/{1}",
                "AssetRef.Btn.Back" => "← 返回",
                "AssetRef.Btn.Rescan" => "🔄 重新扫描",
                "AssetRef.Btn.Open" => "📂 打开",
                "AssetRef.NoTarget" => "（未指定查询目标）",
                "AssetRef.NotScanned" => "尚未扫描…",
                "AssetRef.TargetFmt" => "目标: {0} / {1}",
                "AssetRef.ReverseHeaderFmt" => "被引用（谁引用我）: {0} 笔",
                "AssetRef.ForwardHeaderFmt" => "引用到（我引用谁）: {0} 笔",
                "AssetRef.Empty" => "（无）",


                // ==== UCL_MarkdownViewerPage ====
                "MdViewer.Title" => "Markdown 检视器",
                "MdViewer.LoadFailedFmt" => "⚠ 加载失败: {0}",
                "MdViewer.Frontmatter" => "Frontmatter",
                "MdViewer.RelatedTitle" => "<b>🔗 关联文件</b>",

                // ==== UCL_PlayerPrefsEditPage ====
                "PlayerPrefs.Btn.Refresh" => "刷新",
                "PlayerPrefs.Btn.DeleteAll" => "!!! 删除所有 PLAYERPREFS !!!",
                "PlayerPrefs.Dialog.DeleteAll.Title" => "危险操作",
                "PlayerPrefs.Dialog.DeleteAll.Body" => "确定要删除「全部」PlayerPrefs 吗?此动作不可恢复!",
                "PlayerPrefs.Dialog.DeleteOne.Title" => "确认删除",
                "PlayerPrefs.Dialog.DeleteOne.BodyFmt" => "确定要删除 key「{0}」吗?",

                // ==== UCL_ChatTavernPage ====
                "Tavern.Title" => "聊天酒馆",
                "Tavern.Btn.Refresh" => "刷新",
                "Tavern.Btn.AutoPoll" => "Auto-Poll",
                "Tavern.Btn.CancelHandshake" => "🛑 中止握手",
                "Tavern.Btn.CancelHandshakeNone" => "🛑 中止握手 (无)",
                "Tavern.Btn.NewRoom" => "+ 新房间",
                "Tavern.Btn.NewIdentity" => "+ 新身分",
                "Tavern.Btn.CancelCreate" => "− 取消",
                "Tavern.Btn.Create" => "创建",
                "Tavern.Btn.Send" => "发送",
                "Tavern.Btn.JoinRoomFmt" => "加入「{0}」",
                "Tavern.Btn.LeaveRoomFmt" => "离开「{0}」",
                "Tavern.SelectRoomFirst" => "请先选择或建立一个房间。",
                "Tavern.TopPanel.Title" => "控制区（房间 / 身分 / 角色 Mapping / 发言）",
                "Tavern.Field.Room" => "房间:",
                "Tavern.Field.Identity" => "身分:",
                "Tavern.Field.Meta" => "meta (k=v;k=v)",
                "Tavern.Field.Refs" => "refs (path|path)",
                "Tavern.Room.Empty" => "(尚无房间 — 用下面 + 新房间)",
                "Tavern.Room.NeedSelect" => "(选房间+身分后可加入/离开)",
                "Tavern.Room.MemberCountFmt" => "登录 {0} 人",
                "Tavern.Room.NotJoined" => "(尚未进房)",
                "Tavern.Room.MemberTooltip" => "曾经 join 过的累计人数，不代表当前活跃\n(agent 是 turn-based，turn 结束 ≠ 离房)",
                "Tavern.Identity.Empty" => "(尚无身分 — 用下面 + 新身分)",
                "Tavern.Identity.NamingHint1" => "命名约定: id 用 <model>-<persona>，例: claude-da-xiaojie / gemini-da-xiaojie / gpt-shifu",
                "Tavern.Identity.NamingHint2" => "display_name 用 agent 自家称呼，例: Claude大小姐 / Gemini大小姐 / GPT师傅",
                "Tavern.Balance.Fmt" => "💰 余额: <color=#ffd700><b>{0}</b></color> Token",
                "Tavern.CharMapping.TitleOpen" => "▼ 角色 Mapping",
                "Tavern.CharMapping.TitleClosed" => "▶ 角色 Mapping",
                "Tavern.CharMapping.Subtitle" => "(sender_id 没对应角色时的 fallback 链)",
                "Tavern.CharMapping.Default" => "预设",
                "Tavern.CharMapping.DefaultHint" => "(建议用已建 Identity Asset 的 id)",
                "Tavern.CharMapping.AliasesLabel" => "Aliases (sender_id → identity_id):",
                "Tavern.CharMapping.NewAlias" => "+ 新 alias",
                "Tavern.Messages.HeaderFmt" => "# 🍺 {0} (seq={1})",
                "Tavern.Messages.Empty" => "_(尚无消息)_",
                "Tavern.Messages.PagerFmt" => "第 {0}/{1} 页 · 共 {2} 笔",
                "Tavern.Messages.JumpTo" => "跳至",
                "Tavern.Messages.JumpBtn" => "跳转",
                "Tavern.Reply.IndicatorFmt" => "↩ 回复 seq={0}",
                "Tavern.Input.NoIdentity" => "(尚未选择身分)",
                "Tavern.Input.SpeakingAsFmt" => "以「{0}」({1}) 身分发言",
                "Tavern.Join.MsgFmt" => "{0} 进入了酒馆",
                "Tavern.Leave.MsgFmt" => "{0} 离开了酒馆",
                "Tavern.Err.NoIdentity" => "身分不存在",
                "Tavern.Err.NoRoom" => "房间未选",
                "Tavern.Err.RoomIdEmpty" => "Room id 不能为空",
                "Tavern.Err.IdentityIdEmpty" => "Identity id 不能为空",


                _ => null
            };
        }
    }
}
