
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_zhHant(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "Edit Modules" => "編輯模組",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "播放集",
                "UCL_ModulePlayListPage" => "編輯播放集",
                "Create new module" => "創建新模組",
                "Module ID" => "模組ID",
                "EditModulewarning" => "對內建模組(Core)的編輯，會在更新後失效\n請建立新的模組，來新增或覆蓋原有內容\n不同模組中，若有相同ID的內容\n將會由後載入的模組的內容覆蓋",
                "EditType" => "編輯模式",
                "UCL_ModuleEditType_Builtin" => "內建模組",
                "UCL_ModuleEditType_Runtime" => "遊戲模組",
                "UCL_ModuleEditType_Template" => "預設範本",
                "Save Config" => "保存設定",
                "Load Config" => "載入設定",
                "Open Module Folder" => "開啟模組資料夾",
                "ModuleService Config" => "模組相關設定",
                "Loaded modules" => "目前載入的模組",
                "Config" => "設定",
                "Current playlist" => "目前的模組播放集",
                "Create new playlist" => "創建新模組播放集",
                "Load current playlist" => "載入目前播放集",
                "ModulePlayListTip" => "若要啟用模組\n請按下「編輯播放集按鈕」\n並將要啟用的模組加入播放集中",
                "UCL_ModulePlayListPageTip" => "請選取想要編輯的播放集\n或是創建新模組播放集",
                "UCL_ModulePlayListPageSaveTip" => "編輯播放集後請按下「存檔」\n若要套用當前播放集請按下「載入目前播放集」",
                "UCL_CreateNewModulePageTip" => "模組ID請避免使用「純數字」(例如3387893998)\nSteam訂閱的模組以數字為ID\n若ID與Steam訂閱的模組相同，將會被覆蓋",
                "DeleteTargetDes" => "刪除「{0}」",
                "UCL_LocalizeAsset" => "本地化設定",
                "UCL_ModResourceAsset" => "模組資源",
                "UCL_LanguageCodeAsset" => "支援的語言碼",
                "UCL_SteamWorkshopAsset" => "Steam工作坊",
                "Module Content" => "模組內容",
                "Asset Type" => "資產類型",
                "Open Folder" => "開啟資料夾",
                "SteamAPILangCode" => "SteamAPI語言碼",
                "EWorkshopFileType" => "工作坊檔案類型",
                "Visibility" => "可見度",
                "Dependencies" => "相依性",
                "PublishedFileId" => "工作坊物品ID",
                "ChangeLog" => "變更日誌",
                "Create workshop item" => "生成工作坊物品",
                "Update item to workshop" => "同步物品到工作坊",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公開",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "社區",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "將模組加入當前的播放清單",
                "AddNewModulesToCurrentPlaylistContent" => "是否要將新訂閱的模組{0}\n加入到目前的播放清單({1})?",
                "HideThisOption" => "隱藏此選項",
                "Asset Group" => "Asset分組",
                "Confirm" => "確認",
                "Cancel" => "取消",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "重新安裝",
                "ReInstallAlert" => "重新安裝將會刪除所有模組，請問是否要進行重新安裝？\n(若遊戲無法正常執行或啟動，可以嘗試重新安裝)",
                "Edit" => "編輯",
                "Preview" => "預覽",
                "OpenFile" => "開啟檔案",
                "UCL_LocalizeEditPage" => "本地化語言設定",
                "UCL_LocalizeEditPage_Language" => "語言",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（尚未註冊任何 UCL_LanguageCodeAsset）",
                "UCL_LocalizeEditPage_Current" => "當前：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "套用（持久化）",
                "UCL_LocalizeEditPage_Reset" => "重設",
                "UCL_LocalizeEditPage_ClearOverride" => "清除已持久化的覆寫",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset 內存有覆寫）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （目前使用預設值）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  預設值：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 套用會持久化到 UCL_ConfigAsset/{0}.json，下次啟動自動載入。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ 程式控制（純 session）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "下載",
                "Key" => "索引鍵",
                "MoveElement" => "改變順序",
                "SelectAssetTemplateDes" => "請選取新建{0}的範本",
                "OpenModuleRootFolder" => "開啟模組資料夾",
                "OpenModuleInstallFolder" => "開啟安裝資料夾",
                "CopyToClipboard" => "複製到剪貼簿",
                "PasteFromClipboard" => "從剪貼簿貼上",
                "CopyDescriptionToClipboard" => "複製描述到剪貼簿",
                "Rename" => "重新命名",
                "EditGroup" => "編輯分組",
                "ShowDeleteButton" => "顯示刪除按鈕",
                "CreateFolder" => "創建資料夾",
                "Delete" => "刪除",
                "CreateNew" => "新增",
                "RefreshData" => "刷新資料",
                "Save" => "存檔",
                "Copy" => "複製",
                "Paste" => "貼上",
                "Back" => "返回",
                "Close" => "關閉",
                "Select" => "選擇",
                "Search" => "搜尋",
                "Add" => "新增",
                "SetCount" => "設定數量",
                "SaveBeforeExit?" => "是否先存檔後在離開?",
                "ExitWitoutSave" => "不存檔 直接離開",
                "UCL_SelectAsset" => "選取資產",
                "UCL_CreateAsset" => "建立資產",
                "UCL_SaveSuccess" => "儲存成功！",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / 總覽",
                "Welcome.Title" => "👋  歡迎使用 UCL_Core",
                "Welcome.Subtitle" => "跨專案共用的 Unity 基礎框架  ·  Welcome 內容版本 v{0}",
                "Welcome.IntroTitle" => "UCL_Core 是什麼？",
                "Welcome.IntroBody" => "UCL_Core 是一套跨專案共用的 Unity 基礎框架，提供「資料資產(UCL_Asset)/ 模組系統 / 本地化 / Editor Page / Agent Command 跨 process 指令系統」等核心元件。\n想快速上手？從下方功能卡片挑一個你最常用的開始。",
                "Welcome.FeaturesTitle" => "核心功能(點按鈕直達)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset 系統",
                "Welcome.Asset.Desc" => "JSON 序列化的設計資產(卡牌 / 道具 / 怪物等)，編輯器可視化編輯、跨平台讀寫、SerializeReference 多型支援。",
                "Welcome.Asset.Btn" => "打開 Modules 編輯器",
                "Welcome.Localize.Title" => "🌐  Localize 翻譯字串編輯",
                "Welcome.Localize.Desc" => "編輯各語系翻譯字串、CurLangKey、PlayerPrefs key。日常切換語言用上方語言列即可，不必進這頁。",
                "Welcome.Localize.Btn" => "打開 Localize 編輯器",
                "Welcome.Lang.Label" => "🌐 語言：",
                "Welcome.Lang.NoneAvailable" => "(尚未發現 UCL_LanguageCodeAsset — 請先建立語言 Asset)",
                "Welcome.Lang.OpenEditor" => "進階編輯…",
                "Welcome.Agent.Title" => "🤖  Agent Commands(agent ↔ Editor 跨 process)",
                "Welcome.Agent.Desc" => "AI agent 寫 queue.json、Editor Watcher 自動執行 — 含 ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat 等內建 Cmd。",
                "Welcome.Agent.Btn" => "打開 Agent Commands 頁",
                "Welcome.Editor.Title" => "🪟  Editor Pages 框架",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — 一致風格的 IMGUI 頁面堆疊，支援搜尋下拉、HelpURL 跳轉、TopBar 客製。",
                "Welcome.Editor.Btn" => "PlayerPrefs 編輯範例",
                "Welcome.DocBtn" => "📖 文件",
                "Welcome.DocsTitle" => "📚 文件總入口",
                "Welcome.Docs.Index" => "UCL_Core 文件 index",
                "Welcome.Docs.Architecture" => "Agent Command 整體架構",
                "Welcome.Docs.CreateCmd" => "新增 Cmd SOP",
                "Welcome.Docs.Validate" => "驗證 UCL_Asset 格式",
                "Welcome.Docs.CompileError" => "🔧 Compile Error 排查工作流",
                // Welcome 頁的 Skill 入口卡片（小，導向獨立的 AgentSkillManager 頁）
                "Welcome.SkillEntry.Title" => "🧩  Agent Skill 管理",
                "Welcome.SkillEntry.Desc" => "把 UCL_Core 的 commit / 進酒館 / 排查編譯錯等工作流抽成 AI agent Skill — 不同 agent (Claude Code / Cursor / Antigravity / Gemini) 各自的安裝路徑由管理頁統一處理。第一次開 Welcome 會自動彈出。",
                "Welcome.SkillEntry.OpenBtn" => "🛠 打開 Skill 管理頁",

                // 獨立的 UCL_AgentSkillManagerPage
                "AgentSkill.Title" => "🛠 Agent Skill Manager",
                "AgentSkill.Subtitle" => "把 UCL_Core 的工作流安裝給各家 AI agent 用",
                "AgentSkill.ConceptTitle" => "為什麼有這頁？",
                "AgentSkill.ConceptBody" => "UCL_Core/Skills~/ 內每個 skill 是一份「lazy-load 工作流」— agent 看到觸發詞才載入完整 SOP，平時不吃 context。Claude Code 不掃 submodule，所以要把 SKILL.md 拷到專案的 .claude/skills/。Cursor / Antigravity / Gemini 各有自家路徑慣例（cursor 用 .cursor/rules/、antigravity 待實作）— 本頁負責統一安裝。",
                "AgentSkill.OneClick.Title" => "一鍵安裝（目前：Claude Code）",
                "AgentSkill.OneClick.Desc" => "跑 Tools~/install_skills.py 把所有 skill 拷到 <project-root>/.claude/skills/。冪等可重複跑；偵測本地修改不會覆寫。",
                "AgentSkill.Status.NotInstalled" => "⚠ 尚未安裝 — 點下方按鈕一鍵裝起來",
                "AgentSkill.Status.Synced" => "✓ 已安裝且同步（UCL_Core commit: {0}）",
                "AgentSkill.Status.Stale" => "⚠ UCL_Core 已 bump — 已安裝 {0}，當前 {1}，建議同步",
                "AgentSkill.Status.UnknownHead" => "已安裝但無法判定 UCL_Core HEAD（git 不在 PATH？）",
                "AgentSkill.Status.NoProjectRoot" => "找不到 host project root（沒有 .claude/ 或 .git/）— 請手動執行 Tools~/install_skills.py --project-root <path>",
                "AgentSkill.Status.NoUCLCore" => "找不到 UCL_Core 路徑（UCL_EditorPath.CorePath 為空）",
                "AgentSkill.HostRoot" => "Project root: {0}",
                "AgentSkill.Btn.Install" => "🚀 一鍵安裝全部",
                "AgentSkill.Btn.Sync" => "🔄 同步到當前版本",
                "AgentSkill.Btn.Reinstall" => "🔁 重新安裝",
                "AgentSkill.Btn.Refresh" => "重新整理",
                "AgentSkill.Btn.Doc" => "📖 Skills~/README",
                "AgentSkill.Btn.ResetAck" => "重設首次彈出",
                "AgentSkill.Matrix.Title" => "🎛 Per-Agent × Per-Skill 切換 (TODO)",
                "AgentSkill.Matrix.Body" => "之後會在這裡分 agent / 分 skill 各自開關（例如不裝 ucl-hook-setup 因為已配過）。目前先固定全裝。下方列出 source 端可用 skill：",
                "AgentSkill.Matrix.NoSource" => "(找不到 UCL_Core/Skills~/ 來源目錄)",
                "AgentSkill.AckToggle" => " 我已知道 Skill 機制(下次開 Welcome 不再自動彈本頁)",
                "AgentSkill.AckVersionLabel" => "AcknowledgedVersion: {0}",
                "AgentSkill.NotSet" => "(未設)",
                "Welcome.AutoOpenToggle" => " 不再自動彈出此頁(仍可從選單 UCL → Welcome 手動開啟)",
                "Welcome.ResetButton" => "重設首次彈出(下次重啟 Editor 會再顯示一次)",
                "Welcome.ResetLog" => "[UCL_Welcome] 已重設首次彈出狀態。下次 domain reload 會再次顯示。",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(未設)",
                "Welcome.Search.Title" => "🔍 文件搜尋",
                "Welcome.Search.Button" => "搜尋",
                "Welcome.Search.Hint" => "支援同義詞展開（讀 Docs/_synonyms.txt）— 例：搜「物品」也能命中標題寫「道具」的文件。多詞以空格分隔（AND 模式）。",
                "Welcome.Search.NoResults" => "(無命中)",
                "Welcome.Search.ResultsCount" => "命中 {0} 篇（共掃 {1} 篇）",
                "Welcome.Search.OpenButton" => "📖 開啟檔案",
                "Welcome.Search.OpenPageButton" => "🔍 開啟文件搜尋頁",
                "DocSearch.Advanced" => "進階選項",
                "DocSearch.Mode" => "搜尋模式",
                "DocSearch.Limit" => "結果上限",
                "DocSearch.SynonymsPath" => "同義詞檔路徑",
                "DocSearch.IncludeArchived" => "包含 archived 文件",
                "DocSearch.Reveal" => "📂 定位",
                "DocSearch.Preview" => "📄 預覽",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "重新整理",
                "AgentCmd.RunPending" => "執行待辦指令",
                "AgentCmd.ClearFailed" => "清除失敗",
                "AgentCmd.OpenFolder" => "開啟資料夾",
                "AgentCmd.QueuePath" => "Queue：{0}",
                "AgentCmd.Stats" => "總計：{0} ｜ OneShot：{1} ｜ Repeatable：{2}",
                "AgentCmd.Commands" => "指令清單",
                "AgentCmd.QueueEmpty" => "（queue 是空的 — 從下方挑一個 Command 加入，或直接編輯 queue.json）",
                "AgentCmd.Remove" => "移除",
                "AgentCmd.AddCommand" => "新增指令",
                "AgentCmd.NoHandlers" => "（尚未註冊任何 Handler — 請寫一個 class 繼承 UCL_AgentCommandHandlerBase）",
                "AgentCmd.Command" => "指令：",
                "AgentCmd.Mode" => "模式：",
                "AgentCmd.Description" => "描述：",
                "AgentCmd.Args" => "參數：",
                "AgentCmd.ArgsFormat" => "（格式：k=v;k=v）",
                "AgentCmd.ArgsSchema" => "  Args Schema：{0}",
                "AgentCmd.Example" => "  範例：{0}",
                "AgentCmd.FillExample" => "填入範例",
                "AgentCmd.ViewHelp" => "查看說明",
                "AgentCmd.AddButton" => "加入「{0}」（{1}）",
                "AgentCmd.SaveTemplateName" => "存為模板 — 名稱：",
                "AgentCmd.SaveTemplate" => "儲存模板",
                "AgentCmd.TemplateNotes" => "模板備註：",
                "AgentCmd.Templates" => "模板",
                "AgentCmd.TemplatesCount" => " {0} 筆",
                "AgentCmd.Search" => "搜尋：",
                "AgentCmd.Clear" => "清空",
                "AgentCmd.NoTemplates" => "（沒有模板 — 在上方「新增指令」區塊填好欄位後按「儲存模板」）",
                "AgentCmd.ApplyToForm" => "套用到表單",
                "AgentCmd.AddToQueue" => "加入 Queue",
                "AgentCmd.Delete" => "刪除",
                "AgentCmd.History" => "歷史紀錄",
                "AgentCmd.HistoryCount" => " {0} 筆",
                "AgentCmd.NoHistory" => "（沒有符合的歷史 — 按下「新增指令」後會自動記錄到這裡）",
                "AgentCmd.Cleanup" => "清理 —",
                "AgentCmd.OlderThanDays" => "早於（天）：",
                "AgentCmd.DeleteOlder" => "刪除過舊",
                "AgentCmd.Dedupe" => "去除重複",
                "AgentCmd.ClearAll" => "全部清空",
                "AgentCmd.ClearAllConfirmTitle" => "全部清空歷史？",
                "AgentCmd.ClearAllConfirmBody" => "確定要刪除 {0} 筆歷史紀錄嗎？此動作不可逆。",
                "AgentCmd.ConfirmDelete" => "刪除",
                "AgentCmd.ConfirmCancel" => "取消",
                "AgentCmd.ReAdd" => "重新加入",
                "AgentCmd.ToTemplate" => "→ 模板",
                "AgentCmd.AutoWatcher" => "自動觸發器",
                "AgentCmd.LastTrigger" => "上次觸發：{0}",
                "AgentCmd.Never" => "（從未）",
                "AgentCmd.SimulateTrigger" => "模擬觸發",
                "AgentCmd.Tips" => "小提示",
                "AgentCmd.Tip_OneShot" => "- OneShot：成功執行後會直接從 queue 中移除",
                "AgentCmd.Tip_Repeatable" => "- Repeatable：每次 Run 都會再執行一次，並把 RunCount +1",
                "AgentCmd.Tip_WaitInit" => "- Run 之前自動 await UCL_ModuleService.WaitUntilInitialized — 確保模組系統已就緒",
                "AgentCmd.Tip_FailedKept" => "- 失敗的指令會把錯誤訊息寫進 LastRunError 並留在 queue（不會被移除）",
                "AgentCmd.Tip_Watcher" => "- Auto-Watcher 啟用時：外部寫入 AgentCommands/pending.trigger 即會自動觸發 Run Pending（無需手動點按鈕）",
                "AgentCmd.Tip_ExportCatalog" => "- 想匯出 Cmd 目錄？加一筆 'ExportCommandCatalog' Cmd 即可（不再有獨立按鈕）",

                _ => null
            };
        }
    }
}
