
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_zhHans(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "Edit Modules" => "编辑模组",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "播放集",
                "UCL_ModulePlayListPage" => "编辑播放集",
                "Create new module" => "创建新模组",
                "Module ID" => "模组ID",
                "EditModulewarning" => "对内建模组(Core)的编辑，会在更新后失效\n请建立新的模组，来新增或复盖原有内容\n不同模組中，若有相同ID的内容\n将会由后载入的模组的内容复盖",
                "EditType" => "编辑模式",
                "UCL_ModuleEditType_Builtin" => "内建模组",
                "UCL_ModuleEditType_Runtime" => "游戏模组",
                "UCL_ModuleEditType_Template" => "预设范本",
                "Save Config" => "保存设定",
                "Load Config" => "载入设定",
                "Open Module Folder" => "开启模组资料夹",
                "ModuleService Config" => "模组相关设定",
                "Loaded modules" => "目前载入的模组",
                "Config" => "设定",
                "Current playlist" => "目前的模组播放集",
                "Create new playlist" => "创建新模组播放集",
                "Load current playlist" => "载入目前播放集",
                "ModulePlayListTip" => "若要启用模组\n请按下「编辑播放集按钮」\n并将要启用的模组加入播放集中",
                "UCL_ModulePlayListPageTip" => "请选取想要编辑的播放集\n或是创建新模组播放集",
                "UCL_ModulePlayListPageSaveTip" => "编辑播放集后请按下「存档」\n若要套用当前播放集请按下「载入目前播放集」",
                "UCL_CreateNewModulePageTip" => "模组ID请避免使用「纯数字」(例如3387893998)\nSteam订阅的模组以数字为ID\n若ID与Steam订阅的模組相同，将会被复盖",
                "DeleteTargetDes" => "删除「{0}」",
                "UCL_LocalizeAsset" => "本地化设定",
                "UCL_ModResourceAsset" => "模组资源",
                "UCL_LanguageCodeAsset" => "编辑支持的语言码",
                "UCL_SteamWorkshopAsset" => "Steam工作坊",
                "Module Content" => "模组内容",
                "Asset Type" => "资产类型",
                "Open Folder" => "开启资料夹",
                "SteamAPILangCode" => "SteamAPI语言码",
                "EWorkshopFileType" => "工作坊档案类型",
                "Visibility" => "可见度",
                "Dependencies" => "相依性",
                "PublishedFileId" => "工作坊物品ID",
                "ChangeLog" => "变更日誌",
                "Create workshop item" => "生成工作坊物品",
                "Update item to workshop" => "同步物品到工作坊",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公开",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "社区",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "将模组加入当前的播放清单",
                "AddNewModulesToCurrentPlaylistContent" => "是否要将新订阅的模组{0}\n加入到目前的播放清单({1})?",
                "HideThisOption" => "隐藏此选项",
                "Asset Group" => "Asset分组",
                "Confirm" => "确认",
                "Cancel" => "取消",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "重新安装",
                "ReInstallAlert" => "重新安装将会删除所有模组，请问是否要进行重新安装？\n(若游戏无法正常执行或启动，可以尝试重新安装)",
                "Edit" => "编辑",
                "Preview" => "预览",
                "OpenFile" => "开启档案",
                "UCL_LocalizeEditPage" => "本地化语言设置",
                "UCL_LocalizeEditPage_Language" => "语言",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（尚未注册任何 UCL_LanguageCodeAsset）",
                "UCL_LocalizeEditPage_Current" => "当前：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "应用（持久化）",
                "UCL_LocalizeEditPage_Reset" => "重设",
                "UCL_LocalizeEditPage_ClearOverride" => "清除已持久化的覆写",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset 内存有覆写）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （目前使用默认值）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  默认值：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 应用会持久化到 UCL_ConfigAsset/{0}.json，下次启动自动载入。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ 程序控制（纯 session）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "下载",
                "Key" => "索引键",
                "MoveElement" => "改变顺序",
                "SelectAssetTemplateDes" => "请选取新建{0}的范本",
                "OpenModuleRootFolder" => "开启模组资料夹",
                "OpenModuleInstallFolder" => "开启安装资料夹",
                "CopyToClipboard" => "复制到剪贴板",
                "PasteFromClipboard" => "从剪贴板粘贴",
                "CopyDescriptionToClipboard" => "複製描述到剪贴簿",
                "Rename" => "重新命名",
                "EditGroup" => "编辑分组",
                "ShowDeleteButton" => "显示删除按钮",
                "CreateFolder" => "创建资料夹",
                "Delete" => "删除",
                "CreateNew" => "新增",
                "RefreshData" => "刷新资料",
                "Save" => "存档",
                "Copy" => "复制",
                "Paste" => "贴上",
                "Back" => "返回",
                "Close" => "关闭",
                "Select" => "选择",
                "Search" => "搜索",
                "Add" => "新增",
                "SetCount" => "设置数量",
                "SaveBeforeExit?" => "是否先存档后在离开?",
                "ExitWitoutSave" => "不存档 直接离开",
                "UCL_SelectAsset" => "选取资产",
                "UCL_CreateAsset" => "建立资产",
                "UCL_SaveSuccess" => "保存成功！",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / 总览",
                "Welcome.Title" => "👋  欢迎使用 UCL_Core",
                "Welcome.Subtitle" => "跨项目共用的 Unity 基础框架  ·  Welcome 内容版本 v{0}",
                "Welcome.IntroTitle" => "UCL_Core 是什么？",
                "Welcome.IntroBody" => "UCL_Core 是一套跨项目共用的 Unity 基础框架，提供「数据资产 (UCL_Asset) / 模块系统 / 本地化 / Editor Page / Agent Command 跨进程指令系统」等核心组件。\n想快速上手？从下方功能卡片挑一个你最常用的开始。",
                "Welcome.FeaturesTitle" => "核心功能 (点按钮直达)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset 系统",
                "Welcome.Asset.Desc" => "JSON 序列化的设计资产 (卡牌 / 道具 / 怪物等)，编辑器可视化编辑、跨平台读写、SerializeReference 多态支持。",
                "Welcome.Asset.Btn" => "打开 Modules 编辑器",
                "Welcome.Localize.Title" => "🌐  Localize 翻译字串编辑",
                "Welcome.Localize.Desc" => "编辑各语系翻译字串、CurLangKey、PlayerPrefs key。日常切换语言用上方语言栏即可，不必进这页。",
                "Welcome.Localize.Btn" => "打开 Localize 编辑器",
                "Welcome.Lang.Label" => "🌐 语言：",
                "Welcome.Lang.NoneAvailable" => "(尚未发现 UCL_LanguageCodeAsset — 请先建立语言 Asset)",
                "Welcome.Lang.OpenEditor" => "高级编辑…",
                "Welcome.Agent.Title" => "🤖  Agent Commands (agent ↔ Editor 跨进程)",
                "Welcome.Agent.Desc" => "AI agent 写 queue.json、Editor Watcher 自动执行 — 含 ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat 等内建 Cmd。",
                "Welcome.Agent.Btn" => "打开 Agent Commands 页",
                "Welcome.Editor.Title" => "🪟  Editor Pages 框架",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — 一致风格的 IMGUI 页面堆栈，支持搜索下拉、HelpURL 跳转、TopBar 客制。",
                "Welcome.Editor.Btn" => "PlayerPrefs 编辑范例",
                "Welcome.DocBtn" => "📖 文档",
                "Welcome.DocsTitle" => "📚 文档总入口",
                "Welcome.Docs.Index" => "UCL_Core 文档 index",
                "Welcome.Docs.Architecture" => "Agent Command 整体架构",
                "Welcome.Docs.CreateCmd" => "新增 Cmd SOP",
                "Welcome.Docs.Validate" => "验证 UCL_Asset 格式",
                "Welcome.Docs.CompileError" => "🔧 Compile Error 排查工作流",
                "Welcome.AutoOpenToggle" => " 不再自动弹出此页 (仍可从菜单 UCL → Welcome 手动开启)",
                "Welcome.ResetButton" => "重置首次弹出 (下次重启 Editor 会再显示一次)",
                "Welcome.ResetLog" => "[UCL_Welcome] 已重置首次弹出状态。下次 domain reload 会再次显示。",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(未设)",
                "Welcome.Search.Title" => "🔍 文档搜索",
                "Welcome.Search.Button" => "搜索",
                "Welcome.Search.Hint" => "支持同义词展开 (读 Docs/_synonyms.txt) — 例：搜「物品」也能命中标题写「道具」的文档。多词以空格分隔 (AND 模式)。",
                "Welcome.Search.NoResults" => "(无命中)",
                "Welcome.Search.ResultsCount" => "命中 {0} 篇 (共扫 {1} 篇)",
                "Welcome.Search.OpenButton" => "📖 打开文件",
                "Welcome.Search.OpenPageButton" => "🔍 打开文件搜索页",
                "DocSearch.Advanced" => "高级选项",
                "DocSearch.Mode" => "搜索模式",
                "DocSearch.Limit" => "结果上限",
                "DocSearch.SynonymsPath" => "同义词文件路径",
                "DocSearch.IncludeArchived" => "包含 archived 文档",
                "DocSearch.Reveal" => "📂 定位",
                "DocSearch.Preview" => "📄 预览",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "刷新",
                "AgentCmd.RunPending" => "执行待办指令",
                "AgentCmd.ClearFailed" => "清除失败",
                "AgentCmd.OpenFolder" => "打开文件夹",
                "AgentCmd.QueuePath" => "Queue: {0}",
                "AgentCmd.Stats" => "总计: {0} | OneShot: {1} | Repeatable: {2}",
                "AgentCmd.Commands" => "指令清单",
                "AgentCmd.QueueEmpty" => "(queue 是空的 — 从下方挑一个 Command 加入，或直接编辑 queue.json)",
                "AgentCmd.Remove" => "移除",
                "AgentCmd.AddCommand" => "新增指令",
                "AgentCmd.NoHandlers" => "(尚未注册任何 Handler — 请写一个 class 继承 UCL_AgentCommandHandlerBase)",
                "AgentCmd.Command" => "指令:",
                "AgentCmd.Mode" => "模式:",
                "AgentCmd.Description" => "描述:",
                "AgentCmd.Args" => "参数:",
                "AgentCmd.ArgsFormat" => "(格式: k=v;k=v)",
                "AgentCmd.ArgsSchema" => "  Args Schema: {0}",
                "AgentCmd.Example" => "  示例: {0}",
                "AgentCmd.FillExample" => "填入示例",
                "AgentCmd.ViewHelp" => "查看说明",
                "AgentCmd.AddButton" => "加入「{0}」({1})",
                "AgentCmd.SaveTemplateName" => "存为模板 — 名称:",
                "AgentCmd.SaveTemplate" => "保存模板",
                "AgentCmd.TemplateNotes" => "模板备注:",
                "AgentCmd.Templates" => "模板",
                "AgentCmd.TemplatesCount" => " {0} 条",
                "AgentCmd.Search" => "搜索:",
                "AgentCmd.Clear" => "清空",
                "AgentCmd.NoTemplates" => "(没有模板 — 在上方「新增指令」区块填好后按「保存模板」)",
                "AgentCmd.ApplyToForm" => "应用到表单",
                "AgentCmd.AddToQueue" => "加入 Queue",
                "AgentCmd.Delete" => "删除",
                "AgentCmd.History" => "历史记录",
                "AgentCmd.HistoryCount" => " {0} 条",
                "AgentCmd.NoHistory" => "(没有符合的历史 — 按下「新增指令」后会自动记录到这里)",
                "AgentCmd.Cleanup" => "清理 —",
                "AgentCmd.OlderThanDays" => "早于(天):",
                "AgentCmd.DeleteOlder" => "删除过旧",
                "AgentCmd.Dedupe" => "去除重复",
                "AgentCmd.ClearAll" => "全部清空",
                "AgentCmd.ClearAllConfirmTitle" => "全部清空历史？",
                "AgentCmd.ClearAllConfirmBody" => "确定要删除 {0} 条历史记录吗？此动作不可逆。",
                "AgentCmd.ConfirmDelete" => "删除",
                "AgentCmd.ConfirmCancel" => "取消",
                "AgentCmd.ReAdd" => "重新加入",
                "AgentCmd.ToTemplate" => "→ 模板",
                "AgentCmd.AutoWatcher" => "自动触发器",
                "AgentCmd.LastTrigger" => "上次触发: {0}",
                "AgentCmd.Never" => "(从未)",
                "AgentCmd.SimulateTrigger" => "模拟触发",
                "AgentCmd.Tips" => "小提示",
                "AgentCmd.Tip_OneShot" => "- OneShot: 成功执行后会直接从 queue 中移除",
                "AgentCmd.Tip_Repeatable" => "- Repeatable: 每次 Run 都会再执行一次，并把 RunCount +1",
                "AgentCmd.Tip_WaitInit" => "- Run 之前自动 await UCL_ModuleService.WaitUntilInitialized — 确保模组系统已就绪",
                "AgentCmd.Tip_FailedKept" => "- 失败的指令会把错误讯息写进 LastRunError 并留在 queue (不会被移除)",
                "AgentCmd.Tip_Watcher" => "- Auto-Watcher 启用时: 外部写入 AgentCommands/pending.trigger 即会自动触发 Run Pending (无需手动点按钮)",
                "AgentCmd.Tip_ExportCatalog" => "- 想导出 Cmd 目录？加一笔 'ExportCommandCatalog' Cmd 即可 (不再有独立按钮)",

                _ => null
            };
        }
    }
}
