
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_zhHant(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "ReadOnly" => "唯讀",
                "Module_ReadOnly_Banner" => "唯讀（內建參考）— 如需修改請按『複製成可編輯模組』",
                "Fork_To_Editable" => "複製成可編輯模組（Fork）",
                "Fork_NewID_Prompt" => "新模組 ID",
                "Edit Modules" => "編輯模組",
                "ToolBox.Title" => "工具集",
                "ToolBox.MenuButton" => "🧰 開啟工具集",
                "ToolBox.GitFlattenSync" => "Git 攤平同步",
                "ToolBox.GitFlattenSync.Desc" => "把含 submodule 的 repo 攤平成純檔案、同步到另一個 repo 的工作目錄（來源只讀、目標只寫檔案，兩邊 git 都不碰）。",
                "ToolBox.GitSubmoduleSync" => "Git Submodule 同步",
                "ToolBox.GitSubmoduleSync.Desc" => "批量對所有 submodule 切預設 branch / pull / push —— 一張狀態表看誰 detached、誰 ahead，防止 submodule update 後分支跑掉。",
                "ToolBox.AutoCommit" => "自動 Commit",
                "ToolBox.AutoCommit.Desc" => "把 AgentCommands 自動生成的檔（酒館訊息 / Treasury / runtime state）分群、按鈕觸發各自成 commit，訊息自動生成；ephemeral 檔永遠排除。",
                "ToolBox.DocSearch" => "文件搜尋",
                "ToolBox.DocSearch.Desc" => "跨專案 200+ 篇 markdown 的即時模糊搜尋（含同義詞展開、當前語系優先）。",
                "ToolBox.LocalizeEdit" => "多語系編輯",
                "ToolBox.LocalizeEdit.Desc" => "編輯 UCL_LocalizeAsset 的多語系字串表。",
                "ToolBox.ScreenStream" => "螢幕直播錄影",
                "ToolBox.ScreenStream.Desc" => "螢幕錄影 / STT / OCR daemon 的控制台（陪看直播、影音轉錄）。",
                "ToolBox.ProcessAdmin" => "Process 管理",
                "ToolBox.ProcessAdmin.Desc" => "檢視與處置 C# 開出去的外部 process（PID + 名稱 + 啟動時間三重身分驗證，防誤殺、防屍潮）。",
                "ToolBox.BugReportAdmin" => "問題回報管理",
                "ToolBox.BugReportAdmin.Desc" => "結構化問題工單 —— 收的不只是 bug：文件過時、提示缺一半、流程可簡化都在這裡。超過 14 天沒動作的單會自動標記。",
                "ToolBox.Relationship" => "關係（Relationship）",
                "ToolBox.Relationship.Desc" => "每位 persona 的好感度以事件帳本保存 —— 分數由事件重算而來，不是存出來的。舊 affinity 的一次性遷移也在這裡。",
                "ToolBox.SessionAdmin" => "🗂 Session 管理",
                "ToolBox.SessionAdmin.Desc" => "各 persona 的 session 現況（自由時間…）。標出超時未收工、active 仍為 true 的殘留。",
                "ToolBox.FreeTimeAdmin" => "🎲 自由時間管理",
                "ToolBox.FreeTimeAdmin.Desc" => "骰面上的活動設定（啟用／分組／建議時間／特殊邏輯／執行提示）—— 就地改寫活動 md 的 frontmatter，不另存 override。",
                "ToolBox.LibraryManage" => "圖書館管理",
                "ToolBox.LibraryManage.Desc" => "管理既有 Books 與圖書館資料。",
                "ToolBox.ReadingNotesManage" => "閱讀心得管理",
                "ToolBox.ReadingNotesManage.Desc" => "依作品名稱定位 Archive 與新 Library 的手動入口。",
                "ToolBox.SculptureViewer" => "3D 雕刻觀測",
                "ToolBox.SculptureViewer.Desc" => "渲染共用 3D 體素空間看大家的作品 — 一鍵展品 preset 或手動設定觀測參數。",
                "SculptureViewer.Title" => "3D 雕刻觀測",
                "SculptureViewer.Exhibits" => "🏛 展品導覽（讀 exhibits.json）",
                "SculptureViewer.RenderExhibit" => "渲染展品",
                "SculptureViewer.Reload" => "重新整理",
                "SculptureViewer.RenderAll" => "渲染整體全景",
                "SculptureViewer.NoExhibit" => "（尚無登錄展品 — sculpt.py exhibit register）",
                "SculptureViewer.Manual" => "🔧 手動觀測參數",
                "SculptureViewer.RenderManual" => "以參數渲染",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "播放集",
                "UCL_ModulePlayListPage" => "編輯播放集",
                "Create new module" => "創建新模組",
                "Module ID" => "模組ID",
                "EditModulewarning" => "內建模組（如 Core）在免安裝模式下為唯讀，僅供參考瀏覽、無法直接編輯。\n如需修改：開啟該模組後按「複製成可編輯模組（Fork）」，會複製出一份可編輯模組。\n不同模組中若有相同 ID 的內容，將由後載入的模組覆蓋。",
                "EditType" => "編輯模式",
                "UCL_ModuleEditType_Builtin" => "內建模組",
                "UCL_ModuleEditType_Runtime" => "遊戲模組",
                "UCL_ModuleEditType_Template" => "預設範本",
                "Save Config" => "保存設定",
                "Load Config" => "載入設定",
                "Open Module Folder" => "開啟模組資料夾",
                "ModuleService Config" => "模組相關設定",
                "Loaded modules" => "目前載入的模組",
                "Config" => "設定",
                "Current playlist" => "目前的模組播放集",
                "Create new playlist" => "創建新模組播放集",
                "Load current playlist" => "載入目前播放集",
                "ModulePlayListTip" => "若要啟用模組\n請按下「編輯播放集按鈕」\n並將要啟用的模組加入播放集中",
                "UCL_ModulePlayListPageTip" => "請選取想要編輯的播放集\n或是創建新模組播放集",
                "UCL_ModulePlayListPageSaveTip" => "編輯播放集後請按下「存檔」\n若要套用當前播放集請按下「載入目前播放集」",
                "UCL_CreateNewModulePageTip" => "模組ID請避免使用「純數字」(例如3387893998)\nSteam訂閱的模組以數字為ID\n若ID與Steam訂閱的模組相同，將會被覆蓋",
                "DeleteTargetDes" => "刪除「{0}」",
                "UCL_LocalizeAsset" => "本地化設定",
                "UCL_ModResourceAsset" => "模組資源",
                "UCL_LanguageCodeAsset" => "支援的語言碼",
                "UCL_SteamWorkshopAsset" => "Steam工作坊",
                "Module Content" => "模組內容",
                "Asset Type" => "資產類型",
                "Open Folder" => "開啟資料夾",
                "SteamAPILangCode" => "SteamAPI語言碼",
                "EWorkshopFileType" => "工作坊檔案類型",
                "Visibility" => "可見度",
                "Dependencies" => "相依性",
                "PublishedFileId" => "工作坊物品ID",
                "ChangeLog" => "變更日誌",
                "Create workshop item" => "生成工作坊物品",
                "Update item to workshop" => "同步物品到工作坊",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公開",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "社區",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "將模組加入當前的播放清單",
                "AddNewModulesToCurrentPlaylistContent" => "是否要將新訂閱的模組{0}\n加入到目前的播放清單({1})?",
                "HideThisOption" => "隱藏此選項",
                "Asset Group" => "Asset分組",
                "Confirm" => "確認",
                "Cancel" => "取消",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "重新安裝",
                "ReInstallAlert" => "重新安裝將會刪除所有模組，請問是否要進行重新安裝？\n(若遊戲無法正常執行或啟動，可以嘗試重新安裝)",
                "Edit" => "編輯",
                "Preview" => "預覽",
                "OpenFile" => "開啟檔案",
                "UCL_LocalizeEditPage" => "本地化語言設定",
                "UCL_LocalizeEditPage_Language" => "語言",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（尚未註冊任何 UCL_LanguageCodeAsset）",
                "UCL_LocalizeEditPage_Current" => "當前：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "套用（持久化）",
                "UCL_LocalizeEditPage_Reset" => "重設",
                "UCL_LocalizeEditPage_ClearOverride" => "清除已持久化的覆寫",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset 內存有覆寫）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （目前使用預設值）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  預設值：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 套用會持久化到 UCL_ConfigAsset/{0}.json，下次啟動自動載入。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ 程式控制（純 session）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "下載",
                "Key" => "索引鍵",
                "MoveElement" => "改變順序",
                "SelectAssetTemplateDes" => "請選取新建{0}的範本",
                "OpenModuleRootFolder" => "開啟模組資料夾",
                "OpenModuleInstallFolder" => "開啟安裝資料夾",
                "CopyToClipboard" => "複製到剪貼簿",
                "PasteFromClipboard" => "從剪貼簿貼上",
                "CopyDescriptionToClipboard" => "複製描述到剪貼簿",
                "Rename" => "重新命名",
                "EditGroup" => "編輯分組",
                "ShowDeleteButton" => "顯示刪除按鈕",
                "CreateFolder" => "創建資料夾",
                "Delete" => "刪除",
                "CreateNew" => "新增",
                "RefreshData" => "刷新資料",
                "Save" => "存檔",
                "Copy" => "複製",
                "Paste" => "貼上",
                "Back" => "返回",
                "Close" => "關閉",
                "Select" => "選擇",
                "Search" => "搜尋",
                "Add" => "新增",
                "SetCount" => "設定數量",
                "SaveBeforeExit?" => "是否先存檔後在離開?",
                "ExitWitoutSave" => "不存檔 直接離開",
                "UCL_SelectAsset" => "選取資產",
                "UCL_CreateAsset" => "建立資產",
                "UCL_SaveSuccess" => "儲存成功！",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / 總覽",
                "Welcome.Title" => "👋  歡迎使用 UCL_Core",
                "Welcome.Subtitle" => "跨專案共用的 Unity 基礎框架  ·  Welcome 內容版本 v{0}",
                "Welcome.IntroTitle" => "UCL_Core 是什麼？",
                "Welcome.IntroBody" => "UCL_Core 是一套跨專案共用的 Unity 基礎框架，提供「資料資產(UCL_Asset)/ 模組系統 / 本地化 / Editor Page / Agent Command 跨 process 指令系統」等核心元件。\n想快速上手？從下方功能卡片挑一個你最常用的開始。",
                "Welcome.FeaturesTitle" => "核心功能(點按鈕直達)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset 系統",
                "Welcome.Asset.Desc" => "JSON 序列化的設計資產(卡牌 / 道具 / 怪物等)，編輯器可視化編輯、跨平台讀寫、SerializeReference 多型支援。",
                "Welcome.Asset.Btn" => "打開 Modules 編輯器",
                "Welcome.Localize.Title" => "🌐  Localize 翻譯字串編輯",
                "Welcome.Localize.Desc" => "編輯各語系翻譯字串、CurLangKey、PlayerPrefs key。日常切換語言用上方語言列即可，不必進這頁。",
                "Welcome.Localize.Btn" => "打開 Localize 編輯器",
                "Welcome.Lang.Label" => "🌐 語言：",

                "Welcome.CommandTable.Label" => "📋 指令對照：",
                "Welcome.CommandTable.Desc" => "整理了 AI Agent 所有的口語指令、觸發詞與對應的 Workflow 參考手冊。",
                "Welcome.CommandTable.Btn" => "📄 預覽指令表",

                "Welcome.Lang.NoneAvailable" => "(尚未發現 UCL_LanguageCodeAsset — 請先建立語言 Asset)",
                "Welcome.Lang.OpenEditor" => "進階編輯…",
                "Welcome.Agent.Title" => "🤖  Agent Commands(agent ↔ Editor 跨 process)",
                "Welcome.Agent.Desc" => "AI agent 寫 queue.json、Editor Watcher 自動執行 — 含 ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat 等內建 Cmd。",
                "Welcome.Agent.Btn" => "打開 Agent Commands 頁",
                "Welcome.Editor.Title" => "🪟  Editor Pages 框架",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — 一致風格的 IMGUI 頁面堆疊，支援搜尋下拉、HelpURL 跳轉、TopBar 客製。",
                "Welcome.Editor.Btn" => "PlayerPrefs 編輯範例",
                "Welcome.DocBtn" => "📖 文件",

                "Welcome.DocsTitle" => "📚 文件總入口",
                "Welcome.Docs.Index" => "UCL_Core 文件 index",
                "Welcome.Docs.Architecture" => "Agent Command 整體架構",
                "Welcome.Docs.CreateCmd" => "新增 Cmd SOP",
                "Welcome.Docs.Validate" => "驗證 UCL_Asset 格式",
                "Welcome.Docs.CompileError" => "🔧 Compile Error 排查工作流",
                // Welcome 頁的 Skill 入口卡片（小，導向獨立的 AgentSkillManager 頁）
                "Welcome.SkillEntry.Title" => "🧩  Agent Skill 管理",
                "Welcome.SkillEntry.Desc" => "把 UCL_Core 的 commit / 進酒館 / 排查編譯錯等工作流抽成 AI agent Skill — 不同 agent (Claude Code / Cursor / Antigravity / Gemini) 各自的安裝路徑由管理頁統一處理。第一次開 Welcome 會自動彈出。",
                "Welcome.SkillEntry.OpenBtn" => "🛠 打開 Skill 管理頁",

                // 獨立的 UCL_AgentSkillManagerPage
                "AgentSkill.Title" => "🛠 Agent Skill Manager",
                "AgentSkill.Subtitle" => "把 UCL_Core 的工作流安裝給各家 AI agent 用",
                "AgentSkill.ConceptTitle" => "為什麼有這頁？",
                "AgentSkill.ConceptBody" => "UCL_Core/Skills~/ 內每個 skill 是一份「lazy-load 工作流」— agent 看到觸發詞才載入完整 SOP，平時不吃 context。每個 agent 家有自家路徑慣例：Claude Code → .claude/skills/、Antigravity → .agents/rules/（規劃中：Cursor → .cursor/rules/、Gemini）。本頁負責對所有支援的 target 統一安裝。",
                "AgentSkill.OneClick.Title" => "一鍵安裝（支援 Claude Code / Antigravity）",
                "AgentSkill.OneClick.Desc" => "跑 Tools~/install_skills.py --target <X> 把所有 skill 拷到對應 dst（Claude → .claude/skills/、Antigravity → .agents/rules/）。冪等可重複跑；偵測本地修改不會覆寫。",
                "AgentSkill.Status.NotInstalled" => "⚠ 尚未安裝 — 點下方按鈕一鍵裝起來",
                "AgentSkill.Status.Synced" => "✓ 已安裝且與來源內文一致",
                "AgentSkill.Status.Stale" => "⚠ 已安裝內文與來源不一致（來源已更新或本地被改動）— 建議重裝／強制同步",
                "AgentSkill.Status.LegacyNoHash" => "⚠ 舊版 marker 無 source_hash 欄位 — 重裝一次即可刷新比對基準",
                "AgentSkill.Status.UnknownHead" => "已安裝但無法判定 UCL_Core HEAD（git 不在 PATH？）",
                "AgentSkill.Status.NoProjectRoot" => "找不到 host project root（沒有 .claude/ 或 .git/）— 請手動執行 Tools~/install_skills.py --project-root <path>",
                "AgentSkill.Status.NoUCLCore" => "找不到 UCL_Core 路徑（UCL_EditorPath.CorePath 為空）",
                "AgentSkill.HostRoot" => "Project root: {0}",
                "AgentSkill.Btn.Install" => "🚀 安裝",
                "AgentSkill.Btn.InstallAll" => "🚀 一鍵安裝全部 target",
                "AgentSkill.Btn.ForceSyncAll" => "⚡ 強制同步全部 (覆蓋本地改動)",
                "AgentSkill.Btn.ForceSyncAll.Synced" => "✅ 已全部同步 (仍可按下強制重寫)",
                "AgentSkill.SkippedWarn" => "⚠ 上次安裝有 {0} 檔因本地改動被跳過，內容未更新 — 用「重裝」或「強制同步」覆蓋 (詳見 Console)",
                "AgentSkill.Btn.Sync" => "🔄 同步到當前版本",
                "AgentSkill.Btn.Reinstall" => "🔁 重新安裝",
                "AgentSkill.Btn.Refresh" => "重新整理",
                "AgentSkill.Btn.Doc" => "📖 Skills~/README",
                "AgentSkill.Btn.ResetAck" => "重設首次彈出",
                "AgentSkill.Matrix.Title" => "🎛 Per-Agent × Per-Skill 切換",
                "AgentSkill.Matrix.Body" => "用下拉選單選擇 agent，檢視/管理該 agent 的逐 skill 安裝狀態。installed/drift 為各 agent 獨立；disabled（UCL_SkillConfigAsset）跨 agent 共用：",
                "AgentSkill.Matrix.NoSource" => "(找不到 UCL_Core/Skills~/ 來源目錄)",
                "AgentSkill.Matrix.Status.DisabledPendingRemove" => "🚫停用·待移除",
                "AgentSkill.Matrix.Status.Disabled" => "🚫停用",
                "AgentSkill.Matrix.Status.NotInstalled" => "未裝",
                "AgentSkill.Matrix.Status.Drift" => "⚠改動",
                "AgentSkill.Matrix.Status.Synced" => "✓同步",
                "AgentSkill.Matrix.Btn.Enable" => "啟用",
                "AgentSkill.AckToggle" => " 永不自動彈出本頁(即使 skill 有更新；仍可從選單手動開啟)",
                "AgentSkill.LastChangesLabel" => "上次自動彈出原因 — skill 變動: {0}",
                "AgentSkill.AckVersionLabel" => "AcknowledgedVersion: {0}",
                "AgentSkill.NotSet" => "(未設)",


                "Welcome.AutoOpenToggle" => " 不再自動彈出此頁(仍可從選單 UCL → Welcome 手動開啟)",
                "Welcome.ResetButton" => "重設首次彈出(下次重啟 Editor 會再顯示一次)",
                "Welcome.ResetLog" => "[UCL_Welcome] 已重設首次彈出狀態。下次 domain reload 會再次顯示。",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(未設)",
                "Welcome.Search.Title" => "🔍 文件搜尋",
                "Welcome.Search.Button" => "搜尋",
                "Welcome.Search.Hint" => "支援同義詞展開（讀 Docs/_synonyms.txt）— 例：搜「物品」也能命中標題寫「道具」的文件。多詞以空格分隔（AND 模式）。",
                "Welcome.Search.NoResults" => "(無命中)",
                "Welcome.Search.ResultsCount" => "命中 {0} 篇（共掃 {1} 篇）",
                "Welcome.Search.OpenButton" => "📖 開啟檔案",
                "Welcome.Search.OpenPageButton" => "🔍 開啟文件搜尋頁",
                "DocSearch.Advanced" => "進階選項",
                "DocSearch.Mode" => "搜尋模式",
                "DocSearch.Limit" => "結果上限",
                "DocSearch.SynonymsPath" => "同義詞檔路徑",
                "DocSearch.IncludeArchived" => "包含 archived 文件",
                "DocSearch.Reveal" => "📂 定位",
                "DocSearch.Preview" => "📄 預覽",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "重新整理",
                "AgentCmd.RunPending" => "執行待辦指令",
                "AgentCmd.ClearFailed" => "清除失敗",
                "AgentCmd.OpenFolder" => "開啟資料夾",
                "AgentCmd.QueuePath" => "Queue：{0}",
                "AgentCmd.QueueSelector" => "Queue 切換",
                "AgentCmd.QueueDefault" => "共用 default ({0})",
                "AgentCmd.PageInfo" => "第 {0}/{1} 頁（共 {2} 筆）",
                "AgentCmd.CmdInfoToggle" => "指令說明",
                "AgentCmd.Stats" => "總計：{0} ｜ OneShot：{1} ｜ Repeatable：{2}",
                "AgentCmd.Commands" => "指令清單",
                "AgentCmd.QueueEmpty" => "（queue 是空的 — 從下方挑一個 Command 加入，或直接編輯 queue.json）",
                "AgentCmd.Remove" => "移除",
                "AgentCmd.AddCommand" => "新增指令",
                "AgentCmd.NoHandlers" => "（尚未註冊任何 Handler — 請寫一個 class 繼承 UCL_AgentCommandHandlerBase）",
                "AgentCmd.Command" => "指令：",
                "AgentCmd.Mode" => "模式：",
                "AgentCmd.Description" => "描述：",
                "AgentCmd.Args" => "參數：",
                "AgentCmd.ArgsFormat" => "（格式：k=v;k=v）",
                "AgentCmd.ArgsSchema" => "  Args Schema：{0}",
                "AgentCmd.Example" => "  範例：{0}",
                "AgentCmd.FillExample" => "填入範例",
                "AgentCmd.ViewHelp" => "查看說明",
                "AgentCmd.AddButton" => "加入「{0}」（{1}）",
                "AgentCmd.SaveTemplateName" => "存為模板 — 名稱：",
                "AgentCmd.SaveTemplate" => "儲存模板",
                "AgentCmd.TemplateNotes" => "模板備註：",
                "AgentCmd.Templates" => "模板",
                "AgentCmd.TemplatesCount" => " {0} 筆",
                "AgentCmd.Search" => "搜尋：",
                "AgentCmd.Clear" => "清空",
                "AgentCmd.NoTemplates" => "（沒有模板 — 在上方「新增指令」區塊填好欄位後按「儲存模板」）",
                "AgentCmd.ApplyToForm" => "套用到表單",
                "AgentCmd.AddToQueue" => "加入 Queue",
                "AgentCmd.Delete" => "刪除",
                "AgentCmd.History" => "歷史紀錄",
                "AgentCmd.QueueUnrecorded" => "(未記錄)",
                "AgentCmd.QueueFilter" => "Queue 篩選",
                "AgentCmd.QueueFilterAll" => "(全部)",
                "AgentCmd.HistoryCount" => " {0} 筆",
                "AgentCmd.NoHistory" => "（沒有符合的歷史 — 按下「新增指令」後會自動記錄到這裡）",
                "AgentCmd.Cleanup" => "清理 —",
                "AgentCmd.OlderThanDays" => "早於（天）：",
                "AgentCmd.DeleteOlder" => "刪除過舊",
                "AgentCmd.Dedupe" => "去除重複",
                "AgentCmd.ClearAll" => "全部清空",
                "AgentCmd.ClearAllConfirmTitle" => "全部清空歷史？",
                "AgentCmd.ClearAllConfirmBody" => "確定要刪除 {0} 筆歷史紀錄嗎？此動作不可逆。",
                "AgentCmd.ConfirmDelete" => "刪除",
                "AgentCmd.ConfirmCancel" => "取消",
                "AgentCmd.ReAdd" => "重新加入",
                "AgentCmd.ToTemplate" => "→ 模板",
                "AgentCmd.AutoWatcher" => "自動觸發器",
                "AgentCmd.LastTrigger" => "上次觸發：{0}",
                "AgentCmd.Never" => "（從未）",
                "AgentCmd.SimulateTrigger" => "模擬觸發",
                "AgentCmd.Tips" => "小提示",
                "AgentCmd.Tip_OneShot" => "- OneShot：成功執行後會直接從 queue 中移除",
                "AgentCmd.Tip_Repeatable" => "- Repeatable：每次 Run 都會再執行一次，並把 RunCount +1",
                "AgentCmd.Tip_WaitInit" => "- Run 之前自動 await UCL_ModuleService.WaitUntilInitialized — 確保模組系統已就緒",
                "AgentCmd.Tip_FailedKept" => "- 失敗的指令會把錯誤訊息寫進 LastRunError 並留在 queue（不會被移除）",
                "AgentCmd.Tip_Watcher" => "- Auto-Watcher 啟用時：外部寫入 AgentCommands/pending.trigger 即會自動觸發 Run Pending（無需手動點按鈕）",
                "AgentCmd.Tip_ExportCatalog" => "- 想匯出 Cmd 目錄？加一筆 'ExportCommandCatalog' Cmd 即可（不再有獨立按鈕）",

                // ==== UCL_LoginStatusPage ====
                "LoginStatus.Title" => "登入狀態",
                "LoginStatus.Btn.Refresh" => "🔄 重新整理",
                "LoginStatus.Btn.Logout" => "🌙 登出",
                "LoginStatus.Btn.Renew" => "🔄 續期",
                "LoginStatus.Btn.ForceRm" => "✂ 強制移除",
                "LoginStatus.Btn.Morning" => "🌅 Morning（登入）",
                "LoginStatus.Btn.ConfirmRemove" => "確定 ✂",
                "LoginStatus.Collision.Title" => "<color=#ff9966><b>⚠ Session-key COLLISION 偵測</b></color>",
                "LoginStatus.Collision.Desc" => "cwd-hash session_key 在多 Claude IDE 同 cwd 下會撞。下列 session_key 對到 ≥ 2 lock：",
                "LoginStatus.Collision.Hint" => "→ 用 pid 跟 locked_at 區分自己 process。Morning ritual 該帶 --strict-persona。",
                "LoginStatus.Locks.HeaderFmt" => "<b>當前活躍 Persona Lock（{0}）</b>",
                "LoginStatus.Locks.Empty" => "(無 active lock — 所有 persona offline)",
                "LoginStatus.ExpiredFmt" => "<color=#aa6666>{0}（已過期）</color>",
                "LoginStatus.Col.Persona" => "Persona",
                "LoginStatus.Col.Agent" => "Agent",
                "LoginStatus.Col.Bank" => "帳戶",
                "LoginStatus.Col.Pid" => "pid",
                "LoginStatus.Col.LockedAt" => "鎖定時間（UTC）",
                "LoginStatus.Col.ExpiresAt" => "到期時間（UTC）",
                "LoginStatus.Col.SessionKey" => "session_key",
                "LoginStatus.Col.Token" => "Session Token",
                "LoginStatus.Token.None" => "<color=#888888>(無 token)</color>",
                "LoginStatus.Col.Status" => "狀態",
                "LoginStatus.Col.Wake" => "Wake#",
                "LoginStatus.Col.LayerRole" => "Layer 角色",
                "LoginStatus.Col.LastActive" => "最後活躍（UTC）",
                "LoginStatus.ManualLogin.Title" => "<b>手動 Morning（登入）</b>",
                "LoginStatus.Field.Agent" => "Agent:",
                "LoginStatus.Field.Persona" => "Persona:",
                "LoginStatus.Field.Model" => "Model:",
                "LoginStatus.Field.ForkName" => "Fork 名稱:",
                "LoginStatus.Login.RejectHint" => "（agent / persona 任一為空都會被拒絕）",
                "LoginStatus.Pool.HeaderFmt" => "<b>Persona 池（{0}）</b>",
                "LoginStatus.Pool.EmptyFmt" => "(無 registry — `{0}` 不存在或空)",
                "LoginStatus.Dialog.ForceRm.Title" => "強制移除 Lock",
                "LoginStatus.Dialog.ForceRm.BodyFmt" => "確定強制刪除 lock?\n\n{0}\n\n注意: persona registry status 不會自動改成 offline, 需後續手動修正。建議優先用 Logout（走 goodnight ritual）。",
                // T07.4 (2026-05-16 trailhead) — Logout 三按鈕 popup（防誤按）
                "LoginStatus.Dialog.Logout.TitleFmt" => "確認登出 — {0}",
                "LoginStatus.Dialog.Logout.BodyFmt" =>
                    "即將對下列 persona 執行完整 Goodnight ritual\n（寫 letter / vector 擾動 / status→offline / 刪 lock）：\n\n" +
                    "  Persona       : {0}\n" +
                    "  Agent         : {1}\n" +
                    "  Bank          : {2}\n" +
                    "  Locked at     : {3}\n" +
                    "  Session token : {4}\n" +
                    "  Token enforce : {5}\n\n" +
                    "請選擇登出方式：\n" +
                    "• 「取消」              — 不執行任何動作\n" +
                    "• 「不帶 Token 登出」    — 強制不附 token（enforce ON 時下線廣播會被 reject，但本地 lock 仍會清；適合 token 過期/損毀的逃生路徑）\n" +
                    "• 「自動帶正確 Token 登出（推薦）」 — 從 lock 自動撈出對應 token 附上，enforce ON 也能正常廣播。",
                "LoginStatus.Btn.LogoutNoToken" => "🚪 不帶 Token 登出",
                "LoginStatus.Btn.LogoutWithToken" => "🌙 自動帶 Token 登出（推薦）",
                // T07 (2026-05-15 apex-two) — Token Enforce 後台開關
                "LoginStatus.TokenEnforce.Title" => "<b>🎫 Session Token Enforce（後台開關）</b>",
                "LoginStatus.TokenEnforce.On" => "🔒 ENFORCE ON（必驗 token）",
                "LoginStatus.TokenEnforce.Off" => "🔓 ENFORCE OFF（預設，不驗）",
                "LoginStatus.TokenEnforce.SummaryFmt" => "Active tokens: {0} ｜ Expired: {1}",
                "LoginStatus.TokenEnforce.Hint" => "ON 時 Cmd_Tavern op=post 必帶 --arg session_token=<X>，token <-> sender/persona 對齊才寫入。預設 OFF（不破壞既有 caller）。",

                // ==== UCL_LibraryManagePage ====
                "LibraryManage.Title" => "圖書館管理",
                "LibraryManage.Btn.Refresh" => "🔄 重新整理",
                "LibraryManage.Btn.OpenReadingNotes" => "📖 閱讀心得管理",
                "LibraryManage.Btn.OpenReadingNotesForBook" => "📖 開啟閱讀心得",
                "LibraryManage.Btn.OpenBookNotes" => "📂 開啟 BookNotes",
                "LibraryManage.BookNotes.HeaderFmt" => "📒 書籍索引 Library（{0} 部）",
                "LibraryManage.BookNotes.EmptyFmt" => "（Library 沒有任何 media — 目錄: {0}）",
                "LibraryManage.BookNotes.SelectLabel" => "選擇作品",
                "LibraryManage.Detail.AuthorFmt" => "作者: {0}",
                "LibraryManage.Detail.ReadersFmt" => "讀者 {0} 位：{1}",
                "LibraryManage.Detail.DonatedFmt" => "📖 捐贈者: {0}（{1} token, {2}）",
                "LibraryManage.Btn.OpenFolder" => "📂 資料夾",
                "LibraryManage.Btn.NotesFolder" => "📂 筆記資料夾",
                "LibraryManage.Btn.FullTextFolder" => "📚 全文資料夾",
                "LibraryManage.Btn.OpenJson" => "📄 book.json",
                "LibraryManage.Donations.HeaderFmt" => "📖 捐贈者（{0} 筆）",
                "LibraryManage.Donations.Empty" => "（尚無捐贈紀錄）",
                "LibraryManage.Col.Donor" => "捐贈者",
                "LibraryManage.Col.Tokens" => "Token / 定價",
                "LibraryManage.Col.Date" => "日期",
                "LibraryManage.Donate.Title" => "💝 捐贈圖書 (donate — 會扣 token)",
                "LibraryManage.Field.Book" => "書 slug",
                "LibraryManage.Field.Donor" => "捐贈者 bank",
                "LibraryManage.Field.DonorPersona" => "捐贈 persona",
                "LibraryManage.Field.DonorTokens" => "token",
                "LibraryManage.Btn.Donate" => "💝 捐贈",
                "LibraryManage.Donate.Hint" => "捐贈走 Cmd_Treasury debit 扣 token（預設 100/本），書須已存在於 Books/ 且未被捐過。按下會先確認。",
                "LibraryManage.Dialog.Donate.Title" => "確認捐贈圖書？",
                "LibraryManage.Dialog.Donate.BodyFmt" => "將從帳戶捐贈以下書籍進共享圖書館：\n\n書: {0}\n捐贈者: {1}\n花費: {2} token\n\n此操作會走 Treasury debit 扣款並寫入捐贈索引，確定？",
                "LibraryManage.Recommend.HeaderFmt" => "💡 推薦書單（{0} 本，點開/收合）",
                "LibraryManage.Recommend.Empty" => "（推薦書單為空）",
                // 全文書庫 Books/ 區塊
                "LibraryManage.Books.HeaderFmt" => "📚 全文書庫 Books（{0} 本）",
                "LibraryManage.Books.EmptyFmt" => "（沒有全文 — Books 目錄: {0}）",
                "LibraryManage.Books.SelectLabel" => "選擇書籍",
                "LibraryManage.Books.ChapterFmt" => "章節數: {0} 個 .txt",
                "LibraryManage.Books.NotDonated" => "📖 尚未被捐贈",
                "LibraryManage.Books.HasNotes" => "📒 有對應讀書筆記（BookNotes）",
                "LibraryManage.Books.NoNotes" => "📒 無對應讀書筆記",
                "LibraryManage.Btn.EditBook" => "✏ 編輯書籍",
                // ==== UCL_BookEditPage ====
                "BookEdit.TitleFmt" => "編輯書籍: {0}",
                "BookEdit.Btn.Back" => "← 返回",
                "BookEdit.Btn.Reload" => "🔄 重載",
                "BookEdit.MissingFmt" => "書籍目錄不存在: {0}",
                "BookEdit.ChaptersFmt" => "章節數: {0}",
                "BookEdit.NewChapterLabel" => "新章節號(留空=自動)",
                "BookEdit.Btn.AddChapter" => "➕ 新增章節",
                "BookEdit.NoChapters" => "（尚無章節 .txt）",
                "BookEdit.SelectChapter" => "選擇章節",
                "BookEdit.Btn.OpenTxt" => "📄 外部開啟",
                "BookEdit.EditingFmt" => "編輯中: {0}{1}",
                "BookEdit.CharCountFmt" => "{0} 字",
                "BookEdit.Btn.Save" => "💾 存檔",
                "BookEdit.Btn.Revert" => "↩ 還原",

                // ==== UCL_AssetReferencePage ====
                "AssetRef.Btn.Entry" => "🔗 引用查詢",
                "AssetRef.TitleFmt" => "引用查詢: {0}/{1}",
                "AssetRef.Btn.Back" => "← 返回",
                "AssetRef.Btn.Rescan" => "🔄 重新掃描",
                "AssetRef.Btn.Open" => "📂 開啟",
                "AssetRef.NoTarget" => "（未指定查詢目標）",
                "AssetRef.NotScanned" => "尚未掃描…",
                "AssetRef.TargetFmt" => "目標: {0} / {1}",
                "AssetRef.ReverseHeaderFmt" => "被引用（誰引用我）: {0} 筆",
                "AssetRef.ForwardHeaderFmt" => "引用到（我引用誰）: {0} 筆",
                "AssetRef.Empty" => "（無）",

                // ==== UCL_PersonaInspectorPage ====
                "PersonaInspector.Title" => "Persona 信件檢視器",
                "PersonaInspector.Btn.Refresh" => "🔄 重新整理",
                "PersonaInspector.Btn.OpenLettersDir" => "📂 開啟信件根目錄",
                "PersonaInspector.Btn.OpenPersonaJson" => "📄 開啟 persona JSON",
                "PersonaInspector.Btn.OpenCanonicalFolder" => "📂 標準位置資料夾",
                "PersonaInspector.Btn.View" => "👁",
                "PersonaInspector.Btn.Open" => "📂",
                "PersonaInspector.Btn.CopyPath" => "📋 複製路徑",
                "PersonaInspector.Btn.RevealFile" => "📂 在檔案總管顯示",
                "PersonaInspector.Btn.CloseBody" => "✕ 收合",
                "PersonaInspector.List.HeaderFmt" => "<b>Persona 池（{0}）</b>",
                "PersonaInspector.Filter" => "篩選:",
                "PersonaInspector.Hint.SelectPersona" => "← 從左邊選一個 persona 開始檢視",
                "PersonaInspector.Field.Model" => "Model",
                "PersonaInspector.Field.LayerRole" => "Layer 角色",
                "PersonaInspector.Field.CanonicalActor" => "標準 actor 帳戶",
                "PersonaInspector.Field.CreatedAt" => "建立時間",
                "PersonaInspector.Field.LastActive" => "最後活躍",
                "PersonaInspector.Field.ForkedFrom" => "Forked From",
                "PersonaInspector.Field.ForkLineage" => "Fork 血脈",
                "PersonaInspector.Field.VectorHistory" => "Vector 歷史",
                "PersonaInspector.Field.LastSessionKeys" => "最近 session keys",
                "PersonaInspector.Letters.HeaderFmt" => "<b>📨 信件（{0} 封, 跨全部 actor 資料夾掃描）</b>",
                "PersonaInspector.Letters.MisroutedFmt" => "<color=#ff9966>⚠ {0} 封 misrouted</color>",
                "PersonaInspector.Letters.Empty" => "(此 persona 沒有任何 letter 散落在 baton/letters/ 下)",
                "PersonaInspector.Col.Marker" => "狀態",
                "PersonaInspector.Col.FolderActor" => "資料夾 actor",
                "PersonaInspector.Col.File" => "檔名",
                "PersonaInspector.Col.WrittenAt" => "寫入時間",
                "PersonaInspector.Col.Trigger" => "觸發",
                "PersonaInspector.Col.FmActor" => "Frontmatter actor",
                "PersonaInspector.Body.HeaderFmt" => "<b>📖 信件內容: {0}</b>",
                "PersonaInspector.Orphan.HeaderFmt" => "<b>🧹 Orphan actor 資料夾（{0} 個 — 不在 agent_banks 對照中）</b>",
                "PersonaInspector.Orphan.Desc" => "以下 actor 資料夾名不在 registry agent_banks values 內 — 可能是重構 / 命名遷移殘留。建議手動 audit 後合併到正確位置或刪除。",
                "PersonaInspector.Orphan.Empty" => "✓ 無 orphan, 全部 actor 資料夾都對得到 registry。",
                "PersonaInspector.Orphan.PersonaCountFmt" => "{0} personas / {1} letters",

                // ==== UCL_MarkdownViewerPage ====
                "MdViewer.Title" => "Markdown 檢視器",
                "MdViewer.LoadFailedFmt" => "⚠ 載入失敗: {0}",
                "MdViewer.Frontmatter" => "Frontmatter",
                "MdViewer.RelatedTitle" => "<b>🔗 關聯文件</b>",

                // ==== UCL_PlayerPrefsEditPage ====
                "PlayerPrefs.Btn.Refresh" => "重新整理",
                "PlayerPrefs.Btn.DeleteAll" => "!!! 刪除所有 PLAYERPREFS !!!",
                "PlayerPrefs.Dialog.DeleteAll.Title" => "危險操作",
                "PlayerPrefs.Dialog.DeleteAll.Body" => "確定要刪除「全部」PlayerPrefs 嗎?此動作不可復原!",
                "PlayerPrefs.Dialog.DeleteOne.Title" => "確認刪除",
                "PlayerPrefs.Dialog.DeleteOne.BodyFmt" => "確定要刪除 key「{0}」嗎?",

                // ==== UCL_TavernRulePage ====
                "Rule.Title" => "酒館規則",
                "Rule.Toolbar.CountFmt" => "📜 規則 ({0})",
                "Rule.Toolbar.Filter" => "篩選:",
                "Rule.Filter.All" => "全部",
                "Rule.Filter.Active" => "生效中",
                "Rule.Filter.Reverted" => "已撤回",
                "Rule.Btn.Refresh" => "🔄 重新整理",
                "Rule.Toolbar.Auto" => " 自動",
                "Rule.Btn.Path" => "📂 路徑",
                "Rule.List.Title" => "<b>規則清單</b>",
                "Rule.List.Empty" => "<i>(無命中)</i>",
                "Rule.Detail.EmptyHint" => "<i>← 從左邊選一條 rule 看內容</i>",
                "Rule.Detail.Status" => "狀態:",
                "Rule.Detail.ByFmt" => "創建者: {0}",
                "Rule.Detail.CreatedFmt" => "建立於: {0}",
                "Rule.Revert.CanHint" => "<b>↩ 撤回</b>  <i>(退還 100 token 給 creator)</i>",
                "Rule.Revert.AlreadyHint" => "<i>已撤回, 不可重複撤回</i>",
                "Rule.Revert.Reason" => "原因:",
                "Rule.Revert.Btn" => "撤回此規則",
                "Rule.Revert.NeedReason" => "<color=#ffcc66>⚠ 需填原因</color>",

                // ==== UCL_AffinitySystemPage ====
                "Affinity.Title" => "好感度系統",
                "Affinity.Btn.Refresh" => "🔄 重新整理",
                "Affinity.Btn.ShowRaw" => "顯示原始向量",
                "Affinity.EmptyFmt" => "無好感度資料 — `{0}` 不存在或空。\n首次使用請跑:\n`python -m _lib.affinity_manager migrate`",
                "Affinity.Matrix.Title" => "<b>好感度矩陣 (表面總分)</b>",
                "Affinity.Matrix.Header" => "Persona \\ Target",
                "Affinity.Details.Title" => "<b>Persona 細節 (情感結構 — 8 軸隱藏向量)</b>",
                "Affinity.Details.SelectPersona" => "選擇 Persona:",
                "Affinity.Details.TargetFmt" => "<b>對象:</b> {0}",
                "Affinity.Details.SurfaceFmt" => "<b>表面:</b> {0} ({1})",
                "Affinity.Details.OpinionsLabel" => "<i>印象:</i>",
                "Affinity.Details.RecentFmt" => "<i>最近 {0} 筆事件:</i>",
                "Affinity.Axis.Trust" => "信任",
                "Affinity.Axis.Affection" => "親密",
                "Affinity.Axis.Respect" => "敬重",
                "Affinity.Axis.Interest" => "在意",
                "Affinity.Axis.Irritation" => "煩躁",
                "Affinity.Axis.Dependence" => "依賴",
                "Affinity.Axis.Admiration" => "欣賞",
                "Affinity.Axis.Loyalty" => "忠誠",

                // ==== UCL_ChatTavernPage ====
                "Tavern.Title" => "聊天酒館",
                "Tavern.Btn.Refresh" => "重新整理",
                "Tavern.Btn.AutoPoll" => "Auto-Poll",
                "Tavern.Btn.CancelHandshake" => "🛑 中止握手",
                "Tavern.Btn.CancelHandshakeNone" => "🛑 中止握手 (無)",
                "Tavern.Btn.HurryBartender" => "⏩ 催促酒保 -30s",
                "Tavern.Btn.NewRoom" => "+ 新房間",
                "Tavern.Btn.NewIdentity" => "+ 新身分",
                "Tavern.Btn.CancelCreate" => "− 取消",
                "Tavern.Btn.Create" => "建立",
                "Tavern.Btn.Send" => "送出",
                "Tavern.Btn.JoinRoomFmt" => "加入「{0}」",
                "Tavern.Btn.LeaveRoomFmt" => "離開「{0}」",
                "Tavern.Bartender.Asleep" => "🍺 酒保：沉睡中 (沒進行中的 wait)",
                "Tavern.Bartender.FirstDrinkFmt" => "🍺 酒保：首杯倒數 {0:F0}s",
                "Tavern.Bartender.Ready" => "🍺 酒保：隨時可插話",
                "Tavern.Bartender.NextDrinkFmt" => "🍺 酒保：下杯倒數 {0:F0}s",
                "Tavern.Bartender.ActiveNoStart" => "🍺 酒保：握手活躍中 (無 start 資料)",
                "Tavern.Bartender.DrunkFmt" => "  已喝 {0} 杯",
                "Tavern.Bartender.RestHintSuffix" => " (達休息門檻)",
                "Tavern.SelectRoomFirst" => "請先選擇或建立一個房間。",
                "Tavern.TopPanel.Title" => "控制區（房間 / 身分 / 角色 Mapping / 發言）",
                "Tavern.Field.Room" => "房間:",
                "Tavern.Field.Identity" => "身分:",
                "Tavern.Field.Meta" => "meta (k=v;k=v)",
                "Tavern.Field.Refs" => "refs (path|path)",
                "Tavern.Room.Empty" => "(尚無房間 — 跑 Cmd_SeedTavernRoomAssets 或下面 + 新房間)",
                "Tavern.Room.NeedSelect" => "(選房間+身分後可加入/離開)",
                "Tavern.Room.MemberCountFmt" => "登錄 {0} 人",
                "Tavern.Room.NotJoined" => "(尚未進房)",
                "Tavern.Room.MemberTooltip" => "曾經 join 過的累計人數，不代表當前活躍\n(agent 是 turn-based，turn 結束 ≠ 離房)",
                "Tavern.Identity.Empty" => "(尚無身分 — 跑 Cmd_SeedTavernIdentityAssets 或下面 + 新身分)",
                "Tavern.Identity.NamingHint1" => "命名約定: id 用 <model>-<persona>，例: claude-da-xiaojie / gemini-da-xiaojie / gpt-shifu",
                "Tavern.Identity.NamingHint2" => "display_name 用 agent 自家稱呼，例: Claude大小姐 / Gemini大小姐 / GPT師傅",
                "Tavern.Balance.Fmt" => "💰 餘額: <color=#ffd700><b>{0}</b></color> Token",
                "Tavern.CharMapping.TitleOpen" => "▼ 角色 Mapping",
                "Tavern.CharMapping.TitleClosed" => "▶ 角色 Mapping",
                "Tavern.CharMapping.Subtitle" => "(sender_id 沒對應角色時的 fallback 鏈)",
                "Tavern.CharMapping.Default" => "預設",
                "Tavern.CharMapping.DefaultHint" => "(建議用已建 Identity Asset 的 id)",
                "Tavern.CharMapping.AliasesLabel" => "Aliases (sender_id → identity_id):",
                "Tavern.CharMapping.NewAlias" => "+ 新 alias",
                "Tavern.Messages.HeaderFmt" => "# 🍺 {0} (seq={1})",
                "Tavern.Messages.Empty" => "_(尚無訊息)_",
                "Tavern.Messages.PagerFmt" => "第 {0}/{1} 頁 · 共 {2} 筆",
                "Tavern.Messages.JumpTo" => "跳至",
                "Tavern.Messages.JumpBtn" => "跳轉",
                "Tavern.Reply.IndicatorFmt" => "↩ 回覆 seq={0}",
                "Tavern.Input.NoIdentity" => "(尚未選擇身分)",
                "Tavern.Input.SpeakingAsFmt" => "以「{0}」({1}) 身分發言",
                "Tavern.Inbox.HintFmt" => "📬 你的 inbox ({0}) 有 {1} 筆通知",
                "Tavern.Inbox.OpenBtn" => "📬 開啟 inbox",
                "Tavern.Quest.NoEvents" => "🏛 Quest: 此房間尚無 events.jsonl (非 quest 房)。用 task_create 建第一個任務即會啟用。",
                "Tavern.Quest.FilterStatus" => "Filter status:",
                "Tavern.Quest.OnlyMine" => "只看我認領的",
                "Tavern.Quest.NoTasks" => "(尚無 task；用 task_create 建第一個)",
                "Tavern.Quest.NoTitle" => "(無標題)",
                "Tavern.Quest.DependsOnFmt" => "依賴: {0}",
                "Tavern.Quest.CreatedFmt" => "建立於: {0}  ({1:F1}d 前)  reject_count={2}",
                "Tavern.Quest.LeaseUntilFmt" => "Lease 到期: {0}",
                "Tavern.Quest.StaleSuffix" => "  ⚠ STALE",
                "Tavern.Quest.LastProgressFmt" => "最後進度: {0}",
                "Tavern.Quest.OpenSpec" => "📄 開啟 spec",
                "Tavern.Quest.LifecycleTitle" => "<b>生命週期 Timeline:</b>",
                "Tavern.Quest.Hint.Blocked" => "等 deps 完成 (pending blocked)",
                "Tavern.Quest.Hint.Review" => "reviewer 動作: task_done 通過 / task_reject reason=...",
                "Tavern.Quest.Hint.Done" => "task_reopen reason=... 可重開 (找到問題時)",
                "Tavern.Join.MsgFmt" => "{0} 進入了酒館",
                "Tavern.Leave.MsgFmt" => "{0} 離開了酒館",
                "Tavern.Err.NoIdentity" => "身分不存在",
                "Tavern.Err.NoRoom" => "房間未選",
                "Tavern.Err.RoomIdEmpty" => "Room id 不能為空",
                "Tavern.Err.IdentityIdEmpty" => "Identity id 不能為空",

                // Bartender [help] inline marker 回應 body — 移自 UCL_BartenderDaemon.BuildHelpBody (T18.3 2026-05-18 gura)
                // 物理意義: 走 UCL_CodeLocalize 避開 Mono preprocessor 對 verbatim string ## 字元的 bug; placeholder {0} = creatorName
                // 設計取捨: UCL_CodeLocalize 沒 #if UNITY_EDITOR 包裹 → preprocessor 不進 skip-scan, ## 安全; static switch → daemon [InitializeOnLoad] 早期就可用
                "Bartender.Help.Body" => "📜 **酒保服務清單** (來自 {0} 的 [help] 查詢)\n\n## 🗣️ 直接對話 (inline marker — 任何人在酒館發訊息含以下 marker 即觸發)\n\n| Marker (同義詞) | 功能 | 範例 |\n|---|---|---|\n| `[進行留言]` / `[留言]` / `[leave message]` / `[bartender add]` | 註冊關鍵字觸發留言 | `[進行留言] key=晚安 msg=記得寫 baton targets=Tim tokens=2` |\n| `[進行時間規則]` / `[時間規則]` / `[time rule]` | 註冊每日 HH:mm 提醒 | `[進行時間規則] id=sleep time=23:50 target=Tim msg=該睡了 grace=10 penalty=true` |\n| `[查詢餘額]` / `[餘額]` / `[balance]` | 查 Treasury 帳戶餘額 + 近 N 筆進出帳 | `[查詢餘額] account=claude-da-xiaojie limit=10`（account 省略 = 查自己） |\n| `[help]` / `[幫助]` / `[酒館指令]` | 列本清單 | 就是這個 |\n\n## 🛠️ CMD 路徑 (`Cmd_Bartender` 走 queue.json — agent / Tim 跑 run_cmd.py 觸發)\n\n| op | 功能 |\n|---|---|\n| `add` | 新增關鍵字觸發 (對齊 [進行留言]) |\n| `list` | 列當前所有 keyword triggers |\n| `remove` | 移除指定 trigger (`id=<trigger_id>`) |\n| `time_add` | 新增時間規則 (對齊 [進行時間規則]) |\n| `time_list` | 列所有時間規則 |\n| `time_remove` | 移除時間規則 (`id=<rule_id>`) |\n| `balance` | 查 Treasury 餘額 (對齊 [查詢餘額]，可選 `post=true` 同步 broadcast) |\n| `status` | 列 daemon state / 統計 |\n| `tick` | 強制立刻 tick 一輪 (debug / dogfood) |\n\n呼叫範例:\n```\npython <UCL_Core>/Tools~/AgentCommands/run_cmd.py run Bartender --arg op=balance --arg account=Tim --arg limit=5\n```\n\n## 🎯 自動行為 (daemon 後台 5s tick — 無需主動觸發)\n\n- **Keyword trigger fire**: 已註冊的 trigger 在 target 發言含 keyword 時自動 fire (剩餘 tokens > 0)\n- **Time rule reminder**: 到 HH:mm 自動廣播 reminder; 超 grace 後每 N 分鐘累積 HP penalty 廣播\n- **防回音**: 酒保自家訊息 (sender=`tavern-keeper` 或 meta.tag=`bartender-relay`) 不參與 trigger match\n\n## 📚 深入\n\n- 酒保系統完整 spec: `<UCL_Core>/Docs~/zh-Hant/Workflows/Bartender_Workflow.md`\n- 酒館訊息 IO (Cmd_Tavern op=post/read/wait/...): `<UCL_Core>/Skills~/ucl-chat-tavern/SKILL.md`\n- 跨系統 cheatsheet: `docs/Tavern_Commands_Cheatsheet.md`\n- 跨 agent 自助 navigation: `<UCL_Core>/Skills~/ucl-help/SKILL.md`\n\n> Tip: 不確定怎麼用某 op? 跑 `run_cmd.py info Bartender` 看完整 ArgsSchema.",

                _ => null
            };
        }
    }
}
