
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_ja(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "Edit Modules" => "Edit Modules",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "プレイリスト",
                "UCL_ModulePlayListPage" => "プレイリストを編集する",
                "Create new module" => "Create new module",
                "Module ID" => "Module ID",
                "EditModulewarning" => "内蔵モジュール（Core）の編集は、更新後に無効になります。\n新しいモジュールを作成して、既存のコンテンツを追加または上書きしてください。 \n異なるモジュールに同じIDのコンテンツがある場合、 \n後から読み込まれたモジュールのコンテンツが前のものを上書きします。",
                "EditType" => "Edit type",
                "UCL_ModuleEditType_Builtin" => "Builtin",
                "UCL_ModuleEditType_Runtime" => "Runtime",
                "UCL_ModuleEditType_Template" => "テンプレート",
                "Save Config" => "Save Config",
                "Load Config" => "Load Config",
                "Open Module Folder" => "Open Module Folder",
                "ModuleService Config" => "ModuleService Config",
                "Loaded modules" => "Loaded modules",
                "Config" => "設定",
                "Current playlist" => "Current playlist",
                "Create new playlist" => "Create new playlist",
                "Load current playlist" => "現在のプレイリストを読み込む",
                "ModulePlayListTip" => "モジュールを有効にするには、 \n「プレイリストを編集する」を押して、 \n有効にしたいモジュールをプレイリストに追加してください。",
                "UCL_ModulePlayListPageTip" => "編集したいプレイリストを選択するか、\n新しいモジュールプレイリストを作成してください。",
                "UCL_ModulePlayListPageSaveTip" => "プレイリストを編集した後、「保存」を押してください。\n 現在のプレイリストを適用するには、\n「現在のプレイリストを読み込む」を押してください。",
                "UCL_CreateNewModulePageTip" => "モジュールIDには「純粋な数字」（例：3387893998）\nを使用しないでください。\nSteamでサブスクライブされたモジュールは数字をIDとして使用します。\nIDがSteamでサブスクライブされたモジュールと同じ場合、上書きされます。",
                "DeleteTargetDes" => "\"{0}\"を削除します",
                "UCL_LocalizeAsset" => "ローカライズ資産",
                "UCL_ModResourceAsset" => "ModResource",
                "UCL_LanguageCodeAsset" => "編輯支援の言語コード",
                "UCL_SteamWorkshopAsset" => "Steamワークショップ",
                "Module Content" => "モジュール内容",
                "Asset Type" => "アセットタイプ",
                "Open Folder" => "フォルダーを開く",
                "SteamAPILangCode" => "SteamAPI言語コード",
                "EWorkshopFileType" => "ワークショップファイルタイプ",
                "Visibility" => "視認性",
                "Dependencies" => "依存関係",
                "PublishedFileId" => "ワークショップアイテムID",
                "ChangeLog" => "変更履歴",
                "Create workshop item" => "ワークショップアイテムを生成する",
                "Update item to workshop" => "アイテムをワークショップに同期する",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公開",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "コミュニティ",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "モジュールを現在のプレイリストに追加する",
                "AddNewModulesToCurrentPlaylistContent" => "新しく購読したモジュールを{0}\n現在のプレイリストに追加しますか({1})？",
                "HideThisOption" => "このオプションを隠す",
                "Asset Group" => "Asset Group",
                "Confirm" => "確認",
                "Cancel" => "キャンセル",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "再インストール",
                "ReInstallAlert" => "再インストールすると、すべてのモジュールが削除されます。\n再インストールを実行しますか？\n（ゲームが正常に動作しない場合や起動しない場合は、再インストールを試みることができます。）",
                "Edit" => "編集",
                "Preview" => "プレビュー",
                "OpenFile" => "ファイルを開く",
                "UCL_LocalizeEditPage" => "ローカライズの編集",
                "UCL_LocalizeEditPage_Language" => "言語",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（UCL_LanguageCodeAsset が未登録）",
                "UCL_LocalizeEditPage_Current" => "現在：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "適用（永続化）",
                "UCL_LocalizeEditPage_Reset" => "リセット",
                "UCL_LocalizeEditPage_ClearOverride" => "永続化された上書きをクリア",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset に上書きあり）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （現在デフォルト値を使用中）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  デフォルト値：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 適用すると UCL_ConfigAsset/{0}.json に永続化され、次回起動時に自動読み込みされます。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ コード制御（セッション内のみ）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "ダウンロード",
                "Key" => "辞書キー",
                "MoveElement" => "移動エレメント",
                "SelectAssetTemplateDes" => "Select {0} asset template",
                "OpenModuleRootFolder" => "Open Module Folder",
                "OpenModuleInstallFolder" => "Open Install Folder",
                "CopyToClipboard" => "クリップボードにコピー",
                "PasteFromClipboard" => "クリップボードから貼り付ける",
                "CopyDescriptionToClipboard" => "複製説明文をクリップボードにコピーする。",
                "Rename" => "リネーム",
                "EditGroup" => "Edit Group",
                "ShowDeleteButton" => "Show Delete Button",
                "CreateFolder" => "フォルダーを作成する",
                "Delete" => "削除",
                "CreateNew" => "Create New",
                "RefreshData" => "Refresh Data",
                "Save" => "Save",
                "Copy" => "コピー",
                "Paste" => "ペースト",
                "Back" => "戻る",
                "Close" => "閉じる",
                "Select" => "選択",
                "Search" => "検索",
                "Add" => "追加",
                "SetCount" => "カウント設定",
                "SaveBeforeExit?" => "Save before exit?",
                "ExitWitoutSave" => "Exit without save",
                "UCL_SelectAsset" => "アセットを選択",
                "UCL_CreateAsset" => "アセットを作成",
                "UCL_SaveSuccess" => "保存に成功しました！",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / 概要",
                "Welcome.Title" => "👋  UCL_Core へようこそ",
                "Welcome.Subtitle" => "プロジェクト横断の Unity 基盤ライブラリ  ·  Welcome ページ v{0}",
                "Welcome.IntroTitle" => "UCL_Core とは？",
                "Welcome.IntroBody" => "UCL_Core はプロジェクト横断で共有する Unity 基盤ライブラリです。データアセット (UCL_Asset)、モジュールシステム、ローカライズ、Editor Page、Agent Command クロスプロセスシステムなどの主要コンポーネントを提供します。\n素早く始めたい？下の機能カードから普段使うものを 1 つ選んで開始してください。",
                "Welcome.FeaturesTitle" => "主要機能 (ボタンで直接開く)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset システム",
                "Welcome.Asset.Desc" => "JSON シリアライズされた設計アセット (カード / アイテム / モンスターなど)。Editor 側ビジュアル編集、クロスプラットフォーム IO、SerializeReference 多態サポート。",
                "Welcome.Asset.Btn" => "Modules エディタを開く",
                "Welcome.Localize.Title" => "🌐  ローカライズ (翻訳文字列編集)",
                "Welcome.Localize.Desc" => "各言語の翻訳文字列、CurLangKey、PlayerPrefs key を編集。言語切替だけなら上の言語バーで OK、このページに入る必要はありません。",
                "Welcome.Localize.Btn" => "Localize エディタを開く",
                "Welcome.Lang.Label" => "🌐 言語：",
                "Welcome.Lang.NoneAvailable" => "(UCL_LanguageCodeAsset 未検出 — 先に Language Asset を作成してください)",
                "Welcome.Lang.OpenEditor" => "詳細編集…",
                "Welcome.Agent.Title" => "🤖  Agent Commands (agent ↔ Editor クロスプロセス)",
                "Welcome.Agent.Desc" => "AI agent が queue.json に書き込み、Editor Watcher が自動実行 — ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat などの組み込み Cmd を含む。",
                "Welcome.Agent.Btn" => "Agent Commands ページを開く",
                "Welcome.Editor.Title" => "🪟  Editor Pages フレームワーク",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — 統一スタイルの IMGUI ページスタック、検索可能ドロップダウン、HelpURL ジャンプ、TopBar カスタマイズ対応。",
                "Welcome.Editor.Btn" => "PlayerPrefs 編集サンプル",
                "Welcome.DocBtn" => "📖 ドキュメント",
                "Welcome.DocsTitle" => "📚 ドキュメント入口",
                "Welcome.Docs.Index" => "UCL_Core ドキュメント index",
                "Welcome.Docs.Architecture" => "Agent Command 全体アーキテクチャ",
                "Welcome.Docs.CreateCmd" => "新規 Cmd SOP",
                "Welcome.Docs.Validate" => "UCL_Asset フォーマット検証",
                "Welcome.Docs.CompileError" => "🔧 コンパイルエラー診断ワークフロー",
                "Welcome.AutoOpenToggle" => " このページを自動表示しない (UCL → Welcome メニューから手動で開けます)",
                "Welcome.ResetButton" => "初回表示をリセット (次回 Editor 再起動時に再度表示)",
                "Welcome.ResetLog" => "[UCL_Welcome] 初回表示状態をリセットしました。次回の domain reload で再度表示されます。",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(未設定)",
                "Welcome.Search.Title" => "🔍 ドキュメント検索",
                "Welcome.Search.Button" => "検索",
                "Welcome.Search.Hint" => "同義語展開対応 (Docs/_synonyms.txt 読み込み) — 例：「アイテム」で検索すると「道具」と書かれたドキュメントもヒット。複数語はスペース区切り (AND モード)。",
                "Welcome.Search.NoResults" => "(ヒットなし)",
                "Welcome.Search.ResultsCount" => "{0} 件ヒット ({1} 件中)",
                "Welcome.Search.OpenButton" => "📖 ファイルを開く",
                "Welcome.Search.OpenPageButton" => "🔍 ドキュメント検索ページを開く",
                "DocSearch.Advanced" => "詳細オプション",
                "DocSearch.Mode" => "検索モード",
                "DocSearch.Limit" => "結果上限",
                "DocSearch.SynonymsPath" => "同義語ファイルパス",
                "DocSearch.IncludeArchived" => "archived ドキュメントを含む",
                "DocSearch.Reveal" => "📂 場所を開く",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "更新",
                "AgentCmd.RunPending" => "保留中の指令を実行",
                "AgentCmd.ClearFailed" => "失敗をクリア",
                "AgentCmd.OpenFolder" => "フォルダを開く",
                "AgentCmd.QueuePath" => "Queue: {0}",
                "AgentCmd.Stats" => "合計: {0} | OneShot: {1} | Repeatable: {2}",
                "AgentCmd.Commands" => "指令一覧",
                "AgentCmd.QueueEmpty" => "（queue は空です — 下から Command を選んで追加するか、queue.json を直接編集してください）",
                "AgentCmd.Remove" => "削除",
                "AgentCmd.AddCommand" => "指令を追加",
                "AgentCmd.NoHandlers" => "（Handler が未登録 — UCL_AgentCommandHandlerBase を継承したクラスを作成してください）",
                "AgentCmd.Command" => "指令:",
                "AgentCmd.Mode" => "モード:",
                "AgentCmd.Description" => "説明:",
                "AgentCmd.Args" => "引数:",
                "AgentCmd.ArgsFormat" => "（書式: k=v;k=v）",
                "AgentCmd.ArgsSchema" => "  Args Schema: {0}",
                "AgentCmd.Example" => "  例: {0}",
                "AgentCmd.FillExample" => "例を入力",
                "AgentCmd.ViewHelp" => "ヘルプ表示",
                "AgentCmd.AddButton" => "「{0}」を追加（{1}）",
                "AgentCmd.SaveTemplateName" => "テンプレートとして保存 — 名前:",
                "AgentCmd.SaveTemplate" => "テンプレート保存",
                "AgentCmd.TemplateNotes" => "テンプレートのメモ:",
                "AgentCmd.Templates" => "テンプレート",
                "AgentCmd.TemplatesCount" => " {0} 件",
                "AgentCmd.Search" => "検索:",
                "AgentCmd.Clear" => "クリア",
                "AgentCmd.NoTemplates" => "（テンプレートなし — 上の「指令を追加」セクションを記入し「テンプレート保存」を押してください）",
                "AgentCmd.ApplyToForm" => "フォームに適用",
                "AgentCmd.AddToQueue" => "Queue に追加",
                "AgentCmd.Delete" => "削除",
                "AgentCmd.History" => "履歴",
                "AgentCmd.HistoryCount" => " {0} 件",
                "AgentCmd.NoHistory" => "（一致する履歴なし — 「指令を追加」でここに自動記録されます）",
                "AgentCmd.Cleanup" => "整理 —",
                "AgentCmd.OlderThanDays" => "経過日数:",
                "AgentCmd.DeleteOlder" => "古いものを削除",
                "AgentCmd.Dedupe" => "重複を削除",
                "AgentCmd.ClearAll" => "全削除",
                "AgentCmd.ClearAllConfirmTitle" => "履歴を全削除しますか？",
                "AgentCmd.ClearAllConfirmBody" => "{0} 件の履歴を削除します。この操作は取り消せません。",
                "AgentCmd.ConfirmDelete" => "削除",
                "AgentCmd.ConfirmCancel" => "キャンセル",
                "AgentCmd.ReAdd" => "再追加",
                "AgentCmd.ToTemplate" => "→ テンプレート",
                "AgentCmd.AutoWatcher" => "自動ウォッチャー",
                "AgentCmd.LastTrigger" => "最終トリガー: {0}",
                "AgentCmd.Never" => "（未実行）",
                "AgentCmd.SimulateTrigger" => "トリガー疑似実行",
                "AgentCmd.Tips" => "ヒント",
                "AgentCmd.Tip_OneShot" => "- OneShot: 実行成功後、queue から即削除されます",
                "AgentCmd.Tip_Repeatable" => "- Repeatable: Run のたびに再実行され、RunCount が +1 されます",
                "AgentCmd.Tip_WaitInit" => "- Run の前に await UCL_ModuleService.WaitUntilInitialized を行い、モジュール系の準備完了を保証します",
                "AgentCmd.Tip_FailedKept" => "- 失敗した指令は LastRunError にエラーが書き込まれ、queue に残ります（自動削除されません）",
                "AgentCmd.Tip_Watcher" => "- Auto-Watcher 有効時: 外部から AgentCommands/pending.trigger を書き込むと自動で Run Pending が発火します（手動操作不要）",
                "AgentCmd.Tip_ExportCatalog" => "- Cmd カタログをエクスポートしたい？ 'ExportCommandCatalog' Cmd を 1 件追加するだけです（独立ボタンは廃止済み）",

                _ => null
            };
        }
    }
}
