
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_ja(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "ReadOnly" => "読み取り専用",
                "Module_ReadOnly_Banner" => "読み取り専用（内蔵リファレンス）— 編集するには「編集可能なモジュールへ複製」を押してください",
                "Fork_To_Editable" => "編集可能なモジュールへ複製（Fork）",
                "Fork_NewID_Prompt" => "新しいモジュール ID",
                "Edit Modules" => "Edit Modules",
                "ToolBox.Title" => "ツールボックス",
                "ToolBox.MenuButton" => "🧰 ツールボックスを開く",
                "ToolBox.Group.Git" => "🔀 Git / コミット",
                "ToolBox.Group.AgentOps" => "🧭 エージェント運用",
                "ToolBox.Group.Runtime" => "🖥 モデルと実行環境",
                "ToolBox.Group.Docs" => "📖 ドキュメントと多言語",
                "ToolBox.Group.Content" => "📚 コンテンツとライブラリ",
                "ToolBox.GitFlattenSync" => "Git フラット同期",
                "ToolBox.GitFlattenSync.Desc" => "submodule を含む repo をプレーンなファイルへ展開し、別 repo の作業ディレクトリへ同期します（ソースは読み取りのみ、宛先はファイル書き込みのみ — どちらの git も触りません）。",
                "ToolBox.GitSubmoduleSync" => "Git Submodule 同期",
                "ToolBox.GitSubmoduleSync.Desc" => "全 submodule に対して既定 branch への checkout / pull / push を一括実行 — detached や ahead を一覧で把握し、submodule update 後のブランチずれを防ぎます。",
                "ToolBox.AutoCommit" => "自動 Commit",
                "ToolBox.AutoCommit.Desc" => "AgentCommands の自動生成ファイル（酒場メッセージ / Treasury / runtime state）をグループ分けし、ボタンで各グループを個別 commit（メッセージ自動生成）。ephemeral ファイルは常に除外。",
                "ToolBox.LLMModelAdmin" => "ローカル LLM モデル",
                "ToolBox.LLMModelAdmin.Desc" => "ローカルの大規模言語モデル（ollama）を管理：環境状態の確認、厳選カタログからのインストール／アンインストール、動作確認の一発実行。既定で Qwen シリーズ（VRAM 6GB 以下で動くサイズ）を収録。",
                "ToolBox.DocSearch" => "ドキュメント検索",
                "ToolBox.DocSearch.Desc" => "200 以上の markdown を横断する即時あいまい検索（同義語展開・現在のロケール優先）。",
                "ToolBox.LocalizeEdit" => "多言語編集",
                "ToolBox.LocalizeEdit.Desc" => "UCL_LocalizeAsset の多言語文字列テーブルを編集します。",
                "ToolBox.ScreenStream" => "画面配信・録画",
                "ToolBox.ScreenStream.Desc" => "画面録画 / STT / OCR デーモンのコンソール（配信の同時視聴、音声文字起こし）。",
                "ToolBox.ProcessAdmin" => "プロセス管理",
                "ToolBox.ProcessAdmin.Desc" => "C# から起動した外部プロセスの確認と処置（PID + 名前 + 起動時刻の三重照合で誤終了とゾンビ増殖を防ぐ）。",
                "ToolBox.TaskManager" => "タスク・プロジェクト管理",
                "ToolBox.TaskManager.Desc" => "エージェント横断のタスクチケット（1件1ファイル）。他者が待つ約束は Task、自分だけの自律は見叢へ。未解決の blocker がある間は完了不可、in_progress は 14 日で stale 表示。",
                "ToolBox.Relationship" => "関係（Relationship）",
                "ToolBox.Relationship.Desc" => "persona ごとの好感度を「イベント台帳」として保持 —— スコアはイベントから再計算される投影。",
                "ToolBox.SessionAdmin" => "🗂 Session 管理",
                "ToolBox.SessionAdmin.Desc" => "各 persona の session 現況（自由時間…）。終了時刻を過ぎても active な残留を明示。",
                "ToolBox.FreeTimeAdmin" => "🎲 自由時間管理",
                "ToolBox.FreeTimeAdmin.Desc" => "ダイス面の活動設定（有効／グループ／推奨分数／特殊ロジック／実行ヒント）—— 活動 md の frontmatter を直接書き換え、override は作らない。",
                "ToolBox.LibraryManage" => "ライブラリ管理",
                "ToolBox.LibraryManage.Desc" => "既存の Books とライブラリデータを管理します。",
                "ToolBox.ReadingNotesManage" => "読書メモ管理",
                "ToolBox.ReadingNotesManage.Desc" => "作品名から Archive と新 Library の手動入口を検索します。",
                "ToolBox.SculptureViewer" => "3D彫刻ビューア",
                "ToolBox.SculptureViewer.Desc" => "共有3Dボクセル空間をレンダリング — 展示プリセットのワンクリック表示、または手動パラメータ指定。",
                "SculptureViewer.Title" => "3D彫刻ビューア",
                "SculptureViewer.Exhibits" => "🏛 展示品（exhibits.json より）",
                "SculptureViewer.RenderExhibit" => "展示品をレンダリング",
                "SculptureViewer.Reload" => "再読込",
                "SculptureViewer.RenderAll" => "全景レンダリング",
                "SculptureViewer.NoExhibit" => "（登録済み展示なし — sculpt.py exhibit register）",
                "SculptureViewer.Manual" => "🔧 手動観測パラメータ",
                "SculptureViewer.RenderManual" => "パラメータでレンダリング",
                "Agent Commands" => "Agent 指令集",
                "Playlist" => "プレイリスト",
                "UCL_ModulePlayListPage" => "プレイリストを編集する",
                "Create new module" => "Create new module",
                "Module ID" => "Module ID",
                "EditModulewarning" => "内蔵モジュール（Core など）は、インストール不要（直接読み込み）モードでは読み取り専用で、\n参照閲覧のみ可能で直接編集はできません。\n編集するには、モジュールを開いて「編集可能なモジュールへ複製（Fork）」を押すと、編集可能なモジュールが複製されます。\n異なるモジュールに同じIDのコンテンツがある場合、後から読み込まれたモジュールが上書きします。",
                "EditType" => "Edit type",
                "UCL_ModuleEditType_Builtin" => "Builtin",
                "UCL_ModuleEditType_Runtime" => "Runtime",
                "UCL_ModuleEditType_Template" => "テンプレート",
                "Save Config" => "Save Config",
                "Load Config" => "Load Config",
                "Open Module Folder" => "Open Module Folder",
                "ModuleService Config" => "ModuleService Config",
                "Loaded modules" => "Loaded modules",
                "Config" => "設定",
                "Current playlist" => "Current playlist",
                "Create new playlist" => "Create new playlist",
                "Load current playlist" => "現在のプレイリストを読み込む",
                "ModulePlayListTip" => "モジュールを有効にするには、 \n「プレイリストを編集する」を押して、 \n有効にしたいモジュールをプレイリストに追加してください。",
                "UCL_ModulePlayListPageTip" => "編集したいプレイリストを選択するか、\n新しいモジュールプレイリストを作成してください。",
                "UCL_ModulePlayListPageSaveTip" => "プレイリストを編集した後、「保存」を押してください。\n 現在のプレイリストを適用するには、\n「現在のプレイリストを読み込む」を押してください。",
                "UCL_CreateNewModulePageTip" => "モジュールIDには「純粋な数字」（例：3387893998）\nを使用しないでください。\nSteamでサブスクライブされたモジュールは数字をIDとして使用します。\nIDがSteamでサブスクライブされたモジュールと同じ場合、上書きされます。",
                "DeleteTargetDes" => "\"{0}\"を削除します",
                "UCL_LocalizeAsset" => "ローカライズ資産",
                "UCL_ModResourceAsset" => "ModResource",
                "UCL_LanguageCodeAsset" => "編輯支援の言語コード",
                "UCL_SteamWorkshopAsset" => "Steamワークショップ",
                "Module Content" => "モジュール内容",
                "Asset Type" => "アセットタイプ",
                "Open Folder" => "フォルダーを開く",
                "SteamAPILangCode" => "SteamAPI言語コード",
                "EWorkshopFileType" => "ワークショップファイルタイプ",
                "Visibility" => "視認性",
                "Dependencies" => "依存関係",
                "PublishedFileId" => "ワークショップアイテムID",
                "ChangeLog" => "変更履歴",
                "Create workshop item" => "ワークショップアイテムを生成する",
                "Update item to workshop" => "アイテムをワークショップに同期する",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "公開",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "コミュニティ",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "モジュールを現在のプレイリストに追加する",
                "AddNewModulesToCurrentPlaylistContent" => "新しく購読したモジュールを{0}\n現在のプレイリストに追加しますか({1})？",
                "HideThisOption" => "このオプションを隠す",
                "Asset Group" => "Asset Group",
                "Confirm" => "確認",
                "Cancel" => "キャンセル",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "再インストール",
                "ReInstallAlert" => "再インストールすると、すべてのモジュールが削除されます。\n再インストールを実行しますか？\n（ゲームが正常に動作しない場合や起動しない場合は、再インストールを試みることができます。）",
                "Edit" => "編集",
                "Preview" => "プレビュー",
                "OpenFile" => "ファイルを開く",
                "UCL_LocalizeEditPage" => "ローカライズの編集",
                "UCL_LocalizeEditPage_Language" => "言語",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "（UCL_LanguageCodeAsset が未登録）",
                "UCL_LocalizeEditPage_Current" => "現在：",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key（CurLangKey）",
                "UCL_LocalizeEditPage_Key" => "Key：",
                "UCL_LocalizeEditPage_ApplyPersist" => "適用（永続化）",
                "UCL_LocalizeEditPage_Reset" => "リセット",
                "UCL_LocalizeEditPage_ClearOverride" => "永続化された上書きをクリア",
                "UCL_LocalizeEditPage_OverrideExists" => "  （UCL_ConfigAsset に上書きあり）",
                "UCL_LocalizeEditPage_UsingDefault" => "  （現在デフォルト値を使用中）",
                "UCL_LocalizeEditPage_DefaultFmt" => "  デフォルト値：\"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 適用すると UCL_ConfigAsset/{0}.json に永続化され、次回起動時に自動読み込みされます。",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ コード制御（セッション内のみ）：UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "ダウンロード",
                "Key" => "辞書キー",
                "MoveElement" => "移動エレメント",
                "SelectAssetTemplateDes" => "Select {0} asset template",
                "OpenModuleRootFolder" => "Open Module Folder",
                "OpenModuleInstallFolder" => "Open Install Folder",
                "CopyToClipboard" => "クリップボードにコピー",
                "PasteFromClipboard" => "クリップボードから貼り付ける",
                "CopyDescriptionToClipboard" => "複製説明文をクリップボードにコピーする。",
                "Rename" => "リネーム",
                "EditGroup" => "Edit Group",
                "ShowDeleteButton" => "Show Delete Button",
                "CreateFolder" => "フォルダーを作成する",
                "Delete" => "削除",
                "CreateNew" => "Create New",
                "RefreshData" => "Refresh Data",
                "Save" => "Save",
                "Copy" => "コピー",
                "Paste" => "ペースト",
                "Back" => "戻る",
                "Close" => "閉じる",
                "Select" => "選択",
                "Search" => "検索",
                "Add" => "追加",
                "SetCount" => "カウント設定",
                "SaveBeforeExit?" => "Save before exit?",
                "ExitWitoutSave" => "Exit without save",
                "UCL_SelectAsset" => "アセットを選択",
                "UCL_CreateAsset" => "アセットを作成",
                "UCL_SaveSuccess" => "保存に成功しました！",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / 概要",
                "Welcome.Title" => "👋  UCL_Core へようこそ",
                "Welcome.Subtitle" => "プロジェクト横断の Unity 基盤ライブラリ  ·  Welcome ページ v{0}",
                "Welcome.IntroTitle" => "UCL_Core とは？",
                "Welcome.IntroBody" => "UCL_Core はプロジェクト横断で共有する Unity 基盤ライブラリです。データアセット (UCL_Asset)、モジュールシステム、ローカライズ、Editor Page、Agent Command クロスプロセスシステムなどの主要コンポーネントを提供します。\n素早く始めたい？下の機能カードから普段使うものを 1 つ選んで開始してください。",
                "Welcome.FeaturesTitle" => "主要機能 (ボタンで直接開く)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset システム",
                "Welcome.Asset.Desc" => "JSON シリアライズされた設計アセット (カード / アイテム / モンスターなど)。Editor 側ビジュアル編集、クロスプラットフォーム IO、SerializeReference 多態サポート。",
                "Welcome.Asset.Btn" => "Modules エディタを開く",
                "Welcome.Localize.Title" => "🌐  ローカライズ (翻訳文字列編集)",
                "Welcome.Localize.Desc" => "各言語の翻訳文字列、CurLangKey、PlayerPrefs key を編集。言語切替だけなら上の言語バーで OK、このページに入る必要はありません。",
                "Welcome.Localize.Btn" => "Localize エディタを開く",
                "Welcome.Lang.Label" => "🌐 言語：",

                "Welcome.CommandTable.Label" => "📋 コマンド対照：",
                "Welcome.CommandTable.Desc" => "AI Agent の口語コマンド・トリガー語と対応する Workflow をまとめた参照マニュアル。",
                "Welcome.CommandTable.Btn" => "📄 コマンド表をプレビュー",

                "Welcome.Lang.NoneAvailable" => "(UCL_LanguageCodeAsset 未検出 — 先に Language Asset を作成してください)",
                "Welcome.Lang.OpenEditor" => "詳細編集…",
                "Welcome.Agent.Title" => "🤖  Agent Commands (agent ↔ Editor クロスプロセス)",
                "Welcome.Agent.Desc" => "AI agent が queue.json に書き込み、Editor Watcher が自動実行 — ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat などの組み込み Cmd を含む。",
                "Welcome.Agent.Btn" => "Agent Commands ページを開く",
                "Welcome.Editor.Title" => "🪟  Editor Pages フレームワーク",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — 統一スタイルの IMGUI ページスタック、検索可能ドロップダウン、HelpURL ジャンプ、TopBar カスタマイズ対応。",
                "Welcome.Editor.Btn" => "PlayerPrefs 編集サンプル",
                "Welcome.DocBtn" => "📖 ドキュメント",

                "Welcome.DocsTitle" => "📚 ドキュメント入口",
                "Welcome.Docs.Index" => "UCL_Core ドキュメント index",
                "Welcome.Docs.Architecture" => "Agent Command 全体アーキテクチャ",
                "Welcome.Docs.CreateCmd" => "新規 Cmd SOP",
                "Welcome.Docs.Validate" => "UCL_Asset フォーマット検証",
                "Welcome.Docs.CompileError" => "🔧 コンパイルエラー診断ワークフロー",
                // Welcome ページの Skill 入口カード（小、独立した AgentSkillManager ページへ誘導）
                "Welcome.SkillEntry.Title" => "🧩  Agent Skill 管理",
                "Welcome.SkillEntry.Desc" => "UCL_Core の commit / 酒場入り / コンパイルエラー診断などの workflow を AI agent Skill として抽出 — 各 agent (Claude Code / Cursor / Antigravity / Gemini) のインストールパスは管理ページが統一処理。初回 Welcome で自動表示されます。",
                "Welcome.SkillEntry.OpenBtn" => "🛠 Skill 管理ページを開く",

                // 独立した UCL_AgentSkillManagerPage
                "AgentSkill.Title" => "🛠 Agent Skill Manager",
                "AgentSkill.Subtitle" => "UCL_Core の workflow を各 AI agent 用にインストール",
                "AgentSkill.ConceptTitle" => "なぜこのページ？",
                "AgentSkill.ConceptBody" => "UCL_Core/Skills~/ 内の各 skill は「lazy-load workflow」— agent はトリガー語を見た時だけ完全な SOP を読み込み、普段は context を消費しません。各 agent には固有のパス規約があります：Claude Code → .claude/skills/、Antigravity → .agents/rules/（計画中：Cursor → .cursor/rules/、Gemini）。このページは対応する全 target へ統一インストールします。",
                "AgentSkill.OneClick.Title" => "ワンクリックインストール（Claude Code / Antigravity 対応）",
                "AgentSkill.OneClick.Desc" => "Tools~/install_skills.py --target <X> を実行し、全 skill を対応 dst（Claude → .claude/skills/、Antigravity → .agents/rules/）へコピーします。冪等で再実行可能；ローカル変更を検出した場合は上書きしません。",
                "AgentSkill.Status.NotInstalled" => "⚠ 未インストール — 下のボタンでワンクリックインストール",
                "AgentSkill.Status.Synced" => "✓ インストール済み・ソース内容と一致",
                "AgentSkill.Status.Stale" => "⚠ インストール済み内容がソースと不一致（ソース更新またはローカル改変）— 再インストール／強制同期を推奨",
                "AgentSkill.Status.LegacyNoHash" => "⚠ 旧版 marker に source_hash フィールドがありません — 一度再インストールすれば比較基準が更新されます",
                "AgentSkill.Status.UnknownHead" => "インストール済みですが UCL_Core HEAD を判定できません（git が PATH にない？）",
                "AgentSkill.Status.NoProjectRoot" => "host project root が見つかりません（.claude/ も .git/ もない）— Tools~/install_skills.py --project-root <path> を手動実行してください",
                "AgentSkill.Status.NoUCLCore" => "UCL_Core パスが見つかりません（UCL_EditorPath.CorePath が空）",
                "AgentSkill.HostRoot" => "Project root: {0}",
                "AgentSkill.Btn.Install" => "🚀 インストール",
                "AgentSkill.Btn.InstallAll" => "🚀 全 target をワンクリックインストール",
                "AgentSkill.Btn.ForceSyncAll" => "⚡ 全て強制同期（ローカル変更を上書き）",
                "AgentSkill.Btn.ForceSyncAll.Synced" => "✅ すべて同期済み（強制上書きは引き続き可能）",
                "AgentSkill.SkippedWarn" => "⚠ 前回のインストールで {0} 件がローカル変更のためスキップされ、内容が未更新です — 「再インストール」または「強制同期」で上書き（詳細は Console）",
                "AgentSkill.Btn.Sync" => "🔄 現在のバージョンへ同期",
                "AgentSkill.Btn.Reinstall" => "🔁 再インストール",
                "AgentSkill.Btn.Refresh" => "更新",
                "AgentSkill.Btn.Doc" => "📖 Skills~/README",
                "AgentSkill.Btn.ResetAck" => "初回表示をリセット",
                "AgentSkill.Matrix.Title" => "🎛 Per-Agent × Per-Skill 切替",
                "AgentSkill.Matrix.Body" => "ドロップダウンで agent を選び、その agent の skill 別インストール状態を表示/管理します。installed/drift は agent 別、disabled（UCL_SkillConfigAsset）は全 agent 共用：",
                "AgentSkill.Matrix.NoSource" => "(UCL_Core/Skills~/ ソースディレクトリが見つかりません)",
                "AgentSkill.Matrix.Status.DisabledPendingRemove" => "🚫無効·削除待ち",
                "AgentSkill.Matrix.Status.Disabled" => "🚫無効",
                "AgentSkill.Matrix.Status.NotInstalled" => "未インストール",
                "AgentSkill.Matrix.Status.Drift" => "⚠変更",
                "AgentSkill.Matrix.Status.Synced" => "✓同期",
                "AgentSkill.Matrix.Btn.Enable" => "有効化",
                "AgentSkill.AckToggle" => " このページを自動表示しない（skill が更新されても表示しない。メニューから手動で開けます）",
                "AgentSkill.LastChangesLabel" => "前回の自動表示の理由 — skill 変更: {0}",
                "AgentSkill.AckVersionLabel" => "AcknowledgedVersion: {0}",
                "AgentSkill.NotSet" => "(未設定)",


                "Welcome.AutoOpenToggle" => " このページを自動表示しない (UCL → Welcome メニューから手動で開けます)",
                "Welcome.ResetButton" => "初回表示をリセット (次回 Editor 再起動時に再度表示)",
                "Welcome.ResetLog" => "[UCL_Welcome] 初回表示状態をリセットしました。次回の domain reload で再度表示されます。",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(未設定)",
                "Welcome.Search.Title" => "🔍 ドキュメント検索",
                "Welcome.Search.Button" => "検索",
                "Welcome.Search.Hint" => "同義語展開対応 (Docs/_synonyms.txt 読み込み) — 例：「アイテム」で検索すると「道具」と書かれたドキュメントもヒット。複数語はスペース区切り (AND モード)。",
                "Welcome.Search.NoResults" => "(ヒットなし)",
                "Welcome.Search.ResultsCount" => "{0} 件ヒット ({1} 件中)",
                "Welcome.Search.OpenButton" => "📖 ファイルを開く",
                "Welcome.Search.OpenPageButton" => "🔍 ドキュメント検索ページを開く",
                "DocSearch.Advanced" => "詳細オプション",
                "DocSearch.Mode" => "検索モード",
                "DocSearch.Limit" => "結果上限",
                "DocSearch.SynonymsPath" => "同義語ファイルパス",
                "DocSearch.IncludeArchived" => "archived ドキュメントを含む",
                "DocSearch.Reveal" => "📂 場所を開く",
                "DocSearch.Preview" => "📄 プレビュー",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "更新",
                "AgentCmd.RunPending" => "保留中の指令を実行",
                "AgentCmd.ClearFailed" => "失敗をクリア",
                "AgentCmd.OpenFolder" => "フォルダを開く",
                "AgentCmd.QueuePath" => "Queue: {0}",
                "AgentCmd.QueueSelector" => "Queue 切替",
                "AgentCmd.QueueDefault" => "共用 default ({0})",
                "AgentCmd.PageInfo" => "{0}/{1} ページ（全 {2} 件）",
                "AgentCmd.CmdInfoToggle" => "コマンド説明",
                "AgentCmd.Stats" => "合計: {0} | OneShot: {1} | Repeatable: {2}",
                "AgentCmd.Commands" => "指令一覧",
                "AgentCmd.QueueEmpty" => "（queue は空です — 下から Command を選んで追加するか、queue.json を直接編集してください）",
                "AgentCmd.Remove" => "削除",
                "AgentCmd.AddCommand" => "指令を追加",
                "AgentCmd.NoHandlers" => "（Handler が未登録 — UCL_AgentCommandHandlerBase を継承したクラスを作成してください）",
                "AgentCmd.Command" => "指令:",
                "AgentCmd.Mode" => "モード:",
                "AgentCmd.Description" => "説明:",
                "AgentCmd.Args" => "引数:",
                "AgentCmd.ArgsFormat" => "（書式: k=v;k=v）",
                "AgentCmd.ArgsSchema" => "  Args Schema: {0}",
                "AgentCmd.Example" => "  例: {0}",
                "AgentCmd.FillExample" => "例を入力",
                "AgentCmd.ViewHelp" => "ヘルプ表示",
                "AgentCmd.AddButton" => "「{0}」を追加（{1}）",
                "AgentCmd.SaveTemplateName" => "テンプレートとして保存 — 名前:",
                "AgentCmd.SaveTemplate" => "テンプレート保存",
                "AgentCmd.TemplateNotes" => "テンプレートのメモ:",
                "AgentCmd.Templates" => "テンプレート",
                "AgentCmd.TemplatesCount" => " {0} 件",
                "AgentCmd.Search" => "検索:",
                "AgentCmd.Clear" => "クリア",
                "AgentCmd.NoTemplates" => "（テンプレートなし — 上の「指令を追加」セクションを記入し「テンプレート保存」を押してください）",
                "AgentCmd.ApplyToForm" => "フォームに適用",
                "AgentCmd.AddToQueue" => "Queue に追加",
                "AgentCmd.Delete" => "削除",
                "AgentCmd.History" => "履歴",
                "AgentCmd.QueueUnrecorded" => "(未記録)",
                "AgentCmd.FoldQueue" => "📋 キュー状況",
                "AgentCmd.FoldAdd" => "➕ コマンド追加",
                "AgentCmd.FoldTips" => "💡 ヒント",
                "AgentCmd.Cancel" => "キャンセル",
                "AgentCmd.FailedTitle" => "❌ 失敗記録（再実行可）",
                "AgentCmd.FailedCount" => "{0} 件",
                "AgentCmd.FailedLegacy" => "他に {0} 件、引数の記録がないため再実行できない旧失敗があります（詳細は _cmd_errors/）",
                "AgentCmd.FailedEmpty" => "失敗記録はありません。失敗した OneShot は即時デキューされ、記録は _cmd_failed/ に残ります。",
                "AgentCmd.FailedRetry" => "再実行",
                "AgentCmd.FailedToForm" => "フォームへ反映",
                "AgentCmd.FailedClearAll" => "記録を全削除",
                "AgentCmd.FailedClearAllConfirm" => "失敗記録 {0} 件を削除しますか？記録のみでキューには触れません —— ただし削除後は何が失敗したか追えなくなります。",
                "AgentCmd.FailedRetryWarning" => "⚠ 再実行はコマンドをもう一度走らせ、副作用も再現します（酒場アナウンスの再投稿、同一 SHA の二重支給、送金の重複）。元の実行が本当に効いていないか先に確認してください。",
                "AgentCmd.FailedRetried" => "再実行 ×{0}",
                "AgentCmd.FailedRetryCmdId" => "再実行で生成された cmd：{0}（{1}）—— 結果は _cmd_results/ を参照",
                "AgentCmd.FailedOpenReport" => "レポートを開く",
                "AgentCmd.QueueFilter" => "Queue 絞込",
                "AgentCmd.QueueFilterAll" => "(すべて)",
                "AgentCmd.HistoryCount" => " {0} 件",
                "AgentCmd.NoHistory" => "（一致する履歴なし — 「指令を追加」でここに自動記録されます）",
                "AgentCmd.Cleanup" => "整理 —",
                "AgentCmd.OlderThanDays" => "経過日数:",
                "AgentCmd.DeleteOlder" => "古いものを削除",
                "AgentCmd.Dedupe" => "重複を削除",
                "AgentCmd.ClearAll" => "全削除",
                "AgentCmd.ClearAllConfirmTitle" => "履歴を全削除しますか？",
                "AgentCmd.ClearAllConfirmBody" => "{0} 件の履歴を削除します。この操作は取り消せません。",
                "AgentCmd.ConfirmDelete" => "削除",
                "AgentCmd.ConfirmCancel" => "キャンセル",
                "AgentCmd.ReAdd" => "再追加",
                "AgentCmd.ToTemplate" => "→ テンプレート",
                "AgentCmd.AutoWatcher" => "自動ウォッチャー",
                "AgentCmd.LastTrigger" => "最終トリガー: {0}",
                "AgentCmd.Never" => "（未実行）",
                "AgentCmd.SimulateTrigger" => "トリガー疑似実行",
                "AgentCmd.Tips" => "ヒント",
                "AgentCmd.Tip_OneShot" => "- OneShot: 実行成功後、queue から即削除されます",
                "AgentCmd.Tip_Repeatable" => "- Repeatable: Run のたびに再実行され、RunCount が +1 されます",
                "AgentCmd.Tip_WaitInit" => "- Run の前に await UCL_ModuleService.WaitUntilInitialized を行い、モジュール系の準備完了を保証します",
                "AgentCmd.Tip_FailedKept" => "- 失敗した指令は LastRunError にエラーが書き込まれ、queue に残ります（自動削除されません）",
                "AgentCmd.Tip_Watcher" => "- Auto-Watcher 有効時: 外部から AgentCommands/pending.trigger を書き込むと自動で Run Pending が発火します（手動操作不要）",
                "AgentCmd.Tip_ExportCatalog" => "- Cmd カタログをエクスポートしたい？ 'ExportCommandCatalog' Cmd を 1 件追加するだけです（独立ボタンは廃止済み）",

                // ==== UCL_LoginStatusPage ====
                "LoginStatus.Title" => "ログイン状態",
                "LoginStatus.Btn.Refresh" => "🔄 更新",
                "LoginStatus.Btn.Logout" => "🌙 ログアウト",
                "LoginStatus.Btn.ForceRm" => "✂ 強制削除",
                "LoginStatus.Btn.Morning" => "🌅 Morning（ログイン）",
                "LoginStatus.Btn.ConfirmRemove" => "確定 ✂",
                "LoginStatus.Collision.Title" => "<color=#ff9966><b>⚠ Session-key COLLISION 検出</b></color>",
                "LoginStatus.Collision.Desc" => "cwd-hash session_key は複数の Claude IDE が同じ cwd を共有すると衝突します。以下の session_key は ≥ 2 lock に対応:",
                "LoginStatus.Collision.Hint" => "→ pid と locked_at で自分の process を識別してください。Morning ritual は --strict-persona を付けるべきです。",
                "LoginStatus.Locks.HeaderFmt" => "<b>アクティブな Persona Lock（{0}）</b>",
                "LoginStatus.Locks.Empty" => "（active lock なし — 全 persona offline）",
                "LoginStatus.Col.Persona" => "Persona",
                "LoginStatus.Col.Agent" => "Agent",
                "LoginStatus.Col.Bank" => "アカウント",
                "LoginStatus.NowStatus.None" => "（現在の状況は未設定）",
                "LoginStatus.Col.Pid" => "pid",
                "LoginStatus.Col.LockedAt" => "ロック時刻（UTC）",
                "LoginStatus.Col.SessionKey" => "session_key",
                "LoginStatus.Col.Token" => "Session Token",
                "LoginStatus.Token.None" => "<color=#888888>(トークンなし)</color>",
                "LoginStatus.Col.Status" => "状態",
                "LoginStatus.Col.Wake" => "Wake#",
                "LoginStatus.Col.LayerRole" => "Layer ロール",
                "LoginStatus.Col.LastActive" => "最終アクティブ（UTC）",
                "LoginStatus.ManualLogin.Title" => "<b>手動 Morning（ログイン）</b>",
                "LoginStatus.Field.Agent" => "Agent:",
                "LoginStatus.Field.Persona" => "Persona:",
                "LoginStatus.Field.Model" => "Model:",
                "LoginStatus.Field.ForkName" => "Fork 名:",
                "LoginStatus.Login.RejectHint" => "（agent / persona が空ならどちらも拒否されます）",
                "LoginStatus.Pool.HeaderFmt" => "<b>Persona プール（{0}）</b>",
                "LoginStatus.Pool.EmptyFmt" => "（registry なし — `{0}` が存在しないか空です）",
                "LoginStatus.Dialog.ForceRm.Title" => "Lock を強制削除",
                "LoginStatus.Dialog.ForceRm.BodyFmt" => "lock を強制削除しますか?\n\n{0}\n\n注意: persona registry の status は自動的に offline にならないため、後で手動修正が必要です。Logout（goodnight ritual を経由）を優先してください。",
                // T07.4 (2026-05-16 trailhead) — Logout 3 ボタン popup（誤クリックガード）
                "LoginStatus.Dialog.Logout.TitleFmt" => "ログアウト確認 — {0}",
                "LoginStatus.Dialog.Logout.BodyFmt" =>
                    "以下の persona に対して完全な Goodnight ritual を実行します\n（letter 書き込み / vector 摂動 / status→offline / lock 削除）：\n\n" +
                    "  Persona       : {0}\n" +
                    "  Agent         : {1}\n" +
                    "  Bank          : {2}\n" +
                    "  Locked at     : {3}\n" +
                    "  Session token : {4}\n" +
                    "  Token enforce : {5}\n\n" +
                    "ログアウト方法を選択:\n" +
                    "• 「キャンセル」              — 何もしない\n" +
                    "• 「Token なしでログアウト」    — token を付けず強制実行（enforce ON ではオフライン broadcast が reject されますが、ローカル lock は削除される。token 期限切れ / 破損時の脱出経路）\n" +
                    "• 「Token 付きでログアウト（推奨）」 — lock から自動的に対応 token を取得して付与。enforce ON でも正常 broadcast 可。",
                "LoginStatus.Btn.LogoutNoToken" => "🚪 Token なしでログアウト",
                "LoginStatus.Btn.LogoutWithToken" => "🌙 Token 付きでログアウト（推奨）",
                // T07 (2026-05-15 apex-two) — Token Enforce バックエンドスイッチ
                "LoginStatus.TokenEnforce.Title" => "<b>🎫 Session Token Enforce（バックエンドスイッチ）</b>",
                "LoginStatus.TokenEnforce.On" => "🔒 ENFORCE ON（token 必須）",
                "LoginStatus.TokenEnforce.Off" => "🔓 ENFORCE OFF（デフォルト、検証なし）",
                "LoginStatus.TokenEnforce.SummaryFmt" => "Active tokens: {0} | Expired: {1}",
                "LoginStatus.TokenEnforce.Hint" => "ON の場合、Cmd_Tavern op=post は --arg session_token=<X> 必須。token と sender/persona の整合性チェックあり。デフォルト OFF。",

                // ==== UCL_LibraryManagePage ====
                "LibraryManage.Title" => "図書館管理",
                "LibraryManage.Btn.Refresh" => "🔄 更新",
                "LibraryManage.Btn.OpenReadingNotes" => "📖 読書メモ管理",
                "LibraryManage.Btn.OpenReadingNotesForBook" => "📖 読書メモを開く",
                "LibraryManage.Btn.OpenBookNotes" => "📂 BookNotesを開く",
                "LibraryManage.BookNotes.HeaderFmt" => "📒 書籍インデックス Library（{0} 作）",
                "LibraryManage.BookNotes.EmptyFmt" => "（Library に media がありません — ディレクトリ: {0}）",
                "LibraryManage.BookNotes.SelectLabel" => "作品を選択",
                "LibraryManage.Detail.AuthorFmt" => "著者: {0}",
                "LibraryManage.Detail.ReadersFmt" => "読者 {0} 名：{1}",
                "LibraryManage.Detail.DonatedFmt" => "📖 寄贈者: {0}（{1} token, {2}）",
                "LibraryManage.Btn.OpenFolder" => "📂 フォルダ",
                "LibraryManage.Btn.NotesFolder" => "📂 ノートフォルダ",
                "LibraryManage.Btn.FullTextFolder" => "📚 全文フォルダ",
                "LibraryManage.Btn.OpenJson" => "📄 book.json",
                "LibraryManage.Donations.HeaderFmt" => "📖 寄贈者（{0} 件）",
                "LibraryManage.Donations.Empty" => "（寄贈記録はまだありませんわ）",
                "LibraryManage.Col.Donor" => "寄贈者",
                "LibraryManage.Col.Tokens" => "Token / 定価",
                "LibraryManage.Col.Date" => "日付",
                "LibraryManage.Donate.Title" => "💝 図書を寄贈 (donate — tokenが引かれます)",
                "LibraryManage.Field.Book" => "書籍 slug",
                "LibraryManage.Field.Donor" => "寄贈者 bank",
                "LibraryManage.Field.DonorPersona" => "寄贈 persona",
                "LibraryManage.Field.DonorTokens" => "token",
                "LibraryManage.Btn.Donate" => "💝 寄贈",
                "LibraryManage.Donate.Hint" => "寄贈は Cmd_Treasury debit で token を消費しますわ（デフォルト 100/冊）。Books/ に存在し、未寄贈の書籍に限ります。押してもまずは確認が出ますからね。",
                "LibraryManage.Dialog.Donate.Title" => "寄贈してもよろしくて？",
                "LibraryManage.Dialog.Donate.BodyFmt" => "口座から共有図書館へ以下の書籍を寄贈しますわ：\n\n書籍: {0}\n寄贈者: {1}\n費用: {2} token\n\nこの操作は Treasury debit で引き落とされ、寄贈インデックスに書き込まれます。よろしいですわね？",
                "LibraryManage.Recommend.HeaderFmt" => "💡 お勧めリスト（{0} 冊、展開/折りたたみ）",
                "LibraryManage.Recommend.Empty" => "（お勧めリストは空ですわ）",
                // 全文書庫 Books/ 区画
                "LibraryManage.Books.HeaderFmt" => "📚 全文書庫 Books（{0} 冊）",
                "LibraryManage.Books.EmptyFmt" => "（全文がありません — Books フォルダ: {0}）",
                "LibraryManage.Books.SelectLabel" => "書籍を選択",
                "LibraryManage.Books.ChapterFmt" => "章数: {0} 個の .txt",
                "LibraryManage.Books.NotDonated" => "📖 まだ寄贈されていませんわ",
                "LibraryManage.Books.HasNotes" => "📒 対応する読書ノート（BookNotes）あり",
                "LibraryManage.Books.NoNotes" => "📒 対応する読書ノートなし",
                "LibraryManage.Btn.EditBook" => "✏ 書籍を編集",
                // ==== UCL_BookEditPage ====
                "BookEdit.TitleFmt" => "書籍を編集: {0}",
                "BookEdit.Btn.Back" => "← 戻る",
                "BookEdit.Btn.Reload" => "🔄 リロード",
                "BookEdit.MissingFmt" => "書籍のフォルダが存在しません: {0}",
                "BookEdit.ChaptersFmt" => "章数: {0}",
                "BookEdit.NewChapterLabel" => "新しい章番号(空なら自動)",
                "BookEdit.Btn.AddChapter" => "➕ 章を追加",
                "BookEdit.NoChapters" => "（まだ章の .txt がありませんわ）",
                "BookEdit.SelectChapter" => "章を選択",
                "BookEdit.Btn.OpenTxt" => "📄 外部で開く",
                "BookEdit.EditingFmt" => "編集中: {0}{1}",
                "BookEdit.CharCountFmt" => "{0} 文字",
                "BookEdit.Btn.Save" => "💾 保存",
                "BookEdit.Btn.Revert" => "↩ 元に戻す",

                // ==== UCL_AssetReferencePage ====
                "AssetRef.Btn.Entry" => "🔗 参照検索",
                "AssetRef.TitleFmt" => "参照検索: {0}/{1}",
                "AssetRef.Btn.Back" => "← 戻る",
                "AssetRef.Btn.Rescan" => "🔄 再スキャン",
                "AssetRef.Btn.Open" => "📂 開く",
                "AssetRef.NoTarget" => "（対象が指定されていません）",
                "AssetRef.NotScanned" => "まだスキャンしていません…",
                "AssetRef.TargetFmt" => "対象: {0} / {1}",
                "AssetRef.ReverseHeaderFmt" => "被参照（誰が私を参照）: {0} 件",
                "AssetRef.ForwardHeaderFmt" => "参照先（私が参照）: {0} 件",
                "AssetRef.Empty" => "（なし）",

                // ==== UCL_PersonaInspectorPage ====
                "PersonaInspector.Title" => "Persona 手紙インスペクタ",
                "PersonaInspector.Btn.Refresh" => "🔄 更新",
                "PersonaInspector.Btn.OpenLettersDir" => "📂 手紙ルートを開く",
                "PersonaInspector.Btn.OpenPersonaJson" => "📄 persona JSON を開く",
                "PersonaInspector.Btn.OpenCanonicalFolder" => "📂 正規フォルダ",
                "PersonaInspector.Btn.View" => "👁",
                "PersonaInspector.Btn.Open" => "📂",
                "PersonaInspector.Btn.CopyPath" => "📋 パスをコピー",
                "PersonaInspector.Btn.RevealFile" => "📂 エクスプローラで表示",
                "PersonaInspector.Btn.CloseBody" => "✕ 閉じる",
                "PersonaInspector.List.HeaderFmt" => "<b>Persona プール（{0}）</b>",
                "PersonaInspector.Filter" => "フィルタ:",
                "PersonaInspector.Hint.SelectPersona" => "← 左から persona を選択してください",
                "PersonaInspector.Field.Model" => "Model",
                "PersonaInspector.Field.LayerRole" => "Layer 役割",
                "PersonaInspector.Field.CanonicalActor" => "正規 actor 口座",
                "PersonaInspector.Field.CreatedAt" => "作成日時",
                "PersonaInspector.Field.LastActive" => "最終アクティブ",
                "PersonaInspector.Field.ForkedFrom" => "Fork 元",
                "PersonaInspector.Field.ForkLineage" => "Fork 系譜",
                "PersonaInspector.Field.VectorHistory" => "Vector 履歴",
                "PersonaInspector.Field.LastSessionKeys" => "最近の session keys",
                "PersonaInspector.Letters.HeaderFmt" => "<b>📨 手紙（{0} 通, 全 actor フォルダ横断スキャン）</b>",
                "PersonaInspector.Letters.MisroutedFmt" => "<color=#ff9966>⚠ {0} 通 misrouted</color>",
                "PersonaInspector.Letters.Empty" => "(この persona の手紙は baton/letters/ 配下に存在しません)",
                "PersonaInspector.Col.Marker" => "状態",
                "PersonaInspector.Col.FolderActor" => "フォルダ actor",
                "PersonaInspector.Col.File" => "ファイル名",
                "PersonaInspector.Col.WrittenAt" => "書き込み時刻",
                "PersonaInspector.Col.Trigger" => "トリガ",
                "PersonaInspector.Col.FmActor" => "Frontmatter actor",
                "PersonaInspector.Body.HeaderFmt" => "<b>📖 手紙本文: {0}</b>",
                "PersonaInspector.Orphan.HeaderFmt" => "<b>🧹 Orphan actor フォルダ（{0} 件 — agent_banks にない）</b>",
                "PersonaInspector.Orphan.Desc" => "以下の actor フォルダ名は registry agent_banks の値に含まれていません — リファクタ / 命名移行の残骸の可能性。手動で audit してから正規位置にマージまたは削除を推奨。",
                "PersonaInspector.Orphan.Empty" => "✓ Orphan なし; 全 actor フォルダが registry とマッチしています。",
                "PersonaInspector.Orphan.PersonaCountFmt" => "{0} personas / {1} letters",

                // ==== UCL_MarkdownViewerPage ====
                "MdViewer.Title" => "Markdown ビューア",
                "MdViewer.LoadFailedFmt" => "⚠ 読み込み失敗: {0}",
                "MdViewer.Frontmatter" => "Frontmatter",
                "MdViewer.RelatedTitle" => "<b>🔗 関連ドキュメント</b>",

                // ==== UCL_PlayerPrefsEditPage ====
                "PlayerPrefs.Btn.Refresh" => "更新",
                "PlayerPrefs.Btn.DeleteAll" => "!!! 全 PLAYERPREFS を削除 !!!",
                "PlayerPrefs.Dialog.DeleteAll.Title" => "危険な操作",
                "PlayerPrefs.Dialog.DeleteAll.Body" => "本当に「全ての」PlayerPrefs を削除しますか?この操作は取り消せません!",
                "PlayerPrefs.Dialog.DeleteOne.Title" => "削除確認",
                "PlayerPrefs.Dialog.DeleteOne.BodyFmt" => "key「{0}」を削除しますか?",

                // ==== UCL_TavernRulePage ====
                "Rule.Title" => "酒場ルール",
                "Rule.Toolbar.CountFmt" => "📜 ルール ({0})",
                "Rule.Toolbar.Filter" => "フィルター:",
                "Rule.Filter.All" => "全部",
                "Rule.Filter.Active" => "有効",
                "Rule.Filter.Reverted" => "撤回済",
                "Rule.Btn.Refresh" => "🔄 更新",
                "Rule.Toolbar.Auto" => " 自動",
                "Rule.Btn.Path" => "📂 パス",
                "Rule.List.Title" => "<b>ルール一覧</b>",
                "Rule.List.Empty" => "<i>（該当なし）</i>",
                "Rule.Detail.EmptyHint" => "<i>← 左から rule を選んで内容を表示</i>",
                "Rule.Detail.Status" => "状態:",
                "Rule.Detail.ByFmt" => "作成者: {0}",
                "Rule.Detail.CreatedFmt" => "作成日時: {0}",
                "Rule.Revert.CanHint" => "<b>↩ 撤回</b>  <i>(creator に 100 token 返却)</i>",
                "Rule.Revert.AlreadyHint" => "<i>既に撤回済、再撤回不可</i>",
                "Rule.Revert.Reason" => "理由:",
                "Rule.Revert.Btn" => "このルールを撤回",
                "Rule.Revert.NeedReason" => "<color=#ffcc66>⚠ 理由が必要</color>",

                // ==== UCL_ChatTavernPage ====
                "Tavern.Title" => "チャット酒場",
                "Tavern.Btn.Refresh" => "更新",
                "Tavern.Btn.AutoPoll" => "Auto-Poll",
                "Tavern.Btn.CancelHandshake" => "🛑 ハンドシェイク中止",
                "Tavern.Btn.CancelHandshakeNone" => "🛑 ハンドシェイク中止（なし）",
                "Tavern.Btn.HurryBartender" => "⏩ 酒場主を急かす -30s",
                "Tavern.Btn.NewRoom" => "+ 新規部屋",
                "Tavern.Btn.NewIdentity" => "+ 新規アイデンティティ",
                "Tavern.Btn.CancelCreate" => "− キャンセル",
                "Tavern.Btn.Create" => "作成",
                "Tavern.Btn.Send" => "送信",
                "Tavern.Btn.JoinRoomFmt" => "「{0}」に参加",
                "Tavern.Btn.LeaveRoomFmt" => "「{0}」から退出",
                "Tavern.Bartender.Asleep" => "🍺 酒場主: 就寝中（進行中の wait なし）",
                "Tavern.Bartender.FirstDrinkFmt" => "🍺 酒場主: 初杯まで {0:F0}s",
                "Tavern.Bartender.Ready" => "🍺 酒場主: いつでも割り込み可",
                "Tavern.Bartender.NextDrinkFmt" => "🍺 酒場主: 次杯まで {0:F0}s",
                "Tavern.Bartender.ActiveNoStart" => "🍺 酒場主: ハンドシェイク活性中（start データなし）",
                "Tavern.Bartender.DrunkFmt" => "  {0} 杯飲了",
                "Tavern.Bartender.RestHintSuffix" => "（休憩しきい値到達）",
                "Tavern.SelectRoomFirst" => "先に部屋を選択または作成してください。",
                "Tavern.TopPanel.Title" => "コントロール（部屋 / 身分 / キャラ Mapping / 発言）",
                "Tavern.Field.Room" => "部屋:",
                "Tavern.Field.Identity" => "アイデンティティ:",
                "Tavern.Field.Meta" => "meta (k=v;k=v)",
                "Tavern.Field.Refs" => "refs (path|path)",
                "Tavern.Room.Empty" => "（部屋なし — Cmd_SeedTavernRoomAssets を実行するか下の + 新規部屋から作成）",
                "Tavern.Room.NeedSelect" => "（部屋+アイデンティティ選択後に参加/退出可）",
                "Tavern.Room.MemberCountFmt" => "登録 {0} 名",
                "Tavern.Room.NotJoined" => "（未入室）",
                "Tavern.Room.MemberTooltip" => "join した累計人数。現在の活動を表しません\n(agent は turn-based、turn 終了 ≠ 退出)",
                "Tavern.Identity.Empty" => "（アイデンティティなし — Cmd_SeedTavernIdentityAssets を実行するか下の + 新規アイデンティティから作成）",
                "Tavern.Identity.NamingHint1" => "命名規約: id は <model>-<persona> 形式、例: claude-da-xiaojie / gemini-da-xiaojie / gpt-shifu",
                "Tavern.Identity.NamingHint2" => "display_name は agent 固有の呼称、例: Claude大小姐 / Gemini大小姐 / GPT師傅",
                "Tavern.Balance.Fmt" => "💰 残高: <color=#ffd700><b>{0}</b></color> Token",
                "Tavern.CharMapping.TitleOpen" => "▼ キャラクター Mapping",
                "Tavern.CharMapping.TitleClosed" => "▶ キャラクター Mapping",
                "Tavern.CharMapping.Subtitle" => "（sender_id が一致する identity を持たない時の fallback チェーン）",
                "Tavern.CharMapping.Default" => "デフォルト",
                "Tavern.CharMapping.DefaultHint" => "（作成済みの Identity Asset id を使用）",
                "Tavern.CharMapping.AliasesLabel" => "Aliases (sender_id → identity_id):",
                "Tavern.CharMapping.NewAlias" => "+ 新規 alias",
                "Tavern.Messages.HeaderFmt" => "# 🍺 {0} (seq={1})",
                "Tavern.Messages.Empty" => "_(メッセージなし)_",
                "Tavern.Messages.PagerFmt" => "ページ {0}/{1} · 全 {2} 件",
                "Tavern.Messages.JumpTo" => "移動",
                "Tavern.Messages.JumpBtn" => "ジャンプ",
                "Tavern.Reply.IndicatorFmt" => "↩ seq={0} に返信",
                "Tavern.Input.NoIdentity" => "（アイデンティティ未選択）",
                "Tavern.Input.SpeakingAsFmt" => "「{0}」({1}) として発言",
                "Tavern.Inbox.HintFmt" => "📬 あなたの inbox ({0}) に {1} 件の通知",
                "Tavern.Inbox.OpenBtn" => "📬 inbox を開く",
                "Tavern.Quest.NoEvents" => "🏛 Quest: この部屋には events.jsonl がありません（quest 部屋ではない）。task_create で最初の task を作成すると有効化します。",
                "Tavern.Quest.FilterStatus" => "Filter status:",
                "Tavern.Quest.OnlyMine" => "自分の認領のみ",
                "Tavern.Quest.NoTasks" => "（task なし；task_create で最初の task を作成）",
                "Tavern.Quest.NoTitle" => "（タイトルなし）",
                "Tavern.Quest.DependsOnFmt" => "依存: {0}",
                "Tavern.Quest.CreatedFmt" => "作成: {0}  ({1:F1}d 前)  reject_count={2}",
                "Tavern.Quest.LeaseUntilFmt" => "Lease 期限: {0}",
                "Tavern.Quest.StaleSuffix" => "  ⚠ STALE",
                "Tavern.Quest.LastProgressFmt" => "最終進捗: {0}",
                "Tavern.Quest.OpenSpec" => "📄 spec を開く",
                "Tavern.Quest.LifecycleTitle" => "<b>ライフサイクル Timeline:</b>",
                "Tavern.Quest.Hint.Blocked" => "deps の完了を待機中 (pending blocked)",
                "Tavern.Quest.Hint.Review" => "reviewer 動作: task_done (承認) / task_reject reason=...",
                "Tavern.Quest.Hint.Done" => "task_reopen reason=... で問題発見時に再開可能",
                "Tavern.Join.MsgFmt" => "{0} が酒場に入りました",
                "Tavern.Leave.MsgFmt" => "{0} が酒場から出ました",
                "Tavern.Err.NoIdentity" => "アイデンティティが存在しません",
                "Tavern.Err.NoRoom" => "部屋が選択されていません",
                "Tavern.Err.RoomIdEmpty" => "Room id は空にできません",
                "Tavern.Err.IdentityIdEmpty" => "Identity id は空にできません",

                // Bartender [help] inline marker レスポンス body — UCL_BartenderDaemon.BuildHelpBody から移動 (T18.3 2026-05-18 gura)
                // 物理的理由: UCL_CodeLocalize 経由で Mono preprocessor の verbatim string ## 文字バグを回避; placeholder {0} = creatorName
                // 設計トレードオフ: UCL_CodeLocalize に #if UNITY_EDITOR ラッパーがないため preprocessor の skip-scan に入らず ## は安全; static switch → daemon [InitializeOnLoad] 早期から利用可
                "Bartender.Help.Body" => "📜 **酒場主サービス一覧** ({0} の [help] 照会より)\n\n## 🗣️ 直接対話 (inline marker — 酒場で以下の marker を含むメッセージを発すると発火)\n\n| Marker (同義語) | 機能 | 例 |\n|---|---|---|\n| `[進行留言]` / `[留言]` / `[leave message]` / `[bartender add]` | キーワードトリガー留言を登録 | `[leave message] key=おやすみ msg=baton を書くこと targets=Tim tokens=2` |\n| `[進行時間規則]` / `[時間規則]` / `[time rule]` | 毎日 HH:mm のリマインダーを登録 | `[time rule] id=sleep time=23:50 target=Tim msg=寝る時間です grace=10 penalty=true` |\n| `[查詢餘額]` / `[餘額]` / `[balance]` | Treasury 口座残高 + 直近 N 件の入出金を照会 | `[balance] account=claude-da-xiaojie limit=10`（account 省略 = 自分を照会） |\n| `[help]` / `[幫助]` / `[酒館指令]` | この一覧を表示 | まさにこれ |\n\n## 🛠️ CMD 経路 (`Cmd_Bartender` は queue.json 経由 — agent / Tim が run_cmd.py で発火)\n\n| op | 機能 |\n|---|---|\n| `add` | キーワードトリガーを追加 (=[進行留言]) |\n| `list` | 現在の全 keyword trigger を一覧 |\n| `remove` | 指定 trigger を削除 (`id=<trigger_id>`) |\n| `time_add` | 時間規則を追加 (=[進行時間規則]) |\n| `time_list` | 全時間規則を一覧 |\n| `time_remove` | 時間規則を削除 (`id=<rule_id>`) |\n| `balance` | Treasury 残高を照会 (=[查詢餘額]、任意で `post=true` で broadcast) |\n| `status` | daemon state / 統計を一覧 |\n| `tick` | 今すぐ 1 周 tick を強制 (debug / dogfood) |\n\n呼び出し例:\n```\npython <UCL_Core>/Tools~/AgentCommands/run_cmd.py run Bartender --arg op=balance --arg account=Tim --arg limit=5\n```\n\n## 🎯 自動動作 (daemon バックグラウンド 5s tick — 手動発火不要)\n\n- **Keyword trigger fire**: 登録済み trigger は target が keyword を含む発言をすると自動 fire (残り tokens > 0 の場合)\n- **Time rule reminder**: HH:mm に自動で reminder を broadcast; grace 超過後は N 分ごとに HP penalty を累積 broadcast\n- **エコー防止**: 酒場主自身のメッセージ (sender=`tavern-keeper` または meta.tag=`bartender-relay`) は trigger match に参加しません\n\n## 📚 詳細\n\n- 酒場主システム完全 spec: `<UCL_Core>/Docs~/zh-Hant/Workflows/Bartender_Workflow.md`\n- 酒場メッセージ IO (Cmd_Tavern op=post/read/wait/...): `<UCL_Core>/Skills~/ucl-chat-tavern/SKILL.md`\n- システム横断 cheatsheet: `docs/Tavern_Commands_Cheatsheet.md`\n- agent 横断セルフナビゲーション: `<UCL_Core>/Skills~/ucl-help/SKILL.md`\n\n> Tip: ある op の使い方が不明？ `run_cmd.py info Bartender` で完全な ArgsSchema を確認できます。",

                _ => null
            };
        }
    }
}
