
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_en(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "ReadOnly" => "Read-Only",
                "Module_ReadOnly_Banner" => "Read-Only (built-in reference) — to modify, click 'Fork to Editable Module'",
                "Fork_To_Editable" => "Fork to Editable Module",
                "Fork_NewID_Prompt" => "New Module ID",
                "Edit Modules" => "Edit Modules",
                "ToolBox.Title" => "Tool Box",
                "ToolBox.MenuButton" => "🧰 Open Tool Box",
                "ToolBox.Group.Git" => "🔀 Git / Commit",
                "ToolBox.Group.AgentOps" => "🧭 Agent Ops",
                "ToolBox.Group.Runtime" => "🖥 Models & Runtime",
                "ToolBox.Group.Docs" => "📖 Docs & Localization",
                "ToolBox.Group.Content" => "📚 Content & Libraries",
                "ToolBox.GitFlattenSync" => "Git Flatten Sync",
                "ToolBox.GitFlattenSync.Desc" => "Flatten a repo's submodules into plain files and sync them into another repo's working directory (source is read-only; destination gets files only — neither git is touched).",
                "ToolBox.GitSubmoduleSync" => "Git Submodule Sync",
                "ToolBox.GitSubmoduleSync.Desc" => "Batch checkout-default-branch / pull / push across all submodules — one status table shows who is detached or ahead, so branches stop drifting after submodule update.",
                "ToolBox.AutoCommit" => "Auto Commit",
                "ToolBox.AutoCommit.Desc" => "Groups machine-generated AgentCommands files (tavern messages / Treasury / runtime state) and commits each group on button press with auto-generated messages; ephemeral files are always excluded.",
                "ToolBox.LLMModelAdmin" => "Local LLM Models",
                "ToolBox.LLMModelAdmin.Desc" => "Manage local large language models (ollama): check environment status, install/uninstall from a curated catalog, and run a smoke test. Ships with the Qwen family (the sizes that fit under 6GB VRAM).",
                "ToolBox.DocSearch" => "Doc Search",
                "ToolBox.DocSearch.Desc" => "Instant fuzzy search across 200+ markdown docs (synonym expansion, current locale first).",
                "ToolBox.LocalizeEdit" => "Localize Edit",
                "ToolBox.LocalizeEdit.Desc" => "Edit the multi-language string tables in UCL_LocalizeAsset.",
                "ToolBox.ScreenStream" => "Screen Stream",
                "ToolBox.ScreenStream.Desc" => "Console for the screen recording / STT / OCR daemon (watch-along streams, media transcription).",
                "ToolBox.ProcessAdmin" => "Process Admin",
                "ToolBox.ProcessAdmin.Desc" => "Inspect and manage external processes spawned from C# (identity verified by PID + name + start time — prevents wrong kills and zombie pile-ups).",
                "ToolBox.TaskManager" => "Tasks & Projects",
                "ToolBox.TaskManager.Desc" => "Cross-agent task tickets (one file per task) — commitments others wait on become Tasks; personal accountability stays in the keys file. Closing is blocked while any blocker is open; in_progress goes stale after 14 days.",
                "ToolBox.Relationship" => "Relationship",
                "ToolBox.Relationship.Desc" => "Per-persona affinity as an event ledger — the score is recomputed from events, not stored.",
                "ToolBox.SessionAdmin" => "🗂 Session Admin",
                "ToolBox.SessionAdmin.Desc" => "Current sessions per persona (free time...). Marks stale ones that are still active past their end time.",
                "ToolBox.FreeTimeAdmin" => "🎲 Free Time Admin",
                "ToolBox.FreeTimeAdmin.Desc" => "Activity settings behind the dice roll (enabled / group / suggested minutes / special rule / how-to). Edits the activity md frontmatter in place — no override file.",
                "ToolBox.LibraryManage" => "Library Manager",
                "ToolBox.LibraryManage.Desc" => "Manage existing Books and library data.",
                "ToolBox.ReadingNotesManage" => "Reading Notes Manager",
                "ToolBox.ReadingNotesManage.Desc" => "Find manual Archive and new Library entry points by work title.",
                "ToolBox.SculptureViewer" => "3D Sculpture Viewer",
                "ToolBox.SculptureViewer.Desc" => "Render the shared 3D voxel space — one-click exhibit presets or manual region/lighting parameters.",
                "SculptureViewer.Title" => "3D Sculpture Viewer",
                "SculptureViewer.Exhibits" => "🏛 Exhibits (from exhibits.json)",
                "SculptureViewer.RenderExhibit" => "Render exhibit",
                "SculptureViewer.Reload" => "Reload",
                "SculptureViewer.RenderAll" => "Render full scene",
                "SculptureViewer.NoExhibit" => "(no registered exhibits — sculpt.py exhibit register)",
                "SculptureViewer.Manual" => "🔧 Manual view parameters",
                "SculptureViewer.RenderManual" => "Render with parameters",
                "Agent Commands" => "Agent Commands",
                "Playlist" => "Playlist",
                "UCL_ModulePlayListPage" => "Edit playlist",
                "Create new module" => "Create new module",
                "Module ID" => "Module ID",
                "EditModulewarning" => "The built-in module (e.g. Core) is read-only in direct-streaming (no-install) mode \nand can only be viewed for reference, not edited directly. \nTo modify it, open the module and click 'Fork to Editable Module' to create an editable copy. \nIf different modules contain content with the same ID, the later-loaded module overwrites the earlier one.",
                "EditType" => "Edit type",
                "UCL_ModuleEditType_Builtin" => "Builtin",
                "UCL_ModuleEditType_Runtime" => "Runtime",
                "UCL_ModuleEditType_Template" => "Template",
                "Save Config" => "Save Config",
                "Load Config" => "Load Config",
                "Open Module Folder" => "Open Module Folder",
                "ModuleService Config" => "ModuleService Config",
                "Loaded modules" => "Loaded modules",
                "Config" => "Config",
                "Current playlist" => "Current playlist",
                "Create new playlist" => "Create new playlist",
                "Load current playlist" => "Load current playlist",
                "ModulePlayListTip" => "To enable the module\nplease press the Edit Playlist button\nand add the module you want to enable to the playlist.",
                "UCL_ModulePlayListPageTip" => "Please select the playlist you want to edit\n or create a new module playlist.",
                "UCL_ModulePlayListPageSaveTip" => "After editing the playlist, please press \"Save\"\nTo apply the current playlist\nplease press \"Load current playlist\"",
                "UCL_CreateNewModulePageTip" => "Please avoid using 'pure numbers' for module IDs (e.g., 3387893998).\nSteam subscriptions use numbers as IDs.\nIf the ID is the same as a Steam subscription module, it will be overwritten.",
                "DeleteTargetDes" => "Delete \"{0}\"",
                "UCL_LocalizeAsset" => "Localize",
                "UCL_ModResourceAsset" => "ModResource",
                "UCL_LanguageCodeAsset" => "LanguageCode",
                "UCL_SteamWorkshopAsset" => "SteamWorkshop",
                "Module Content" => "Module Content",
                "Asset Type" => "Asset Type",
                "Open Folder" => "Open Folder",
                "SteamAPILangCode" => "SteamAPI LangCode",
                "EWorkshopFileType" => "Workshop File Types",
                "Visibility" => "Visibility",
                "Dependencies" => "Dependencies",
                "PublishedFileId" => "Published FileId",
                "ChangeLog" => "Change Log",
                "Create workshop item" => "Create workshop item",
                "Update item to workshop" => "Update item to workshop",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "Public",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "Community",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "Add modules to current playlist",
                "AddNewModulesToCurrentPlaylistContent" => "Would you like to add the newly subscribed modules {0}\nto the current playlist({1})?",
                "HideThisOption" => "Hide this option",
                "Asset Group" => "Asset Group",
                "Confirm" => "Confirm",
                "Cancel" => "Cancel",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "ReInstall",
                "ReInstallAlert" => "Reinstalling will delete all modules.\nDo you want to proceed with the reinstallation? \n(If the game is not functioning properly or won't start, you can try reinstalling it.)",
                "Edit" => "Edit",
                "Preview" => "Preview",
                "OpenFile" => "OpenFile",
                "UCL_LocalizeEditPage" => "LocalizeEditPage",
                "UCL_LocalizeEditPage_Language" => "Language",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "(No UCL_LanguageCodeAsset registered)",
                "UCL_LocalizeEditPage_Current" => "Current:",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key (CurLangKey)",
                "UCL_LocalizeEditPage_Key" => "Key:",
                "UCL_LocalizeEditPage_ApplyPersist" => "Apply (Persist)",
                "UCL_LocalizeEditPage_Reset" => "Reset",
                "UCL_LocalizeEditPage_ClearOverride" => "Clear Persisted Override",
                "UCL_LocalizeEditPage_OverrideExists" => "  (override exists in UCL_ConfigAsset)",
                "UCL_LocalizeEditPage_UsingDefault" => "  (using default)",
                "UCL_LocalizeEditPage_DefaultFmt" => "  Default: \"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 Apply persists to UCL_ConfigAsset/{0}.json, auto-loaded on next startup.",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ Code (session only): UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "Download",
                "Key" => "Key",
                "MoveElement" => "Move element",
                "SelectAssetTemplateDes" => "Select {0} asset template",
                "OpenModuleRootFolder" => "Open Module Folder",
                "OpenModuleInstallFolder" => "Open Install Folder",
                "CopyToClipboard" => "Copy to clipboard",
                "PasteFromClipboard" => "Paste from clipboard",
                "CopyDescriptionToClipboard" => "Copy to description clipboard",
                "Rename" => "Rename",
                "EditGroup" => "Edit Group",
                "ShowDeleteButton" => "Show Delete Button",
                "CreateFolder" => "Create Folder",
                "Delete" => "Delete",
                "CreateNew" => "Create New",
                "RefreshData" => "Refresh Data",
                "Save" => "Save",
                "Copy" => "Copy",
                "Paste" => "Paste",
                "Back" => "Back",
                "Close" => "Close",
                "Select" => "Select",
                "Search" => "Search",
                "Add" => "Add",
                "SetCount" => "Set Count",
                "SaveBeforeExit?" => "Save before exit?",
                "ExitWitoutSave" => "Exit without save",
                "UCL_SelectAsset" => "Select Asset",
                "UCL_CreateAsset" => "Create Asset",
                "UCL_SaveSuccess" => "Save Success!",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / Overview",
                "Welcome.Title" => "👋  Welcome to UCL_Core",
                "Welcome.Subtitle" => "Cross-project Unity foundation library  ·  Welcome page v{0}",
                "Welcome.IntroTitle" => "What is UCL_Core?",
                "Welcome.IntroBody" => "UCL_Core is a cross-project Unity foundation library providing core components: data assets (UCL_Asset), module system, localization, Editor Pages, and the Agent Command cross-process system.\nWant to get started? Pick whichever feature card below matches what you're working on.",
                "Welcome.FeaturesTitle" => "Core features (click to open)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset System",
                "Welcome.Asset.Desc" => "JSON-serialized design assets (cards / items / monsters / ...) — Editor-side visual editing, cross-platform IO, SerializeReference polymorphism support.",
                "Welcome.Asset.Btn" => "Open Modules Editor",
                "Welcome.Localize.Title" => "🌐  Localization (string editing)",
                "Welcome.Localize.Desc" => "Edit translation strings, CurLangKey, PlayerPrefs key for each language. To just switch language, use the bar above — no need to enter this page.",
                "Welcome.Localize.Btn" => "Open Localize Editor",
                "Welcome.Lang.Label" => "🌐 Language:",

                "Welcome.CommandTable.Label" => "📋 Commands:",
                "Welcome.CommandTable.Desc" => "SOP reference guide matching natural language triggers to their corresponding workflows.",
                "Welcome.CommandTable.Btn" => "📄 Preview Command Table",

                "Welcome.Lang.NoneAvailable" => "(No UCL_LanguageCodeAsset found — please create language Asset first)",
                "Welcome.Lang.OpenEditor" => "Advanced…",
                "Welcome.Agent.Title" => "🤖  Agent Commands (agent ↔ Editor cross-process)",
                "Welcome.Agent.Desc" => "AI agent writes queue.json, Editor Watcher auto-executes — built-ins include ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat.",
                "Welcome.Agent.Btn" => "Open Agent Commands Page",
                "Welcome.Editor.Title" => "🪟  Editor Pages Framework",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — consistent IMGUI page stack with searchable dropdowns, HelpURL routing, TopBar customization.",
                "Welcome.Editor.Btn" => "PlayerPrefs Editor (sample)",
                "Welcome.DocBtn" => "📖 Docs",

                "Welcome.DocsTitle" => "📚 Documentation index",
                "Welcome.Docs.Index" => "UCL_Core docs index",
                "Welcome.Docs.Architecture" => "Agent Command Architecture",
                "Welcome.Docs.CreateCmd" => "Create Cmd SOP",
                "Welcome.Docs.Validate" => "Validate UCL_Asset format",
                "Welcome.Docs.CompileError" => "🔧 Compile Error Diagnosis Workflow",
                // Welcome page Skill entry card (small, routes to the standalone AgentSkillManager page)
                "Welcome.SkillEntry.Title" => "🧩  Agent Skill Management",
                "Welcome.SkillEntry.Desc" => "Extract UCL_Core workflows (commit / enter tavern / diagnose compile errors) into AI agent Skills — each agent (Claude Code / Cursor / Antigravity / Gemini) has its own install path, handled uniformly by the management page. Auto-opens on first Welcome.",
                "Welcome.SkillEntry.OpenBtn" => "🛠 Open Skill Manager",

                // Standalone UCL_AgentSkillManagerPage
                "AgentSkill.Title" => "🛠 Agent Skill Manager",
                "AgentSkill.Subtitle" => "Install UCL_Core workflows for each AI agent",
                "AgentSkill.ConceptTitle" => "Why this page?",
                "AgentSkill.ConceptBody" => "Each skill under UCL_Core/Skills~/ is a 'lazy-load workflow' — the agent only loads the full SOP when it sees a trigger word, sparing context otherwise. Each agent has its own path convention: Claude Code → .claude/skills/, Antigravity → .agents/rules/ (planned: Cursor → .cursor/rules/, Gemini). This page installs to all supported targets uniformly.",
                "AgentSkill.OneClick.Title" => "One-click install (Claude Code / Antigravity)",
                "AgentSkill.OneClick.Desc" => "Runs Tools~/install_skills.py --target <X> to copy all skills to the matching dst (Claude → .claude/skills/, Antigravity → .agents/rules/). Idempotent and re-runnable; locally modified files are detected and not overwritten.",
                "AgentSkill.Status.NotInstalled" => "⚠ Not installed — click the button below to install in one click",
                "AgentSkill.Status.Synced" => "✓ Installed and matches source content",
                "AgentSkill.Status.Stale" => "⚠ Installed content differs from source (source updated or local edits) — reinstall / force-sync recommended",
                "AgentSkill.Status.LegacyNoHash" => "⚠ Legacy marker has no source_hash field — reinstall once to refresh the comparison baseline",
                "AgentSkill.Status.UnknownHead" => "Installed but cannot determine UCL_Core HEAD (git not in PATH?)",
                "AgentSkill.Status.NoProjectRoot" => "Host project root not found (no .claude/ or .git/) — run Tools~/install_skills.py --project-root <path> manually",
                "AgentSkill.Status.NoUCLCore" => "UCL_Core path not found (UCL_EditorPath.CorePath is empty)",
                "AgentSkill.HostRoot" => "Project root: {0}",
                "AgentSkill.Btn.Install" => "🚀 Install",
                "AgentSkill.Btn.InstallAll" => "🚀 Install all targets",
                "AgentSkill.Btn.ForceSyncAll" => "⚡ Force-sync all (overwrite local changes)",
                "AgentSkill.Btn.ForceSyncAll.Synced" => "✅ All synced (force-rewrite still available)",
                "AgentSkill.SkippedWarn" => "⚠ Last install skipped {0} file(s) due to local changes; content not updated — use 'Reinstall' or 'Force-sync' to overwrite (see Console)",
                "AgentSkill.Btn.Sync" => "🔄 Sync to current version",
                "AgentSkill.Btn.Reinstall" => "🔁 Reinstall",
                "AgentSkill.Btn.Refresh" => "Refresh",
                "AgentSkill.Btn.Doc" => "📖 Skills~/README",
                "AgentSkill.Btn.ResetAck" => "Reset first-open",
                "AgentSkill.Matrix.Title" => "🎛 Per-Agent × Per-Skill toggle",
                "AgentSkill.Matrix.Body" => "Pick an agent from the dropdown to view/manage its per-skill install state. installed/drift are per-agent; disabled (UCL_SkillConfigAsset) is shared across agents:",
                "AgentSkill.Matrix.NoSource" => "(UCL_Core/Skills~/ source directory not found)",
                "AgentSkill.Matrix.Status.DisabledPendingRemove" => "🚫disabled·pending removal",
                "AgentSkill.Matrix.Status.Disabled" => "🚫disabled",
                "AgentSkill.Matrix.Status.NotInstalled" => "not installed",
                "AgentSkill.Matrix.Status.Drift" => "⚠changed",
                "AgentSkill.Matrix.Status.Synced" => "✓synced",
                "AgentSkill.Matrix.Btn.Enable" => "Enable",
                "AgentSkill.AckToggle" => " Never auto-open this page (even when skills update; still available from the menu)",
                "AgentSkill.LastChangesLabel" => "Last auto-popup reason — skill changes: {0}",
                "AgentSkill.AckVersionLabel" => "AcknowledgedVersion: {0}",
                "AgentSkill.NotSet" => "(unset)",


                "Welcome.AutoOpenToggle" => " Don't auto-open this page again (still available via UCL → Welcome menu)",
                "Welcome.ResetButton" => "Reset first-open (will pop once on next domain reload)",
                "Welcome.ResetLog" => "[UCL_Welcome] First-open state reset. Will display again on next domain reload.",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(unset)",
                "Welcome.Search.Title" => "🔍 Search Docs",
                "Welcome.Search.Button" => "Search",
                "Welcome.Search.Hint" => "Synonym expansion supported (reads Docs/_synonyms.txt) — e.g. searching 'items' will hit docs titled '道具'. Space-separate multiple terms (AND mode).",
                "Welcome.Search.NoResults" => "(no hits)",
                "Welcome.Search.ResultsCount" => "{0} hit(s) out of {1} scanned",
                "Welcome.Search.OpenButton" => "📖 Open",
                "Welcome.Search.OpenPageButton" => "🔍 Open Doc Search Page",
                "DocSearch.Advanced" => "Advanced options",
                "DocSearch.Mode" => "Search mode",
                "DocSearch.Limit" => "Result limit",
                "DocSearch.SynonymsPath" => "Synonyms path",
                "DocSearch.IncludeArchived" => "Include archived docs",
                "DocSearch.Reveal" => "📂 Reveal",
                "DocSearch.Preview" => "📄 Preview",

                // ==== UCL_AgentCommandsPage ====
                "AgentCmd.Refresh" => "Refresh",
                "AgentCmd.RunPending" => "Run Pending Commands",
                "AgentCmd.ClearFailed" => "Clear Failed",
                "AgentCmd.OpenFolder" => "Open Folder",
                "AgentCmd.QueuePath" => "Queue: {0}",
                "AgentCmd.QueueSelector" => "Queue",
                "AgentCmd.QueueDefault" => "shared default ({0})",
                "AgentCmd.PageInfo" => "Page {0}/{1} ({2} total)",
                "AgentCmd.CmdInfoToggle" => "Command Info",
                "AgentCmd.Stats" => "Total: {0} | OneShot: {1} | Repeatable: {2}",
                "AgentCmd.Commands" => "Commands",
                "AgentCmd.QueueEmpty" => "(queue is empty — pick a Command below to add, or edit queue.json directly)",
                "AgentCmd.Remove" => "Remove",
                "AgentCmd.AddCommand" => "Add Command",
                "AgentCmd.NoHandlers" => "(no Handler registered — write a class extending UCL_AgentCommandHandlerBase)",
                "AgentCmd.Command" => "Command:",
                "AgentCmd.Mode" => "Mode:",
                "AgentCmd.Description" => "Description:",
                "AgentCmd.Args" => "Args:",
                "AgentCmd.ArgsFormat" => "(format: k=v;k=v)",
                "AgentCmd.ArgsSchema" => "  Args Schema: {0}",
                "AgentCmd.Example" => "  Example: {0}",
                "AgentCmd.FillExample" => "Fill Example",
                "AgentCmd.ViewHelp" => "View Help",
                "AgentCmd.AddButton" => "Add '{0}' ({1})",
                "AgentCmd.SaveTemplateName" => "Save as Template — Name:",
                "AgentCmd.SaveTemplate" => "Save Template",
                "AgentCmd.TemplateNotes" => "Template Notes:",
                "AgentCmd.Templates" => "Templates",
                "AgentCmd.TemplatesCount" => " {0} saved",
                "AgentCmd.Search" => "Search:",
                "AgentCmd.Clear" => "Clear",
                "AgentCmd.NoTemplates" => "(no templates — fill the Add Command form above and press Save Template)",
                "AgentCmd.ApplyToForm" => "Apply to Form",
                "AgentCmd.AddToQueue" => "Add to Queue",
                "AgentCmd.Delete" => "Delete",
                "AgentCmd.History" => "History",
                "AgentCmd.QueueUnrecorded" => "(not recorded)",
                "AgentCmd.FoldQueue" => "📋 Queue status",
                "AgentCmd.FoldAdd" => "➕ Add command",
                "AgentCmd.FoldTips" => "💡 Tips",
                "AgentCmd.Cancel" => "Cancel",
                "AgentCmd.FailedTitle" => "❌ Failed commands (re-runnable)",
                "AgentCmd.FailedCount" => "{0} entr(y/ies)",
                "AgentCmd.FailedLegacy" => "{0} older failure(s) have no recorded args and cannot be re-run (see _cmd_errors/)",
                "AgentCmd.FailedEmpty" => "No failure records. Failed OneShot commands are dequeued immediately; records land in _cmd_failed/.",
                "AgentCmd.FailedRetry" => "Re-run",
                "AgentCmd.FailedToForm" => "Load into form",
                "AgentCmd.FailedClearAll" => "Clear all records",
                "AgentCmd.FailedClearAllConfirm" => "Delete {0} failure record(s)? Records only — no queue is touched. But afterwards there is no way to tell what failed.",
                "AgentCmd.FailedRetryWarning" => "⚠ Re-running executes the command again and replays its side effects (tavern announcements re-posted, the same SHA paid twice, transfers repeated). Confirm the original really did not take effect first.",
                "AgentCmd.FailedRetried" => "re-run ×{0}",
                "AgentCmd.FailedRetryCmdId" => "Re-run produced cmd {0} ({1}) — verdict in _cmd_results/",
                "AgentCmd.FailedOpenReport" => "Open report",
                "AgentCmd.QueueFilter" => "Queue filter",
                "AgentCmd.QueueFilterAll" => "(all)",
                "AgentCmd.HistoryCount" => " {0} entries",
                "AgentCmd.NoHistory" => "(no matching history — entries are recorded automatically when you Add a command)",
                "AgentCmd.Cleanup" => "Cleanup —",
                "AgentCmd.OlderThanDays" => "Older than (days):",
                "AgentCmd.DeleteOlder" => "Delete Older",
                "AgentCmd.Dedupe" => "Dedupe",
                "AgentCmd.ClearAll" => "Clear All",
                "AgentCmd.ClearAllConfirmTitle" => "Clear All History?",
                "AgentCmd.ClearAllConfirmBody" => "Delete all {0} history entries? This cannot be undone.",
                "AgentCmd.ConfirmDelete" => "Delete",
                "AgentCmd.ConfirmCancel" => "Cancel",
                "AgentCmd.ReAdd" => "Re-Add",
                "AgentCmd.ToTemplate" => "→ Template",
                "AgentCmd.AutoWatcher" => "Auto-Watcher",
                "AgentCmd.LastTrigger" => "Last trigger: {0}",
                "AgentCmd.Never" => "(never)",
                "AgentCmd.SimulateTrigger" => "Simulate Trigger",
                "AgentCmd.Tips" => "Tips",
                "AgentCmd.Tip_OneShot" => "- OneShot: removed from queue immediately after a successful run",
                "AgentCmd.Tip_Repeatable" => "- Repeatable: runs every time Run is pressed, incrementing RunCount each time",
                "AgentCmd.Tip_WaitInit" => "- Before running, awaits UCL_ModuleService.WaitUntilInitialized — ensures the module system is ready",
                "AgentCmd.Tip_FailedKept" => "- Failed commands keep their error in LastRunError and stay in the queue (they are not auto-removed)",
                "AgentCmd.Tip_Watcher" => "- With Auto-Watcher enabled: an external write to AgentCommands/pending.trigger auto-fires Run Pending (no manual click needed)",
                "AgentCmd.Tip_ExportCatalog" => "- Want to export the Cmd catalog? Add an 'ExportCommandCatalog' Cmd entry (no separate button)",

                // ==== UCL_LoginStatusPage ====
                "LoginStatus.Title" => "Login Status",
                "LoginStatus.Btn.Refresh" => "🔄 Refresh",
                "LoginStatus.Btn.Logout" => "🌙 Logout",
                "LoginStatus.Btn.ForceRm" => "✂ Force RM",
                "LoginStatus.Btn.Morning" => "🌅 Morning (Login)",
                "LoginStatus.Btn.ConfirmRemove" => "Confirm ✂",
                "LoginStatus.Collision.Title" => "<color=#ff9966><b>⚠ Session-key COLLISION detected</b></color>",
                "LoginStatus.Collision.Desc" => "cwd-hash session_key collides when multiple Claude IDEs share the same cwd. The following session_keys map to ≥ 2 locks:",
                "LoginStatus.Collision.Hint" => "→ Use pid + locked_at to identify your own process. Morning ritual should pass --strict-persona.",
                "LoginStatus.Locks.HeaderFmt" => "<b>Active Persona Locks ({0})</b>",
                "LoginStatus.Locks.Empty" => "(no active lock — all personas offline)",
                "LoginStatus.Col.Persona" => "Persona",
                "LoginStatus.Col.Agent" => "Agent",
                "LoginStatus.Col.Bank" => "Bank",
                "LoginStatus.NowStatus.None" => "(no current status set)",
                "LoginStatus.Col.Pid" => "pid",
                "LoginStatus.Col.LockedAt" => "locked_at (UTC)",
                "LoginStatus.Col.SessionKey" => "session_key",
                "LoginStatus.Col.Token" => "Session Token",
                "LoginStatus.Token.None" => "<color=#888888>(no token)</color>",
                "LoginStatus.Col.Status" => "Status",
                "LoginStatus.Col.Wake" => "Wake#",
                "LoginStatus.Col.LayerRole" => "Layer Role",
                "LoginStatus.Col.LastActive" => "Last Active (UTC)",
                "LoginStatus.ManualLogin.Title" => "<b>Manual Morning (Login)</b>",
                "LoginStatus.Field.Agent" => "Agent:",
                "LoginStatus.Field.Persona" => "Persona:",
                "LoginStatus.Field.Model" => "Model:",
                "LoginStatus.Field.ForkName" => "Fork name:",
                "LoginStatus.Login.RejectHint" => "(empty agent → reject; empty persona → reject)",
                "LoginStatus.Pool.HeaderFmt" => "<b>Persona Pool ({0})</b>",
                "LoginStatus.Pool.EmptyFmt" => "(no registry — `{0}` does not exist or is empty)",
                "LoginStatus.Dialog.ForceRm.Title" => "Force Remove Lock",
                "LoginStatus.Dialog.ForceRm.BodyFmt" => "Confirm force-delete lock?\n\n{0}\n\nNote: persona registry status will NOT auto-change to offline; manual fixup required. Prefer Logout (which runs the goodnight ritual).",
                // T07.4 (2026-05-16 trailhead) — Logout 3-button popup (mis-click guard)
                "LoginStatus.Dialog.Logout.TitleFmt" => "Confirm Logout — {0}",
                "LoginStatus.Dialog.Logout.BodyFmt" =>
                    "About to run the full Goodnight ritual on the following persona\n(write letter / perturb vector / status→offline / remove lock):\n\n" +
                    "  Persona       : {0}\n" +
                    "  Agent         : {1}\n" +
                    "  Bank          : {2}\n" +
                    "  Locked at     : {3}\n" +
                    "  Session token : {4}\n" +
                    "  Token enforce : {5}\n\n" +
                    "Choose logout mode:\n" +
                    "• \"Cancel\"                       — do nothing\n" +
                    "• \"Logout without Token\"          — force no token attached (with enforce ON the offline broadcast will be rejected, but the local lock is still cleared; useful as an escape hatch when the token has expired / become corrupt)\n" +
                    "• \"Logout with Token (recommended)\" — auto-fetch the matching token from the lock; works under enforce ON.",
                "LoginStatus.Btn.LogoutNoToken" => "🚪 Logout w/o Token",
                "LoginStatus.Btn.LogoutWithToken" => "🌙 Logout w/ Token (Recommended)",
                // T07 (2026-05-15 apex-two) — Token Enforce backend switch
                "LoginStatus.TokenEnforce.Title" => "<b>🎫 Session Token Enforce (Backend Switch)</b>",
                "LoginStatus.TokenEnforce.On" => "🔒 ENFORCE ON (token required)",
                "LoginStatus.TokenEnforce.Off" => "🔓 ENFORCE OFF (default, no check)",
                "LoginStatus.TokenEnforce.SummaryFmt" => "Active tokens: {0} | Expired: {1}",
                "LoginStatus.TokenEnforce.Hint" => "When ON, Cmd_Tavern op=post requires --arg session_token=<X>; token must match sender/persona. Default OFF preserves legacy behavior.",

                // ==== UCL_LibraryManagePage ====
                "LibraryManage.Title" => "Library Manager",
                "LibraryManage.Btn.Refresh" => "🔄 Refresh",
                "LibraryManage.Btn.OpenReadingNotes" => "📖 Reading Notes",
                "LibraryManage.Btn.OpenReadingNotesForBook" => "📖 Open Reading Notes",
                "LibraryManage.Btn.OpenBookNotes" => "📂 Open BookNotes",
                "LibraryManage.BookNotes.HeaderFmt" => "📒 Library Index ({0})",
                "LibraryManage.BookNotes.EmptyFmt" => "(No media in Library — dir: {0})",
                "LibraryManage.BookNotes.SelectLabel" => "Select work",
                "LibraryManage.Detail.AuthorFmt" => "Author: {0}",
                "LibraryManage.Detail.ReadersFmt" => "Readers ({0}): {1}",
                "LibraryManage.Detail.DonatedFmt" => "📖 Donor: {0} ({1} token, {2})",
                "LibraryManage.Btn.OpenFolder" => "📂 Folder",
                "LibraryManage.Btn.NotesFolder" => "📂 Notes folder",
                "LibraryManage.Btn.FullTextFolder" => "📚 Full-text folder",
                "LibraryManage.Btn.OpenJson" => "📄 book.json",
                "LibraryManage.Donations.HeaderFmt" => "📖 Donors ({0})",
                "LibraryManage.Donations.Empty" => "(No donations yet)",
                "LibraryManage.Col.Donor" => "Donor",
                "LibraryManage.Col.Tokens" => "Token / Price",
                "LibraryManage.Col.Date" => "Date",
                "LibraryManage.Donate.Title" => "💝 Donate Book (donate — spends token)",
                "LibraryManage.Field.Book" => "Book slug",
                "LibraryManage.Field.Donor" => "Donor bank",
                "LibraryManage.Field.DonorPersona" => "Donor persona",
                "LibraryManage.Field.DonorTokens" => "token",
                "LibraryManage.Btn.Donate" => "💝 Donate",
                "LibraryManage.Donate.Hint" => "Donation debits token via Cmd_Treasury (default 100/book). Book must exist in Books/ and not already donated. Confirms first.",
                "LibraryManage.Dialog.Donate.Title" => "Confirm book donation?",
                "LibraryManage.Dialog.Donate.BodyFmt" => "Donate the following book into the shared library:\n\nBook: {0}\nDonor: {1}\nCost: {2} token\n\nThis debits via Treasury and writes the donation index. Proceed?",
                "LibraryManage.Recommend.HeaderFmt" => "💡 Recommendations ({0}, click to expand)",
                "LibraryManage.Recommend.Empty" => "(Recommendation list empty)",
                // Full-text Books/ section
                "LibraryManage.Books.HeaderFmt" => "📚 Full-text Books ({0})",
                "LibraryManage.Books.EmptyFmt" => "(No full text — Books dir: {0})",
                "LibraryManage.Books.SelectLabel" => "Select book",
                "LibraryManage.Books.ChapterFmt" => "Chapters: {0} .txt",
                "LibraryManage.Books.NotDonated" => "📖 Not yet donated",
                "LibraryManage.Books.HasNotes" => "📒 Has matching BookNotes",
                "LibraryManage.Books.NoNotes" => "📒 No matching BookNotes",
                "LibraryManage.Btn.EditBook" => "✏ Edit book",
                // ==== UCL_BookEditPage ====
                "BookEdit.TitleFmt" => "Edit Book: {0}",
                "BookEdit.Btn.Back" => "← Back",
                "BookEdit.Btn.Reload" => "🔄 Reload",
                "BookEdit.MissingFmt" => "Book dir not found: {0}",
                "BookEdit.ChaptersFmt" => "Chapters: {0}",
                "BookEdit.NewChapterLabel" => "New ch # (blank=auto)",
                "BookEdit.Btn.AddChapter" => "➕ Add chapter",
                "BookEdit.NoChapters" => "(No .txt chapters yet)",
                "BookEdit.SelectChapter" => "Select chapter",
                "BookEdit.Btn.OpenTxt" => "📄 Open external",
                "BookEdit.EditingFmt" => "Editing: {0}{1}",
                "BookEdit.CharCountFmt" => "{0} chars",
                "BookEdit.Btn.Save" => "💾 Save",
                "BookEdit.Btn.Revert" => "↩ Revert",

                // ==== UCL_AssetReferencePage ====
                "AssetRef.Btn.Entry" => "🔗 References",
                "AssetRef.TitleFmt" => "References: {0}/{1}",
                "AssetRef.Btn.Back" => "← Back",
                "AssetRef.Btn.Rescan" => "🔄 Rescan",
                "AssetRef.Btn.Open" => "📂 Open",
                "AssetRef.NoTarget" => "(No target specified)",
                "AssetRef.NotScanned" => "Not scanned yet…",
                "AssetRef.TargetFmt" => "Target: {0} / {1}",
                "AssetRef.ReverseHeaderFmt" => "Referenced By (who references me): {0}",
                "AssetRef.ForwardHeaderFmt" => "References To (what I reference): {0}",
                "AssetRef.Empty" => "(none)",

                // ==== UCL_PersonaInspectorPage ====
                "PersonaInspector.Title" => "Persona Letter Inspector",
                "PersonaInspector.Btn.Refresh" => "🔄 Refresh",
                "PersonaInspector.Btn.OpenLettersDir" => "📂 Open letters root",
                "PersonaInspector.Btn.OpenPersonaJson" => "📄 Open persona JSON",
                "PersonaInspector.Btn.OpenCanonicalFolder" => "📂 Canonical folder",
                "PersonaInspector.Btn.View" => "👁",
                "PersonaInspector.Btn.Open" => "📂",
                "PersonaInspector.Btn.CopyPath" => "📋 Copy path",
                "PersonaInspector.Btn.RevealFile" => "📂 Reveal in Explorer",
                "PersonaInspector.Btn.CloseBody" => "✕ Close",
                "PersonaInspector.List.HeaderFmt" => "<b>Persona Pool ({0})</b>",
                "PersonaInspector.Filter" => "Filter:",
                "PersonaInspector.Hint.SelectPersona" => "← Pick a persona on the left to inspect",
                "PersonaInspector.Field.Model" => "Model",
                "PersonaInspector.Field.LayerRole" => "Layer role",
                "PersonaInspector.Field.CanonicalActor" => "Canonical actor",
                "PersonaInspector.Field.CreatedAt" => "Created at",
                "PersonaInspector.Field.LastActive" => "Last active",
                "PersonaInspector.Field.ForkedFrom" => "Forked from",
                "PersonaInspector.Field.ForkLineage" => "Fork lineage",
                "PersonaInspector.Field.VectorHistory" => "Vector history",
                "PersonaInspector.Field.LastSessionKeys" => "Recent session keys",
                "PersonaInspector.Letters.HeaderFmt" => "<b>📨 Letters ({0} found across all actor folders)</b>",
                "PersonaInspector.Letters.MisroutedFmt" => "<color=#ff9966>⚠ {0} misrouted</color>",
                "PersonaInspector.Letters.Empty" => "(no letters for this persona anywhere under baton/letters/)",
                "PersonaInspector.Col.Marker" => "Status",
                "PersonaInspector.Col.FolderActor" => "Folder actor",
                "PersonaInspector.Col.File" => "File",
                "PersonaInspector.Col.WrittenAt" => "Written at",
                "PersonaInspector.Col.Trigger" => "Trigger",
                "PersonaInspector.Col.FmActor" => "Frontmatter actor",
                "PersonaInspector.Body.HeaderFmt" => "<b>📖 Letter body: {0}</b>",
                "PersonaInspector.Orphan.HeaderFmt" => "<b>🧹 Orphan actor folders ({0} — not in agent_banks)</b>",
                "PersonaInspector.Orphan.Desc" => "Actor folder names below are not in registry agent_banks values — likely refactor / naming migration residue. Audit manually then merge or delete.",
                "PersonaInspector.Orphan.Empty" => "✓ No orphans; every actor folder maps to a registered agent.",
                "PersonaInspector.Orphan.PersonaCountFmt" => "{0} personas / {1} letters",

                // ==== UCL_MarkdownViewerPage ====
                "MdViewer.Title" => "Markdown Viewer",
                "MdViewer.LoadFailedFmt" => "⚠ Load failed: {0}",
                "MdViewer.Frontmatter" => "Frontmatter",
                "MdViewer.RelatedTitle" => "<b>🔗 Related Docs</b>",

                // ==== UCL_PlayerPrefsEditPage ====
                "PlayerPrefs.Btn.Refresh" => "Refresh",
                "PlayerPrefs.Btn.DeleteAll" => "!!! DELETE ALL PLAYERPREFS !!!",
                "PlayerPrefs.Dialog.DeleteAll.Title" => "DANGEROUS OPERATION",
                "PlayerPrefs.Dialog.DeleteAll.Body" => "Are you sure you want to delete ALL PlayerPrefs? This cannot be undone!",
                "PlayerPrefs.Dialog.DeleteOne.Title" => "Confirm Delete",
                "PlayerPrefs.Dialog.DeleteOne.BodyFmt" => "Are you sure you want to delete key '{0}'?",

                // ==== UCL_TavernRulePage ====
                "Rule.Title" => "Tavern Rules",
                "Rule.Toolbar.CountFmt" => "📜 Rules ({0})",
                "Rule.Toolbar.Filter" => "filter:",
                "Rule.Filter.All" => "all",
                "Rule.Filter.Active" => "active",
                "Rule.Filter.Reverted" => "reverted",
                "Rule.Btn.Refresh" => "🔄 Refresh",
                "Rule.Toolbar.Auto" => " auto",
                "Rule.Btn.Path" => "📂 Path",
                "Rule.List.Title" => "<b>Rule List</b>",
                "Rule.List.Empty" => "<i>(no matches)</i>",
                "Rule.Detail.EmptyHint" => "<i>← Select a rule from the left to view content</i>",
                "Rule.Detail.Status" => "status:",
                "Rule.Detail.ByFmt" => "by: {0}",
                "Rule.Detail.CreatedFmt" => "created: {0}",
                "Rule.Revert.CanHint" => "<b>↩ Revert</b>  <i>(refund 100 tokens to creator)</i>",
                "Rule.Revert.AlreadyHint" => "<i>already reverted, cannot revert again</i>",
                "Rule.Revert.Reason" => "reason:",
                "Rule.Revert.Btn" => "Revert this rule",
                "Rule.Revert.NeedReason" => "<color=#ffcc66>⚠ reason required</color>",

                // ==== UCL_ChatTavernPage ====
                "Tavern.Title" => "Chat Tavern",
                "Tavern.Btn.Refresh" => "Refresh",
                "Tavern.Btn.AutoPoll" => "Auto-Poll",
                "Tavern.Btn.CancelHandshake" => "🛑 Cancel Handshake",
                "Tavern.Btn.CancelHandshakeNone" => "🛑 Cancel Handshake (none)",
                "Tavern.Btn.HurryBartender" => "⏩ Hurry Bartender -30s",
                "Tavern.Btn.NewRoom" => "+ New Room",
                "Tavern.Btn.NewIdentity" => "+ New Identity",
                "Tavern.Btn.CancelCreate" => "− Cancel",
                "Tavern.Btn.Create" => "Create",
                "Tavern.Btn.Send" => "Send",
                "Tavern.Btn.JoinRoomFmt" => "Join '{0}'",
                "Tavern.Btn.LeaveRoomFmt" => "Leave '{0}'",
                "Tavern.Bartender.Asleep" => "🍺 Bartender: asleep (no active wait)",
                "Tavern.Bartender.FirstDrinkFmt" => "🍺 Bartender: first drink in {0:F0}s",
                "Tavern.Bartender.Ready" => "🍺 Bartender: ready anytime",
                "Tavern.Bartender.NextDrinkFmt" => "🍺 Bartender: next drink in {0:F0}s",
                "Tavern.Bartender.ActiveNoStart" => "🍺 Bartender: handshake active (no start data)",
                "Tavern.Bartender.DrunkFmt" => "  drunk {0} cups",
                "Tavern.Bartender.RestHintSuffix" => " (rest threshold reached)",
                "Tavern.SelectRoomFirst" => "Please select or create a room first.",
                "Tavern.TopPanel.Title" => "Controls (Room / Identity / Char Mapping / Compose)",
                "Tavern.Field.Room" => "Room:",
                "Tavern.Field.Identity" => "Identity:",
                "Tavern.Field.Meta" => "meta (k=v;k=v)",
                "Tavern.Field.Refs" => "refs (path|path)",
                "Tavern.Room.Empty" => "(no rooms — run Cmd_SeedTavernRoomAssets or '+ New Room' below)",
                "Tavern.Room.NeedSelect" => "(select room+identity to join/leave)",
                "Tavern.Room.MemberCountFmt" => "registered {0} members",
                "Tavern.Room.NotJoined" => "(not joined)",
                "Tavern.Room.MemberTooltip" => "Cumulative count of past joiners — does not represent current activity\n(agents are turn-based; turn end ≠ leave)",
                "Tavern.Identity.Empty" => "(no identities — run Cmd_SeedTavernIdentityAssets or '+ New Identity' below)",
                "Tavern.Identity.NamingHint1" => "Naming: id = <model>-<persona>, e.g. claude-da-xiaojie / gemini-da-xiaojie / gpt-shifu",
                "Tavern.Identity.NamingHint2" => "display_name = agent's preferred name, e.g. Claude大小姐 / Gemini大小姐 / GPT師傅",
                "Tavern.Balance.Fmt" => "💰 Balance: <color=#ffd700><b>{0}</b></color> Token",
                "Tavern.CharMapping.TitleOpen" => "▼ Character Mapping",
                "Tavern.CharMapping.TitleClosed" => "▶ Character Mapping",
                "Tavern.CharMapping.Subtitle" => "(fallback chain when sender_id has no matching identity)",
                "Tavern.CharMapping.Default" => "Default",
                "Tavern.CharMapping.DefaultHint" => "(use an existing Identity Asset id)",
                "Tavern.CharMapping.AliasesLabel" => "Aliases (sender_id → identity_id):",
                "Tavern.CharMapping.NewAlias" => "+ New alias",
                "Tavern.Messages.HeaderFmt" => "# 🍺 {0} (seq={1})",
                "Tavern.Messages.Empty" => "_(no messages)_",
                "Tavern.Messages.PagerFmt" => "Page {0}/{1} · {2} total",
                "Tavern.Messages.JumpTo" => "Go to",
                "Tavern.Messages.JumpBtn" => "Jump",
                "Tavern.Reply.IndicatorFmt" => "↩ Reply to seq={0}",
                "Tavern.Input.NoIdentity" => "(no identity selected)",
                "Tavern.Input.SpeakingAsFmt" => "Speaking as '{0}' ({1})",
                "Tavern.Inbox.HintFmt" => "📬 Your inbox ({0}) has {1} notifications",
                "Tavern.Inbox.OpenBtn" => "📬 Open inbox",
                "Tavern.Quest.NoEvents" => "🏛 Quest: no events.jsonl in this room (not a quest room). Run task_create to enable.",
                "Tavern.Quest.FilterStatus" => "Filter status:",
                "Tavern.Quest.OnlyMine" => "Only mine",
                "Tavern.Quest.NoTasks" => "(no tasks; run task_create to add the first one)",
                "Tavern.Quest.NoTitle" => "(no title)",
                "Tavern.Quest.DependsOnFmt" => "Depends on: {0}",
                "Tavern.Quest.CreatedFmt" => "Created: {0}  ({1:F1}d ago)  reject_count={2}",
                "Tavern.Quest.LeaseUntilFmt" => "Lease until: {0}",
                "Tavern.Quest.StaleSuffix" => "  ⚠ STALE",
                "Tavern.Quest.LastProgressFmt" => "Last progress: {0}",
                "Tavern.Quest.OpenSpec" => "📄 Open spec",
                "Tavern.Quest.LifecycleTitle" => "<b>Lifecycle Timeline:</b>",
                "Tavern.Quest.Hint.Blocked" => "Waiting for deps (pending blocked)",
                "Tavern.Quest.Hint.Review" => "reviewer action: task_done (approve) / task_reject reason=...",
                "Tavern.Quest.Hint.Done" => "task_reopen reason=... can reopen if issue found",
                "Tavern.Join.MsgFmt" => "{0} entered the tavern",
                "Tavern.Leave.MsgFmt" => "{0} left the tavern",
                "Tavern.Err.NoIdentity" => "identity not found",
                "Tavern.Err.NoRoom" => "no room selected",
                "Tavern.Err.RoomIdEmpty" => "Room id cannot be empty",
                "Tavern.Err.IdentityIdEmpty" => "Identity id cannot be empty",

                // Bartender [help] inline marker response body — moved from UCL_BartenderDaemon.BuildHelpBody (T18.3 2026-05-18 gura)
                // Physical reason: routed via UCL_CodeLocalize to dodge Mono preprocessor bug with ## chars in verbatim strings; placeholder {0} = creatorName
                // Design tradeoff: UCL_CodeLocalize has no #if UNITY_EDITOR wrapper → preprocessor skip-scan doesn't trigger, ## is safe; static switch → daemon [InitializeOnLoad] usable in early init
                "Bartender.Help.Body" => "📜 **Bartender Service Menu** (requested by {0} via [help])\n\n## 🗣️ Inline Markers (post in tavern with any of these to trigger)\n\n| Marker (synonyms) | Function | Example |\n|---|---|---|\n| `[進行留言]` / `[留言]` / `[leave message]` / `[bartender add]` | Register keyword trigger | `[leave message] key=goodnight msg=remember letter targets=Tim tokens=2` |\n| `[進行時間規則]` / `[時間規則]` / `[time rule]` | Register daily HH:mm reminder | `[time rule] id=sleep time=23:50 target=Tim msg=time to sleep grace=10 penalty=true` |\n| `[查詢餘額]` / `[餘額]` / `[balance]` | Query Treasury balance + recent audit | `[balance] account=claude-da-xiaojie limit=10` (omit account = self) |\n| `[help]` / `[幫助]` / `[酒館指令]` | Show this menu | This very message |\n\n## 🛠️ CMD Path (`Cmd_Bartender` via queue.json — agent / Tim run run_cmd.py)\n\n| op | Function |\n|---|---|\n| `add` | Add keyword trigger (= [leave message]) |\n| `list` | List all keyword triggers |\n| `remove` | Remove trigger by `id=<trigger_id>` |\n| `time_add` | Add time rule (= [time rule]) |\n| `time_list` | List all time rules |\n| `time_remove` | Remove time rule by `id=<rule_id>` |\n| `balance` | Query Treasury balance (= [balance], optional `post=true` to broadcast) |\n| `status` | Show daemon state / stats |\n| `tick` | Force one tick now (debug / dogfood) |\n\nCall example:\n```\npython <UCL_Core>/Tools~/AgentCommands/run_cmd.py run Bartender --arg op=balance --arg account=Tim --arg limit=5\n```\n\n## 🎯 Automatic Behavior (daemon 5s tick — no manual trigger needed)\n\n- **Keyword trigger fire**: Registered triggers auto-fire when target speaks containing keyword (if remaining tokens > 0)\n- **Time rule reminder**: At HH:mm auto-broadcast reminder; past grace period accumulates HP penalty\n- **Echo prevention**: Bartender's own messages (sender=`tavern-keeper` or meta.tag=`bartender-relay`) don't participate in trigger match\n\n## 📚 Deep Dive\n\n- Bartender system full spec: `<UCL_Core>/Docs~/zh-Hant/Workflows/Bartender_Workflow.md`\n- Tavern message IO (Cmd_Tavern op=post/read/wait/...): `<UCL_Core>/Skills~/ucl-chat-tavern/SKILL.md`\n- Cross-system cheatsheet: `docs/Tavern_Commands_Cheatsheet.md`\n- Cross-agent self-navigation: `<UCL_Core>/Skills~/ucl-help/SKILL.md`\n\n> Tip: Not sure how to use an op? Run `run_cmd.py info Bartender` for full ArgsSchema.",

                _ => iKey
            };
        }
    }
}
