
// AutoHeader
// to change the auto header please go to AutoHeader.cs

namespace UCL.Core.LocalizeLib
{
    public static partial class UCL_CodeLocalize
    {
        static public string Get_en(string iKey)
        {
            return iKey switch
            {
                "UCL" => "Unity CommonLib",
                "Edit Modules" => "Edit Modules",
                "Agent Commands" => "Agent Commands",
                "Playlist" => "Playlist",
                "UCL_ModulePlayListPage" => "Edit playlist",
                "Create new module" => "Create new module",
                "Module ID" => "Module ID",
                "EditModulewarning" => "Edits to the built-in module (Core) \nwill become invalid after updates. \nPlease create a new module to add or overwrite existing content. \nIf there are contents with the same ID in different modules\nthe content of the later-loaded module will overwrite the previous one.",
                "EditType" => "Edit type",
                "UCL_ModuleEditType_Builtin" => "Builtin",
                "UCL_ModuleEditType_Runtime" => "Runtime",
                "Save Config" => "Save Config",
                "Load Config" => "Load Config",
                "Open Module Folder" => "Open Module Folder",
                "ModuleService Config" => "ModuleService Config",
                "Loaded modules" => "Loaded modules",
                "Config" => "Config",
                "Current playlist" => "Current playlist",
                "Create new playlist" => "Create new playlist",
                "Load current playlist" => "Load current playlist",
                "ModulePlayListTip" => "To enable the module\nplease press the Edit Playlist button\nand add the module you want to enable to the playlist.",
                "UCL_ModulePlayListPageTip" => "Please select the playlist you want to edit\n or create a new module playlist.",
                "UCL_ModulePlayListPageSaveTip" => "After editing the playlist, please press \"Save\"\nTo apply the current playlist\nplease press \"Load current playlist\"",
                "UCL_CreateNewModulePageTip" => "Please avoid using 'pure numbers' for module IDs (e.g., 3387893998).\nSteam subscriptions use numbers as IDs.\nIf the ID is the same as a Steam subscription module, it will be overwritten.",
                "DeleteTargetDes" => "Delete \"{0}\"",
                "UCL_LocalizeAsset" => "Localize",
                "UCL_ModResourceAsset" => "ModResource",
                "UCL_LanguageCodeAsset" => "LanguageCode",
                "UCL_SteamWorkshopAsset" => "SteamWorkshop",
                "Module Content" => "Module Content",
                "Asset Type" => "Asset Type",
                "Open Folder" => "Open Folder",
                "SteamAPILangCode" => "SteamAPI LangCode",
                "EWorkshopFileType" => "Workshop File Types",
                "Visibility" => "Visibility",
                "Dependencies" => "Dependencies",
                "PublishedFileId" => "Published FileId",
                "ChangeLog" => "Change Log",
                "Create workshop item" => "Create workshop item",
                "Update item to workshop" => "Update item to workshop",
                "ERemoteStoragePublishedFileVisibility_k_ERemoteStoragePublishedFileVisibilityPublic" => "Public",
                "EWorkshopFileType_k_EWorkshopFileTypeCommunity" => "Community",
                "SteamAPILangCode_english" => "English",
                "SteamAPILangCode_tchinese" => "繁體中文",
                "SteamAPILangCode_schinese" => "简体中文",
                "SteamAPILangCode_japanese" => "日本語",
                "SteamAPILangCode_koreana" => "한국어",
                "SteamAPILangCode_russian" => "Русский",
                "AddModulesToCurrentPlaylist" => "Add modules to current playlist",
                "AddNewModulesToCurrentPlaylistContent" => "Would you like to add the newly subscribed modules {0}\nto the current playlist({1})?",
                "HideThisOption" => "Hide this option",
                "Asset Group" => "Asset Group",
                "Confirm" => "Confirm",
                "Cancel" => "Cancel",
                "UCL_UnloadUnusedAssetsOML" => "UnloadUnusedAssets",
                "ReInstall" => "ReInstall",
                "ReInstallAlert" => "Reinstalling will delete all modules.\nDo you want to proceed with the reinstallation? \n(If the game is not functioning properly or won't start, you can try reinstalling it.)",
                "Edit" => "Edit",
                "Preview" => "Preview",
                "OpenFile" => "OpenFile",
                "UCL_LocalizeEditPage" => "LocalizeEditPage",
                "UCL_LocalizeEditPage_Language" => "Language",
                "UCL_LocalizeEditPage_NoLanguageAsset" => "(No UCL_LanguageCodeAsset registered)",
                "UCL_LocalizeEditPage_Current" => "Current:",
                "UCL_LocalizeEditPage_CurLangKey" => "PlayerPrefs Key (CurLangKey)",
                "UCL_LocalizeEditPage_Key" => "Key:",
                "UCL_LocalizeEditPage_ApplyPersist" => "Apply (Persist)",
                "UCL_LocalizeEditPage_Reset" => "Reset",
                "UCL_LocalizeEditPage_ClearOverride" => "Clear Persisted Override",
                "UCL_LocalizeEditPage_OverrideExists" => "  (override exists in UCL_ConfigAsset)",
                "UCL_LocalizeEditPage_UsingDefault" => "  (using default)",
                "UCL_LocalizeEditPage_DefaultFmt" => "  Default: \"{0}\"",
                "UCL_LocalizeEditPage_ApplyHintFmt" => "  💾 Apply persists to UCL_ConfigAsset/{0}.json, auto-loaded on next startup.",
                "UCL_LocalizeEditPage_BootstrapHint" => "  ⌨ Code (session only): UCL_LocalizeService.CurLangKey = \"<your_key>\";",
                "UCL_Download" => "Download",
                "Key" => "Key",
                "MoveElement" => "Move element",
                "SelectAssetTemplateDes" => "Select {0} asset template",
                "OpenModuleRootFolder" => "Open Module Folder",
                "OpenModuleInstallFolder" => "Open Install Folder",
                "CopyToClipboard" => "Copy to clipboard",
                "PasteFromClipboard" => "Paste from clipboard",
                "CopyDescriptionToClipboard" => "Copy to description clipboard",
                "Rename" => "Rename",
                "EditGroup" => "Edit Group",
                "ShowDeleteButton" => "Show Delete Button",
                "CreateFolder" => "Create Folder",
                "Delete" => "Delete",
                "CreateNew" => "Create New",
                "RefreshData" => "Refresh Data",
                "Save" => "Save",
                "Copy" => "Copy",
                "Paste" => "Paste",
                "Back" => "Back",
                "Close" => "Close",
                "Select" => "Select",
                "Search" => "Search",
                "Add" => "Add",
                "SetCount" => "Set Count",
                "SaveBeforeExit?" => "Save before exit?",
                "ExitWitoutSave" => "Exit without save",
                "UCL_SelectAsset" => "Select Asset",
                "UCL_CreateAsset" => "Create Asset",
                "UCL_SaveSuccess" => "Save Success!",

                // ==== UCL_WelcomePage ====
                "Welcome.MenuButton" => "👋 Welcome / Overview",
                "Welcome.Title" => "👋  Welcome to UCL_Core",
                "Welcome.Subtitle" => "Cross-project Unity foundation library  ·  Welcome page v{0}",
                "Welcome.IntroTitle" => "What is UCL_Core?",
                "Welcome.IntroBody" => "UCL_Core is a cross-project Unity foundation library providing core components: data assets (UCL_Asset), module system, localization, Editor Pages, and the Agent Command cross-process system.\nWant to get started? Pick whichever feature card below matches what you're working on.",
                "Welcome.FeaturesTitle" => "Core features (click to open)",
                "Welcome.Asset.Title" => "🧱  UCL_Asset System",
                "Welcome.Asset.Desc" => "JSON-serialized design assets (cards / items / monsters / ...) — Editor-side visual editing, cross-platform IO, SerializeReference polymorphism support.",
                "Welcome.Asset.Btn" => "Open Modules Editor",
                "Welcome.Localize.Title" => "🌐  Localization (string editing)",
                "Welcome.Localize.Desc" => "Edit translation strings, CurLangKey, PlayerPrefs key for each language. To just switch language, use the bar above — no need to enter this page.",
                "Welcome.Localize.Btn" => "Open Localize Editor",
                "Welcome.Lang.Label" => "🌐 Language:",
                "Welcome.Lang.NoneAvailable" => "(No UCL_LanguageCodeAsset found — please create language Asset first)",
                "Welcome.Lang.OpenEditor" => "Advanced…",
                "Welcome.Agent.Title" => "🤖  Agent Commands (agent ↔ Editor cross-process)",
                "Welcome.Agent.Desc" => "AI agent writes queue.json, Editor Watcher auto-executes — built-ins include ExportDocsCatalog / SearchDocs / FindAssetUsages / ValidateAssetFormat.",
                "Welcome.Agent.Btn" => "Open Agent Commands Page",
                "Welcome.Editor.Title" => "🪟  Editor Pages Framework",
                "Welcome.Editor.Desc" => "UCL_GUIPageController + UCL_EditorPage — consistent IMGUI page stack with searchable dropdowns, HelpURL routing, TopBar customization.",
                "Welcome.Editor.Btn" => "PlayerPrefs Editor (sample)",
                "Welcome.DocBtn" => "📖 Docs",
                "Welcome.DocsTitle" => "📚 Documentation index",
                "Welcome.Docs.Index" => "UCL_Core docs index",
                "Welcome.Docs.Architecture" => "Agent Command Architecture",
                "Welcome.Docs.CreateCmd" => "Create Cmd SOP",
                "Welcome.Docs.Validate" => "Validate UCL_Asset format",
                "Welcome.Docs.CompileError" => "🔧 Compile Error Diagnosis Workflow",
                "Welcome.AutoOpenToggle" => " Don't auto-open this page again (still available via UCL → Welcome menu)",
                "Welcome.ResetButton" => "Reset first-open (will pop once on next domain reload)",
                "Welcome.ResetLog" => "[UCL_Welcome] First-open state reset. Will display again on next domain reload.",
                "Welcome.PrefKeyLabel" => "PrefKey_ShownVersion: {0}",
                "Welcome.NotSet" => "(unset)",
                "Welcome.Search.Title" => "🔍 Search Docs",
                "Welcome.Search.Button" => "Search",
                "Welcome.Search.Hint" => "Synonym expansion supported (reads Docs/_synonyms.txt) — e.g. searching 'items' will hit docs titled '道具'. Space-separate multiple terms (AND mode).",
                "Welcome.Search.NoResults" => "(no hits)",
                "Welcome.Search.ResultsCount" => "{0} hit(s) out of {1} scanned",
                "Welcome.Search.OpenButton" => "📖 Open",
                "Welcome.Search.OpenPageButton" => "🔍 Open Doc Search Page",
                "DocSearch.Advanced" => "Advanced options",
                "DocSearch.Mode" => "Search mode",
                "DocSearch.Limit" => "Result limit",
                "DocSearch.SynonymsPath" => "Synonyms path",
                "DocSearch.IncludeArchived" => "Include archived docs",
                "DocSearch.Reveal" => "📂 Reveal",

                _ => iKey
            };
        }
    }
}
