
#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace UCL.Core.EditorTools
{
    /// <summary>
    /// [職責] 掃描 UCL_Core/Docs~/ 內所有 .md 文件，產生 manifest 寫入 UCL_Core/Resources/，供 Build 期 UCL_LocalizedDocsManifest 使用。
    /// [物理意義] 遊戲在 Build 模式下打不開實體 Docs~ 資料夾（已被 Unity 排除），所以必須在 build 之前把「哪些 docs 存在」的快照打包進來。
    ///             Editor 模式不需 manifest（直接 File.Exists 即可），但仍可手動跑 Generator 產生新版以便測試 Build 行為。
    /// [數值影響] 不影響任何遊戲狀態；僅產生資料檔。
    /// [觸發時機]
    ///   1. Build 前自動：透過 IPreprocessBuildWithReport 在每次 Build 開始前自動跑（與 RCG_LocalizedDocsManifestBuildHook 並存，互不干擾）。
    ///   2. 手動：選單 "Tools / UCL / Generate Localized Docs Manifest"。
    /// </summary>
    public static class UCL_LocalizedDocsManifestGenerator
    {
        // [常數] manifest 在 UCL_Core 內的相對路徑（含副檔名）；對應 UCL_LocalizedDocsManifest.ResourcesPath。
        // [物理意義] 必須位於 UCL_Core/Resources/ 下，且檔名（不含 .txt）需與 ResourcesPath 一致。
        private const string ManifestRelativePath = "Resources/UCL_LocalizedDocsManifest.txt";

        // [常數] 要掃描的相對於 UCL_Core 根的資料夾名稱。
        // [物理意義] UCL_Core 的多語系文件全部放在 Docs~ 內（Unity 會自動忽略 ~ 結尾的資料夾，但實體檔案存在）。
        private const string DocsRelativeName = "Docs~";

        /// <summary>
        /// [職責] 手動觸發 manifest 產生的選單入口。
        /// </summary>
        [MenuItem("Tools/UCL/Generate Localized Docs Manifest")]
        public static void GenerateMenuItem()
        {
            string aResult = Generate();
            if (string.IsNullOrEmpty(aResult))
            {
                EditorUtility.DisplayDialog("UCL Localized Docs Manifest", "Failed: UCL_Core path could not be located.", "OK");
                return;
            }
            EditorUtility.DisplayDialog(
                "UCL Localized Docs Manifest",
                $"Generated manifest at:\n{Path.Combine(UCL_EditorPath.CorePath ?? string.Empty, ManifestRelativePath)}",
                "OK"
            );
        }

        /// <summary>
        /// [職責] 掃描 UCL_Core/Docs~/ 並寫入 manifest，回傳 manifest 內容字串。
        /// [計算邏輯]
        ///   1. 透過 UCL_EditorPath.CorePath 定位 UCL_Core 根。
        ///   2. 遞迴蒐集 Docs~/**/*.md 的相對路徑（forward-slash 格式，相對於 UCL_Core 根，即保留 `Docs~/` 前綴）。
        ///   3. 排序、加上 header 註解、寫入 ManifestRelativePath。
        ///   4. 觸發 AssetDatabase.ImportAsset 讓 Unity 立即看到。
        /// [回傳] manifest 內容字串；找不到 UCL_Core 根時回傳空字串並 LogWarning。
        /// </summary>
        public static string Generate()
        {
            // 區塊職責：定位 UCL_Core 根。
            // 物理意義：透過 UCL_EditorPath.CorePath 自動找到模組根路徑（與 ucl_core resolver 相同來源）。
            // 數值影響：找不到時整個 manifest 產生流程跳過，runtime 端會 LogWarning。
            string aCoreRoot = UCL_EditorPath.CorePath;
            if (string.IsNullOrEmpty(aCoreRoot))
            {
                Debug.LogWarning("[UCL_LocalizedDocsManifestGenerator] UCL_EditorPath.CorePath is empty; cannot locate UCL_Core. Manifest skipped.");
                return string.Empty;
            }

            // 區塊職責：蒐集 .md 檔。
            // 物理意義：Docs~/ 下遞迴掃描；路徑相對於 UCL_Core 根（保留 `Docs~/` 前綴），與 ucl_core resolver 接受的 relativePath 一致。
            // 數值影響：影響 manifest 條目數；找不到 Docs~ 資料夾時 manifest 為空。
            string aDocsRoot = Path.Combine(aCoreRoot, DocsRelativeName);
            List<string> aRelativePaths = new();
            if (!Directory.Exists(aDocsRoot))
            {
                Debug.LogWarning($"[UCL_LocalizedDocsManifestGenerator] Docs~ folder not found: {aDocsRoot}; writing empty manifest.");
            }
            else
            {
                foreach (var aPath in Directory.EnumerateFiles(aDocsRoot, "*.md", SearchOption.AllDirectories))
                {
                    // [路徑正規化] 計算相對於 UCL_Core 根的路徑（保留 `Docs~/` 前綴），轉成 forward-slash。
                    string aRel = Path.GetRelativePath(aCoreRoot, aPath).Replace('\\', '/');
                    aRelativePaths.Add(aRel);
                }
                aRelativePaths.Sort(System.StringComparer.Ordinal);
            }

            // 區塊職責：組裝 manifest 文字內容。
            // 物理意義：行首 '#' 為註解，runtime parser 會跳過；正式內容每行一條相對路徑（含 `Docs~/` 前綴）。
            // 數值影響：影響 manifest 檔大小與可讀性；註解段純粹是給 dev 看的。
            var aSB = new System.Text.StringBuilder();
            aSB.AppendLine($"# UCL_LocalizedDocsManifest");
            aSB.AppendLine($"# Auto-generated by UCL_LocalizedDocsManifestGenerator at {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}.");
            aSB.AppendLine($"# DO NOT EDIT BY HAND - re-run \"Tools/UCL/Generate Localized Docs Manifest\" instead.");
            aSB.AppendLine($"# Source: UCL_Core/{DocsRelativeName}/");
            aSB.AppendLine($"# Entries: {aRelativePaths.Count}");
            foreach (var aRel in aRelativePaths)
            {
                aSB.AppendLine(aRel);
            }
            string aContent = aSB.ToString();

            // 區塊職責：寫入檔案 + 通知 AssetDatabase。
            // 物理意義：File.WriteAllText 寫入後，AssetDatabase.ImportAsset 通知 Unity 重新匯入該 TextAsset。
            // 數值影響：寫檔失敗會 throw，generator 中止；正常情況下會更新 manifest。
            string aManifestFullPath = Path.Combine(aCoreRoot, ManifestRelativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(aManifestFullPath)!);
            File.WriteAllText(aManifestFullPath, aContent);

            // [Asset 重新匯入] 讓 Unity 立即看到新內容；UCL_EditorPath.CorePath 已是專案內 Asset 路徑。
            string aAssetPath = $"{aCoreRoot}/{ManifestRelativePath}".Replace('\\', '/');
            // [ForceSynchronousImport] 阻塞直到匯入完成 — Build hook 中必須同步，避免新 manifest 寫入後但尚未匯入就被打包進 Build 的時序問題。
            AssetDatabase.ImportAsset(aAssetPath, ImportAssetOptions.ForceSynchronousImport);

            Debug.Log($"[UCL_LocalizedDocsManifestGenerator] Wrote {aRelativePaths.Count} entries to {aAssetPath}");
            return aContent;
        }
    }

    /// <summary>
    /// [職責] 在每次 Build 開始前自動產生 UCL_Core 的 manifest，避免人為遺忘。
    /// [物理意義] Unity 的 IPreprocessBuildWithReport hook，build 開始時呼叫 OnPreprocessBuild。
    /// [數值影響] 影響 Build 內 UCL_Core/Resources/UCL_LocalizedDocsManifest.txt 的內容；Build 後玩家手上的 fallback 行為以此為準。
    /// </summary>
    public sealed class UCL_LocalizedDocsManifestBuildHook : IPreprocessBuildWithReport
    {
        // [介面屬性] 多個 IPreprocessBuildWithReport 並存時依此排序執行；0 為預設值即可。
        public int callbackOrder => 0;

        /// <summary>
        /// [職責] Build 前自動產生 manifest。
        /// [計算邏輯] 直接呼叫 Generator.Generate；任何例外會中止 build 流程（Unity 的預設行為）。
        /// </summary>
        public void OnPreprocessBuild(BuildReport report)
        {
            Debug.Log("[UCL_LocalizedDocsManifestBuildHook] Pre-build: regenerating UCL_Core localized docs manifest...");
            UCL_LocalizedDocsManifestGenerator.Generate();
        }
    }
}
#endif
